! -*-f90-*-
MODULE constants

  IMPLICIT NONE

  ! INTEGER kind parameters
  INTEGER, PARAMETER :: I4=SELECTED_INT_KIND(9)
  
  ! REAL kind parameters
  INTEGER, PARAMETER :: SP=KIND(1.0)
  INTEGER, PARAMETER :: DP=KIND(1.0d0)

  ! COMPLEX kind parameters
  INTEGER, PARAMETER :: SPC=KIND((1.0,1.0))
  INTEGER, PARAMETER :: DPC=KIND((1.0d0,1.0d0))

  ! Mathematical and physical constants
  REAL(DP), PARAMETER ::    PI=3.141592653589793238462643383279502884197_DP
  REAL(DP), PARAMETER :: TWOPI=6.283185307179586476925286766559005768394_DP

  ! Numerical parameters
  REAL(DP), PARAMETER :: ZERO_TOLERANCE=1.0e-10_DP

  ! ASCII constants
  CHARACTER(LEN=1), PARAMETER :: TAB=ACHAR(9)

  ! Parameters
  LOGICAL,PARAMETER::Debug=.false.
  LOGICAL,PARAMETER::DebugElem=.false.
  LOGICAL,PARAMETER::DebugSlice=.true.
  INTEGER(I4),PARAMETER::MaxNumExtraBases=16
  INTEGER(I4),PARAMETER::MaximumNumVersions=32
  INTEGER(I4),PARAMETER::MaximumNodesInSlice=200

  ! Element Data
  INTEGER(I4),PARAMETER::NumNodePerElem_0D=1
  INTEGER(I4),PARAMETER::NumNodePerElem_1D=2
  INTEGER(I4),PARAMETER::NumNodePerElem_2D=4
  INTEGER(I4),PARAMETER::NumNodePerElem_3D=8
  INTEGER(I4),PARAMETER::NumNodePerElem_4D=16

  ! IO parameters
  INTEGER(I4),PARAMETER::stdin=5
  INTEGER(I4),PARAMETER::stdout=6
  INTEGER(I4),PARAMETER::stderr=0

  ! File name lengths (arbitary. Just make File_len big enough).
  INTEGER(I4),PARAMETER::FILE_LEN=128
  INTEGER(I4),PARAMETER::FILE_EXTENSION=7
  INTEGER(I4),PARAMETER::FILE_3D=2
  INTEGER(I4),PARAMETER::FULL_FILE_LEN=FILE_LEN+FILE_EXTENSION
  INTEGER(I4),PARAMETER::FILE_LEN_3D=FILE_LEN+FILE_3D
  INTEGER(I4),PARAMETER::FULL_FILE_LEN_3D=FILE_LEN_3D+FILE_EXTENSION

  ! Number of redistributions allowed
  INTEGER(I4),PARAMETER::MaxNumRedist=10

END MODULE constants
