      SUBROUTINE DREAL_TIMER(DREAL_TIME)

C#### Subroutine: DREAL_TIMER
C###  Description:
C###     Returns the change in Wallclock time since the last call to 
C###     DREAL_TIMER().

      IMPLICIT NONE
      INCLUDE 'time02.cmn'
      INCLUDE 'cbdi02.cmn'
!     Parameter List
      REAL DREAL_TIME
!     Local Variables
      INTEGER CERROR(50),CERRLEN,ERR
      LOGICAL INITIAL
      REAL*8 CURRENT_TIME,OLD_TIME
      CHARACTER ERROR*255
      SAVE OLD_TIME
      DATA INITIAL,OLD_TIME / .TRUE.,0.0d0 /

      ERR=0
C$OMP CRITICAL(DREAL_TIMER_1)
      CALL CTIMER_REAL(CURRENT_TIME,REAL_TOTAL,ERR,CERROR)
      IF(INITIAL) THEN
        INITIAL=.FALSE.
        OLD_TIME=CURRENT_TIME
      ENDIF
C$OMP END CRITICAL(DREAL_TIMER_1)
      DREAL_TIME=REAL(CURRENT_TIME-OLD_TIME)
      OLD_TIME=CURRENT_TIME
      IF(ERR.NE.0) THEN
        CALL CSTRINGLEN(CERRLEN,CERROR)
        CALL C2FSTRING(CERROR,CERRLEN,OP_STRING(1))
        OP_STRING(1)(CERRLEN:)=' '
        CALL WRITES(IOER,OP_STRING,ERROR,*9999)
      ENDIF

 9999 RETURN
      END


