      SUBROUTINE GETSTR1(PROMPT,STRING,ERROR,*)

C#### Subroutine: GETSTR1
C###  Description:
C###    Gets a string from the terminal.

      IMPLICIT NONE
!     Parameter List
      CHARACTER ERROR*(*),PROMPT*(*),STRING*(*)
!     Local Variables
      INTEGER CERROR(50),CSTRING(100),CSTRLEN,ERR

      CALL ENTERS('GETSTR1',*9999)

      ERR=0
      CALL GETLINE(PROMPT,CSTRING,ERR,CERROR)
      IF(ERR.NE.0) THEN
        CALL CSTRINGLEN(CSTRLEN,CERROR)
        CALL C2FSTRING(CERROR,CSTRLEN,ERROR)
        ERROR(CSTRLEN:)=' '
        GOTO 9999
      ENDIF
      CALL CSTRINGLEN(CSTRLEN,CSTRING)
      CALL C2FSTRING(CSTRING,CSTRLEN,STRING)

      CALL EXITS('GETSTR1')
      RETURN
 9999 CALL ERRORS('GETSTR1',ERROR)
      CALL EXITS('GETSTR1')
      RETURN 1
      END


