      BLOCK DATA BLKCMGUI

      IMPLICIT NONE
      INCLUDE 'cmgui00.cmn'

      DATA CMGUI_DATA_PTR,CMGUI_NODE_PTR,CMGUI_REGION_PTR,
     '  CMGUI_COMMAND_I,CMGUI_COMMAND_O,CMGUI_PROMPT_I,CMGUI_PROMPT_O,
     '  CMGUI_DATA_I,CMGUI_DATA_O /9*0/

      END


