      SUBROUTINE ADD_MATHS_INPUT(MATHS_LABEL,INPUT_LABEL,ERROR,*)

C#### Subroutine: ADD_MATHS_INPUT
C###  Description:
C###    Adds a maths input variable.

      IMPLICIT NONE
      INCLUDE 'maths00.cmn'

!     Parameter List
      CHARACTER MATHS_LABEL*(*),INPUT_LABEL*(*),ERROR*(*)
!     Local Variables
      INTEGER MATHS_INDEX

      CALL ENTERS('ADD_MATHS_INPUT',*9999)

      CALL GET_MATHS_INDEX(MATHS_LABEL,MATHS_INDEX,ERROR,*9999)
      
      CALL SET_LABEL_IN_ARRAY(
     &  MATHS_IN_LABELS_ARRAY,
     &  MATHS_IN_TOTAL_ARRAY,
     &  MATHS_IN_ALLOC_ARRAY,
     &  MATHS_IN_ARRAY_SIZE,
     &  MATHS_INDEX,MATHS_IN_LABELS_LEN,INPUT_LABEL,
     &  ERROR,*9999)

      CALL EXITS('ADD_MATHS_INPUT')
      RETURN
 9999 CALL ERRORS('ADD_MATHS_INPUT',ERROR)
      CALL EXITS('ADD_MATHS_INPUT')
      RETURN 1
      END


