      SUBROUTINE ADD_MATHS_OUTPUT(MATHS_LABEL,OUTPUT_LABEL,ERROR,*)

C#### Subroutine: ADD_MATHS_OUTPUT
C###  Description:
C###    Adds a maths output variable.

      IMPLICIT NONE
      INCLUDE 'maths00.cmn'

!     Parameter List
      CHARACTER MATHS_LABEL*(*),OUTPUT_LABEL*(*),ERROR*(*)
!     Local Variables
      INTEGER MATHS_INDEX

      CALL ENTERS('ADD_MATHS_OUTPUT',*9999)

      CALL GET_MATHS_INDEX(MATHS_LABEL,MATHS_INDEX,ERROR,*9999)
      
      CALL SET_LABEL_IN_ARRAY(
     &  MATHS_OUT_LABELS_ARRAY,
     &  MATHS_OUT_TOTAL_ARRAY,
     &  MATHS_OUT_ALLOC_ARRAY,
     &  MATHS_OUT_ARRAY_SIZE,
     &  MATHS_INDEX,MATHS_OUT_LABELS_LEN,OUTPUT_LABEL,
     &  ERROR,*9999)

      CALL EXITS('ADD_MATHS_OUTPUT')
      RETURN
 9999 CALL ERRORS('ADD_MATHS_OUTPUT',ERROR)
      CALL EXITS('ADD_MATHS_OUTPUT')
      RETURN 1
      END


