      SUBROUTINE GET_MATHS_INPUT_VALUE(MATHS_LABEL,INPUT_LABEL,
     &  VALUE,ERROR,*)

C#### Subroutine: GET_MATHS_INPUT_VALUE
C###  Description:
C###    Gets the current value of a given maths input variable.

      IMPLICIT NONE
      INCLUDE 'maths00.cmn'

!     Parameter List
      INTEGER MATHS_INDEX,INPUT_INDEX
      REAL*8 VALUE
      CHARACTER MATHS_LABEL*(*),INPUT_LABEL*(*),ERROR*(*)

      CALL ENTERS('GET_MATHS_INPUT_VALUE',*9999)

      CALL GET_MATHS_INDEX(MATHS_LABEL,MATHS_INDEX,ERROR,*9999)
      CALL GET_MATHS_INPUT_INDEX(MATHS_LABEL,INPUT_LABEL,
     &  INPUT_INDEX,ERROR,*9999)

      CALL GET_REAL_IN_ARRAY(MATHS_IN_VALUE_ARRAY,
     &  MATHS_IN_VALUE_ALLOC_ARRAY,
     &  MATHS_IN_VALUE_ARRAY_SIZE,
     &  MATHS_INDEX,INPUT_INDEX,VALUE,ERROR,*9999)

      CALL EXITS('GET_MATHS_INPUT_VALUE')
      RETURN
 9999 CALL ERRORS('GET_MATHS_INPUT_VALUE',ERROR)
      CALL EXITS('GET_MATHS_INPUT_VALUE')
      RETURN 1
      END


