      SUBROUTINE GET_MATHS_INPUT_INDEX(MATHS_LABEL,INPUT_LABEL,
     &  INPUT_INDEX,ERROR,*)

C#### Subroutine: GET_MATHS_INPUT_INDEX
C###  Description:
C###    Gets the index of a maths input variable.

      IMPLICIT NONE
      INCLUDE 'maths00.cmn'

!     INPUTeter List
      INTEGER MATHS_INDEX,INPUT_INDEX
      CHARACTER MATHS_LABEL*(*),INPUT_LABEL*(*),ERROR*(*)
      

      CALL ENTERS('GET_MATHS_INPUT_INDEX',*9999)
      
      CALL GET_MATHS_INDEX(MATHS_LABEL,MATHS_INDEX,ERROR,*9999)

      CALL GET_INDEX_IN_ARRAY(MATHS_IN_LABELS_ARRAY,
     &  MATHS_IN_TOTAL_ARRAY,MATHS_IN_ALLOC_ARRAY,
     &  MATHS_IN_ARRAY_SIZE,MATHS_INDEX,MATHS_IN_LABELS_LEN,
     &  INPUT_LABEL,INPUT_INDEX,ERROR,*9999)

      CALL EXITS('GET_MATHS_INPUT_INDEX')
      RETURN
 9999 CALL ERRORS('GET_MATHS_INPUT_INDEX',ERROR)
      CALL EXITS('GET_MATHS_INPUT_INDEX')
      RETURN 1
      END


