      SUBROUTINE GET_MATHS_INPUT_MAP(MATHS_LABEL,
     &  MATHS_IN_LABEL,DEST_TYPE,DEST_LABEL,
     &  DEST_INPUT_LABEL,ERROR,*)

C#### Subroutine: GET_MATHS_INPUT_MAP
C###  Description:
C###    Gets the mapping for a maths input variable.

      IMPLICIT NONE
      INCLUDE 'maths00.cmn'

!     Parameter List
      CHARACTER DEST_LABEL*(*),DEST_INPUT_LABEL*(*),DEST_TYPE*(*),
     &  MATHS_LABEL*(*),MATHS_IN_LABEL*(*),ERROR*(*)
!     Local Variables
      INTEGER MATHS_INDEX,MATHS_IN_INDEX

      CALL ENTERS('GET_MATHS_INPUT_MAP',*9999)
      
      CALL GET_MATHS_INDEX(MATHS_LABEL,MATHS_INDEX,ERROR,*9999)
      CALL GET_MATHS_INPUT_INDEX(MATHS_LABEL,MATHS_IN_LABEL,
     &  MATHS_IN_INDEX,ERROR,*9999)
      
      CALL GET_STRING_IN_ARRAY(
     &  MATHS_IN_MAP_TYPE_ARRAY,
     &  MATHS_IN_MAP_TYPE_ALLOC_ARRAY,
     &  MATHS_IN_MAP_TYPE_ARRAY_SIZE,
     &  MATHS_IN_MAP_TYPE_LEN,
     &  MATHS_INDEX,MATHS_IN_INDEX,DEST_TYPE,
     &  ERROR,*9999)
      
      IF(DEST_TYPE.NE.'VALUE')THEN

        CALL GET_STRING_IN_ARRAY(
     &    MATHS_IN_MAP_PARENT_ARRAY,
     &    MATHS_IN_MAP_PARENT_ALLOC_ARRAY,
     &    MATHS_IN_MAP_PARENT_ARRAY_SIZE,
     &    MATHS_IN_MAP_PARENT_LEN,
     &    MATHS_INDEX,MATHS_IN_INDEX,DEST_LABEL,
     &    ERROR,*9999)

        CALL GET_STRING_IN_ARRAY(
     &    MATHS_IN_MAP_CHILD_ARRAY,
     &    MATHS_IN_MAP_CHILD_ALLOC_ARRAY,
     &    MATHS_IN_MAP_CHILD_ARRAY_SIZE,
     &    MATHS_IN_MAP_CHILD_LEN,
     &    MATHS_INDEX,MATHS_IN_INDEX,DEST_INPUT_LABEL,
     &    ERROR,*9999)
     
      ELSE
        DEST_LABEL = ' '
        DEST_INPUT_LABEL = ' '
      ENDIF

      CALL EXITS('GET_MATHS_INPUT_MAP')
      RETURN
 9999 CALL ERRORS('GET_MATHS_INPUT_MAP',ERROR)
      CALL EXITS('GET_MATHS_INPUT_MAP')
      RETURN 1
      END

