      SUBROUTINE GET_MATHS_INDEX(MATHS_LABEL,MATHS_INDEX,ERROR,*)

C#### Subroutine: GET_MATHS_INDEX
C###  Description:
C###    Gets the index of a maths object.

      IMPLICIT NONE
      INCLUDE 'maths00.cmn'

!     Parameter List
      INTEGER MATHS_INDEX
      CHARACTER MATHS_LABEL*(*),ERROR*(*)
      

      CALL ENTERS('GET_MATHS_INDEX',*9999)

      CALL GET_INDEX(MATHS_LABELS_PTR,
     &  TOTAL_MATHS_LABELS,ALLOCATED_MATHS_LABELS,
     &  MATHS_LABELS_LEN,MATHS_LABEL,MATHS_INDEX,ERROR,*9999)

      CALL EXITS('GET_MATHS_INDEX')
      RETURN
 9999 CALL ERRORS('GET_MATHS_INDEX',ERROR)
      CALL EXITS('GET_MATHS_INDEX')
      RETURN 1
      END


