      SUBROUTINE GET_MATHS_INPUT_LABEL(MATHS_LABEL,
     &  INPUT_INDEX,INPUT_LABEL,ERROR,*)

C#### Subroutine: GET_MATHS_INPUT_LABEL
C###  Description:
C###    Gets the maths input varibale given an index.

      IMPLICIT NONE
      INCLUDE 'maths00.cmn'

!     Parameter List
      INTEGER MATHS_INDEX,INPUT_INDEX
      CHARACTER MATHS_LABEL*(*),INPUT_LABEL*(*),ERROR*(*)

      CALL ENTERS('GET_MATHS_INPUT_LABEL',*9999)

      CALL GET_MATHS_INDEX(MATHS_LABEL,MATHS_INDEX,ERROR,*9999)

      CALL GET_LABEL_IN_ARRAY(MATHS_IN_LABELS_ARRAY,
     &  MATHS_IN_ALLOC_ARRAY,MATHS_IN_ARRAY_SIZE,
     &  MATHS_INDEX,INPUT_INDEX,MATHS_IN_LABELS_LEN,INPUT_LABEL,
     &  ERROR,*9999)

      CALL EXITS('GET_MATHS_INPUT_LABEL')
      RETURN
 9999 CALL ERRORS('GET_MATHS_INPUT_LABEL',ERROR)
      CALL EXITS('GET_MATHS_INPUT_LABEL')
      RETURN 1
      END


