      SUBROUTINE GET_MATHS_OUTPUT_INDEX(MATHS_LABEL,OUTPUT_LABEL,
     &  OUTPUT_INDEX,ERROR,*)

C#### Subroutine: GET_MATHS_OUTPUT_INDEX
C###  Description:
C###    Gets the index of a maths output variable.

      IMPLICIT NONE
      INCLUDE 'maths00.cmn'

!     OUTPUTeter List
      INTEGER MATHS_INDEX,OUTPUT_INDEX
      CHARACTER MATHS_LABEL*(*),OUTPUT_LABEL*(*),ERROR*(*)
      

      CALL ENTERS('GET_MATHS_OUTPUT_INDEX',*9999)
      
      CALL GET_MATHS_INDEX(MATHS_LABEL,MATHS_INDEX,ERROR,*9999)

      CALL GET_INDEX_IN_ARRAY(MATHS_OUT_LABELS_ARRAY,
     &  MATHS_OUT_TOTAL_ARRAY,MATHS_OUT_ALLOC_ARRAY,
     &  MATHS_OUT_ARRAY_SIZE,MATHS_INDEX,MATHS_OUT_LABELS_LEN,
     &  OUTPUT_LABEL,OUTPUT_INDEX,ERROR,*9999)

      CALL EXITS('GET_MATHS_OUTPUT_INDEX')
      RETURN
 9999 CALL ERRORS('GET_MATHS_OUTPUT_INDEX',ERROR)
      CALL EXITS('GET_MATHS_OUTPUT_INDEX')
      RETURN 1
      END


