      SUBROUTINE GET_MATHS_OUTPUT_LABEL(MATHS_LABEL,
     &  OUTPUT_INDEX,OUTPUT_LABEL,ERROR,*)

C#### Subroutine: SET_LABEL
C###  Description:
C###    Gets the maths output variable label given an index.

      IMPLICIT NONE
      INCLUDE 'maths00.cmn'

!     OUTPUTeter List
      INTEGER MATHS_INDEX,OUTPUT_INDEX
      CHARACTER MATHS_LABEL*(*),OUTPUT_LABEL*(*),ERROR*(*)

      CALL ENTERS('GET_MATHS_OUTPUT_LABEL',*9999)

      CALL GET_MATHS_INDEX(MATHS_LABEL,MATHS_INDEX,ERROR,*9999)

      CALL GET_LABEL_IN_ARRAY(MATHS_OUT_LABELS_ARRAY,
     &  MATHS_OUT_ALLOC_ARRAY,MATHS_OUT_ARRAY_SIZE,
     &  MATHS_INDEX,OUTPUT_INDEX,MATHS_OUT_LABELS_LEN,
     &  OUTPUT_LABEL,ERROR,*9999)

      CALL EXITS('GET_MATHS_OUTPUT_LABEL')
      RETURN
 9999 CALL ERRORS('GET_MATHS_OUTPUT_LABEL',ERROR)
      CALL EXITS('GET_MATHS_OUTPUT_LABEL')
      RETURN 1
      END


