      SUBROUTINE GET_MATHS_INPUT_RCQS_INDEX(MATHS_LABEL,INPUT_LABEL,
     &  RCQS_INDEX,ERROR,*)

C#### Subroutine: GET_MATHS_INPUT_RCQS_INDEX
C###  Description:
C###    Gets the RCQS index for a given maths input variable.

      IMPLICIT NONE
      INCLUDE 'maths00.cmn'

!     Parameter List
      INTEGER MATHS_INDEX,INPUT_INDEX,RCQS_INDEX
      CHARACTER MATHS_LABEL*(*),INPUT_LABEL*(*),ERROR*(*)

      CALL ENTERS('GET_MATHS_INPUT_RCQS_INDEX',*9999)

      CALL GET_MATHS_INDEX(MATHS_LABEL,MATHS_INDEX,ERROR,*9999)
      CALL GET_MATHS_INPUT_INDEX(MATHS_LABEL,INPUT_LABEL,
     &  INPUT_INDEX,ERROR,*9999)

      CALL GET_INTEGER_IN_ARRAY(MATHS_IN_RCQS_INDEX_ARRAY,
     &  MATHS_IN_RCQS_INDEX_ALLOC_ARRAY,
     &  MATHS_IN_RCQS_INDEX_ARRAY_SIZE,
     &  MATHS_INDEX,INPUT_INDEX,RCQS_INDEX,ERROR,*9999)

      CALL EXITS('GET_MATHS_INPUT_RCQS_INDEX')
      RETURN
 9999 CALL ERRORS('GET_MATHS_INPUT_RCQS_INDEX',ERROR)
      CALL EXITS('GET_MATHS_INPUT_RCQS_INDEX')
      RETURN 1
      END


