      SUBROUTINE GET_MATHS_OUTPUT_YQS_INDEX(MATHS_LABEL,OUTPUT_LABEL,
     &  YQS_INDEX,ERROR,*)

C#### Subroutine: GET_MATHS_OUTPUT_YQS_INDEX
C###  Description:
C###    Gets the YQS index for a given maths output variable.

      IMPLICIT NONE
      INCLUDE 'maths00.cmn'

!     OUTPUTeter List
      INTEGER MATHS_INDEX,OUTPUT_INDEX,YQS_INDEX
      CHARACTER MATHS_LABEL*(*),OUTPUT_LABEL*(*),ERROR*(*)

      CALL ENTERS('GET_MATHS_OUTPUT_YQS_INDEX',*9999)

      CALL GET_MATHS_INDEX(MATHS_LABEL,MATHS_INDEX,ERROR,*9999)
      CALL GET_MATHS_OUTPUT_INDEX(MATHS_LABEL,OUTPUT_LABEL,
     &  OUTPUT_INDEX,ERROR,*9999)

      CALL GET_INTEGER_IN_ARRAY(MATHS_OUT_YQS_INDEX_ARRAY,
     &  MATHS_OUT_YQS_INDEX_ALLOC_ARRAY,
     &  MATHS_OUT_YQS_INDEX_ARRAY_SIZE,
     &  MATHS_INDEX,OUTPUT_INDEX,YQS_INDEX,ERROR,*9999)

      CALL EXITS('GET_MATHS_OUTPUT_YQS_INDEX')
      RETURN
 9999 CALL ERRORS('GET_MATHS_OUTPUT_YQS_INDEX',ERROR)
      CALL EXITS('GET_MATHS_OUTPUT_YQS_INDEX')
      RETURN 1
      END


