      SUBROUTINE GET_MATHS_SOLVED(MATHS_LABEL,SOLVED,ERROR,*)

C#### Subroutine: GET_MATHS_SOLVED
C###  Description:
C###    Gets the solved of the maths object.

      IMPLICIT NONE
      INCLUDE 'maths00.cmn'

!     Parameter List
      INTEGER MATHS_INDEX,SOLVED
      CHARACTER MATHS_LABEL*(*),ERROR*(*)

      CALL ENTERS('GET_MATHS_SOLVED',*9999)

      CALL GET_MATHS_INDEX(MATHS_LABEL,MATHS_INDEX,ERROR,*9999)

      CALL GET_INTEGER(MATHS_SOLVED_PTR,ALLOCATED_MATHS_SOLVED,
     &  MATHS_INDEX,SOLVED,ERROR,*9999)

      CALL EXITS('GET_MATHS_SOLVED')
      RETURN
 9999 CALL ERRORS('GET_MATHS_SOLVED',ERROR)
      CALL EXITS('GET_MATHS_SOLVED')
      RETURN 1
      END


