      SUBROUTINE GET_MATHS_INPUT_TOTAL(MATHS_LABEL,TOTAL_MATHS_INPUT,
     &  ERROR,*)

C#### Subroutine: GET_MATHS_INPUT_TOTAL
C###  Description:
C###    Gets the total number of maths input variables.

      IMPLICIT NONE
      INCLUDE 'maths00.cmn'

!     Parameter List
      INTEGER TOTAL_MATHS_INPUT,MATHS_INDEX
      CHARACTER MATHS_LABEL*255,ERROR*(*)

      CALL ENTERS('GET_MATHS_INPUT_TOTAL',*9999)
      
      CALL GET_MATHS_INDEX(MATHS_LABEL,MATHS_INDEX,ERROR,*9999)
      
      CALL GET_TOTAL_IN_ARRAY(
     &  %VAL(MATHS_IN_TOTAL_ARRAY),MATHS_IN_ARRAY_SIZE,
     &  MATHS_INDEX,TOTAL_MATHS_INPUT,ERROR,*9999)

      CALL EXITS('GET_MATHS_INPUT_TOTAL')
      RETURN
 9999 CALL ERRORS('GET_MATHS_INPUT_TOTAL',ERROR)
      CALL EXITS('GET_MATHS_INPUT_TOTAL')
      RETURN 1
      END


