      SUBROUTINE GET_MATHS_INPUT_INITIAL_VALUE(MATHS_LABEL,
     &  INPUT_LABEL,INITIAL_VALUE,ERROR,*)

C#### Subroutine: GET_MATHS_INPUT_INITIAL_VALUE
C###  Description:
C###    Gets the initial value of a given maths input variable.

      IMPLICIT NONE
      INCLUDE 'maths00.cmn'

!     Parameter List
      INTEGER MATHS_INDEX,INPUT_INDEX
      REAL*8 INITIAL_VALUE
      CHARACTER MATHS_LABEL*(*),INPUT_LABEL*(*),ERROR*(*)

      CALL ENTERS('GET_MATHS_INPUT_INITIAL_VALUE',*9999)

      CALL GET_MATHS_INDEX(MATHS_LABEL,MATHS_INDEX,ERROR,*9999)
      CALL GET_MATHS_INPUT_INDEX(MATHS_LABEL,INPUT_LABEL,
     &  INPUT_INDEX,ERROR,*9999)

      CALL GET_REAL_IN_ARRAY(MATHS_IN_INIT_VALUE_ARRAY,
     &  MATHS_IN_INIT_VALUE_ALLOC_ARRAY,
     &  MATHS_IN_INIT_VALUE_ARRAY_SIZE,
     &  MATHS_INDEX,INPUT_INDEX,INITIAL_VALUE,ERROR,*9999)

      CALL EXITS('GET_MATHS_INPUT_INITIAL_VALUE')
      RETURN
 9999 CALL ERRORS('GET_MATHS_INPUT_INITIAL_VALUE',ERROR)
      CALL EXITS('GET_MATHS_INPUT_INITIAL_VALUE')
      RETURN 1
      END


