      SUBROUTINE GET_MATHS_VARIANT(MATHS_LABEL,VARIANT,ERROR,*)

C#### Subroutine: GET_MATHS_VARIANT
C###  Description:
C###    Gets the variant value of the maths object.

      IMPLICIT NONE
      INCLUDE 'maths00.cmn'

!     Parameter List
      INTEGER MATHS_INDEX,VARIANT
      CHARACTER MATHS_LABEL*(*),ERROR*(*)

      CALL ENTERS('GET_MATHS_VARIANT',*9999)

      CALL GET_MATHS_INDEX(MATHS_LABEL,MATHS_INDEX,ERROR,*9999)

      CALL GET_INTEGER(MATHS_VARIANTS_PTR,ALLOCATED_MATHS_VARIANTS,
     &  MATHS_INDEX,VARIANT,ERROR,*9999)

      CALL EXITS('GET_MATHS_VARIANT')
      RETURN
 9999 CALL ERRORS('GET_MATHS_VARIANT',ERROR)
      CALL EXITS('GET_MATHS_VARIANT')
      RETURN 1
      END


