      SUBROUTINE GET_MATHS_OUTPUT_VALUE(MATHS_LABEL,OUTPUT_LABEL,
     &  VALUE,ERROR,*)

C#### Subroutine: GET_MATHS_OUTPUT_VALUE
C###  Description:
C###    Gets the YQS value for a given maths output variable.

      IMPLICIT NONE
      INCLUDE 'maths00.cmn'

!     Parameter List
      INTEGER MATHS_INDEX,OUTPUT_INDEX
      REAL*8 VALUE
      CHARACTER MATHS_LABEL*(*),OUTPUT_LABEL*(*),ERROR*(*)

      CALL ENTERS('GET_MATHS_OUTPUT_VALUE',*9999)

      CALL GET_MATHS_INDEX(MATHS_LABEL,MATHS_INDEX,ERROR,*9999)
      CALL GET_MATHS_OUTPUT_INDEX(MATHS_LABEL,OUTPUT_LABEL,
     &  OUTPUT_INDEX,ERROR,*9999)

      CALL GET_REAL_IN_ARRAY(MATHS_OUT_VALUE_ARRAY,
     &  MATHS_OUT_VALUE_ALLOC_ARRAY,
     &  MATHS_OUT_VALUE_ARRAY_SIZE,
     &  MATHS_INDEX,OUTPUT_INDEX,VALUE,ERROR,*9999)

      CALL EXITS('GET_MATHS_OUTPUT_VALUE')
      RETURN
 9999 CALL ERRORS('GET_MATHS_OUTPUT_VALUE',ERROR)
      CALL EXITS('GET_MATHS_OUTPUT_VALUE')
      RETURN 1
      END


