      SUBROUTINE GET_MATHS_LABEL(MATHS_INDEX,MATHS_LABEL,ERROR,*)

C#### Subroutine: GET_MATHS_LABEL
C###  Description: GET_MATHS_LABEL
C###     Get the maths label given an index.

      IMPLICIT NONE
      INCLUDE 'maths00.cmn'

!     Parameter List
      INTEGER MATHS_INDEX
      CHARACTER MATHS_LABEL*(*),ERROR*(*)

      CALL ENTERS('GET_MATHS_LABEL',*9999)

      CALL GET_LABEL(MATHS_LABELS_PTR,ALLOCATED_MATHS_LABELS,
     &  MATHS_INDEX,MATHS_LABELS_LEN,MATHS_LABEL,ERROR,*9999)

      CALL EXITS('GET_MATHS_LABEL')
      RETURN
 9999 CALL ERRORS('GET_MATHS_LABEL',ERROR)
      CALL EXITS('GET_MATHS_LABEL')
      RETURN 1
      END


