      SUBROUTINE GET_MATHS_OUTPUT_TOTAL(MATHS_LABEL,
     &  TOTAL_MATHS_OUTPUT,ERROR,*)

C#### Subroutine: GET_MATHS_OUTPUT_TOTAL
C###  Description:
C###    Gets the total number of maths output variables.

      IMPLICIT NONE
      INCLUDE 'maths00.cmn'

!     OUTPUTeter List
      INTEGER TOTAL_MATHS_OUTPUT,MATHS_INDEX
      CHARACTER MATHS_LABEL*255,ERROR*(*)

      CALL ENTERS('GET_MATHS_OUTPUT_TOTAL',*9999)
      
      CALL GET_MATHS_INDEX(MATHS_LABEL,MATHS_INDEX,ERROR,*9999)
      
      CALL GET_TOTAL_IN_ARRAY(
     &  %VAL(MATHS_OUT_TOTAL_ARRAY),MATHS_OUT_ARRAY_SIZE,
     &  MATHS_INDEX,TOTAL_MATHS_OUTPUT,ERROR,*9999)

      CALL EXITS('GET_MATHS_OUTPUT_TOTAL')
      RETURN
 9999 CALL ERRORS('GET_MATHS_OUTPUT_TOTAL',ERROR)
      CALL EXITS('GET_MATHS_OUTPUT_TOTAL')
      RETURN 1
      END


