      BLOCK DATA MATHS00

      IMPLICIT NONE
      INCLUDE 'maths00.cmn'

! Maths Labels
      DATA MATHS_LABELS_PTR/0/
      DATA ALLOCATED_MATHS_LABELS/0/
      DATA TOTAL_MATHS_LABELS/0/

! Maths Variants
      DATA MATHS_VARIANTS_PTR/0/
      DATA ALLOCATED_MATHS_VARIANTS/0/

! Maths verbosity
      DATA MATHS_VERBOSE_PTR/0/
      DATA ALLOCATED_MATHS_VERBOSE/0/

! Maths Solved
      DATA MATHS_SOLVED_PTR/0/
      DATA ALLOCATED_MATHS_SOLVED/0/

! Maths OUTPUT
      DATA MATHS_OUT_LABELS_ARRAY/0/
      DATA MATHS_OUT_TOTAL_ARRAY/0/
      DATA MATHS_OUT_ALLOC_ARRAY/0/
      DATA MATHS_OUT_ARRAY_SIZE/0/

! Maths Parameters
      DATA MATHS_IN_LABELS_ARRAY/0/
      DATA MATHS_IN_TOTAL_ARRAY/0/
      DATA MATHS_IN_ALLOC_ARRAY/0/
      DATA MATHS_IN_ARRAY_SIZE/0/

! Maths OUTPUT YQS index
      DATA MATHS_OUT_YQS_INDEX_ARRAY/0/
      DATA MATHS_OUT_YQS_INDEX_ALLOC_ARRAY/0/
      DATA MATHS_OUT_YQS_INDEX_ARRAY_SIZE/0/
      
! Maths OUTPUT Value
      DATA MATHS_OUT_VALUE_ARRAY/0/
      DATA MATHS_OUT_VALUE_ALLOC_ARRAY/0/
      DATA MATHS_OUT_VALUE_ARRAY_SIZE/0/
      
! Maths Parameters RCQS index
      DATA MATHS_IN_RCQS_INDEX_ARRAY/0/
      DATA MATHS_IN_RCQS_INDEX_ALLOC_ARRAY/0/
      DATA MATHS_IN_RCQS_INDEX_ARRAY_SIZE/0/

! Maths Parameters values
      DATA MATHS_IN_INIT_VALUE_ARRAY/0/
      DATA MATHS_IN_INIT_VALUE_ALLOC_ARRAY/0/
      DATA MATHS_IN_INIT_VALUE_ARRAY_SIZE/0/

! Maths Parameters values
      DATA MATHS_IN_VALUE_ARRAY/0/
      DATA MATHS_IN_VALUE_ALLOC_ARRAY/0/
      DATA MATHS_IN_VALUE_ARRAY_SIZE/0/

! Equation Parameters map type
      DATA MATHS_IN_MAP_TYPE_ARRAY/0/
      DATA MATHS_IN_MAP_TYPE_ALLOC_ARRAY/0/
      DATA MATHS_IN_MAP_TYPE_ARRAY_SIZE/0/

! Equation Parameters map parent label
      DATA MATHS_IN_MAP_PARENT_ARRAY/0/
      DATA MATHS_IN_MAP_PARENT_ALLOC_ARRAY/0/
      DATA MATHS_IN_MAP_PARENT_ARRAY_SIZE/0/

! Equation Parameters map INPUT label
      DATA MATHS_IN_MAP_CHILD_ARRAY/0/
      DATA MATHS_IN_MAP_CHILD_ALLOC_ARRAY/0/
      DATA MATHS_IN_MAP_CHILD_ARRAY_SIZE/0/

      END



