      SUBROUTINE PRINT_MATHS_OUTPUT_VALUES(MATHS_LABEL,ERROR,*)

C#### Subroutine: PRINT_MATHS_OUTPUT_VALUES
C###  Description:
C###    Prints the current values of an maths output variables.

      IMPLICIT NONE
      INCLUDE 'cbdi02.cmn'
      INCLUDE 'colours00.cmn'
      INCLUDE 'maths00.cmn'

!     Parameter List
      CHARACTER MATHS_LABEL*(MATHS_LABELS_LEN),ERROR*(*)

!     Local Variables
      INTEGER INDEX,TOTAL
      INTEGER IB1,IB2,IE1,IE2
      REAL*8 VALUE
      CHARACTER OLABEL*(MATHS_OUT_LABELS_LEN),
     &  VALUE_STRING*32

      CALL ENTERS('PRINT_MATHS_OUTPUT_VALUES',*9999)
          
      CALL GET_MATHS_INDEX(MATHS_LABEL,INDEX,ERROR,*9999)

      CALL ASSERT(INDEX.NE.0,'Error: Maths label not found',
     &  ERROR,*9999)

      CALL GET_MATHS_OUTPUT_TOTAL(MATHS_LABEL,TOTAL,ERROR,*9999)
      
      DO INDEX=1,TOTAL
        CALL GET_MATHS_OUTPUT_LABEL(MATHS_LABEL,INDEX,OLABEL,
     &    ERROR,*9999)
        CALL STRING_TRIM(OLABEL,IB1,IE1)
        CALL GET_MATHS_OUTPUT_VALUE(MATHS_LABEL,OLABEL,VALUE,
     &    ERROR,*9999)
        WRITE(VALUE_STRING,'('' = '',D12.5)') VALUE
        CALL STRING_TRIM(VALUE_STRING,IB2,IE2)
        WRITE(OP_STRING,'(6X,'''//COLOUR_CHILD//OLABEL(IB1:IE1)
     &    //COLOUR_DEFAULT//' '//VALUE_STRING(IB2:IE2)//''')')
        CALL WRITES(IOFI,OP_STRING,ERROR,*9999)
      ENDDO
      
       

      CALL EXITS('PRINT_MATHS_OUTPUT_VALUES')
      RETURN
 9999 CALL ERRORS('PRINT_MATHS_OUTPUT_VALUES',ERROR)
      CALL EXITS('PRINT_MATHS_OUTPUT_VALUES')
      RETURN 1
      END


