      SUBROUTINE SET_MATHS_OUTPUT_VALUE(MATHS_LABEL,OUTPUT_LABEL,
     &  VALUE,ERROR,*)

C#### Subroutine: SET_MATHS_OUTPUT_VALUE
C###  Description:
C###    Sets the value of a maths output variable.

      IMPLICIT NONE
      INCLUDE 'maths00.cmn'

!     OUTPUTeter List
      REAL*8 VALUE
      CHARACTER MATHS_LABEL*(*),OUTPUT_LABEL*(*),ERROR*(*)
!     Local Variables
      INTEGER MATHS_INDEX,OUTPUT_INDEX

      CALL ENTERS('SET_MATHS_OUTPUT_VALUE',*9999)

      CALL GET_MATHS_INDEX(MATHS_LABEL,MATHS_INDEX,ERROR,*9999)
      CALL GET_MATHS_OUTPUT_INDEX(MATHS_LABEL,OUTPUT_LABEL,
     &  OUTPUT_INDEX,ERROR,*9999)
      
      CALL SET_REAL_IN_ARRAY(
     &  MATHS_OUT_VALUE_ARRAY,
     &  MATHS_OUT_VALUE_ALLOC_ARRAY,
     &  MATHS_OUT_VALUE_ARRAY_SIZE,
     &  MATHS_INDEX,OUTPUT_INDEX,VALUE,
     &  ERROR,*9999)

      CALL EXITS('SET_MATHS_OUTPUT_VALUE')
      RETURN
 9999 CALL ERRORS('SET_MATHS_OUTPUT_VALUE',ERROR)
      CALL EXITS('SET_MATHS_OUTPUT_VALUE')
      RETURN 1
      END


