      SUBROUTINE SET_MATHS_VERBOSE(MATHS_LABEL,MATHS_VERBOSE,
     &  ERROR,*)

C#### Subroutine: SET_MATHS_VERBOSE
C###  Description:
C###    Sets the verbosity level of a maths object.

      IMPLICIT NONE
      INCLUDE 'maths00.cmn'

!     Parameter List
      INTEGER MATHS_INDEX,MATHS_VERBOSE
      CHARACTER MATHS_LABEL*(*),ERROR*(*)

      CALL ENTERS('SET_MATHS_VERBOSE',*9999)

      CALL GET_MATHS_INDEX(MATHS_LABEL,MATHS_INDEX,ERROR,*9999)

      CALL SET_INTEGER(MATHS_VERBOSE_PTR,ALLOCATED_MATHS_VERBOSE,
     &  MATHS_INDEX,MATHS_VERBOSE,ERROR,*9999)

      CALL EXITS('SET_MATHS_VERBOSE')
      RETURN
 9999 CALL ERRORS('SET_MATHS_VERBOSE',ERROR)
      CALL EXITS('SET_MATHS_VERBOSE')
      RETURN 1
      END


