      SUBROUTINE SET_MATHS_SOLVED(MATHS_LABEL,SOLVED,ERROR,*)

C#### Subroutine: SET_MATHS_SOLVED
C###  Description:
C###    Sets the solved state for a maths object.

      IMPLICIT NONE
      INCLUDE 'maths00.cmn'

!     Parameter List
      INTEGER MATHS_INDEX,SOLVED
      CHARACTER MATHS_LABEL*(*),ERROR*(*)

      CALL ENTERS('SET_MATHS_SOLVED',*9999)

      CALL GET_MATHS_INDEX(MATHS_LABEL,MATHS_INDEX,ERROR,*9999)

      CALL SET_INTEGER(MATHS_SOLVED_PTR,ALLOCATED_MATHS_SOLVED,
     &  MATHS_INDEX,SOLVED,ERROR,*9999)

      CALL EXITS('SET_MATHS_SOLVED')
      RETURN
 9999 CALL ERRORS('SET_MATHS_SOLVED',ERROR)
      CALL EXITS('SET_MATHS_SOLVED')
      RETURN 1
      END


