      SUBROUTINE SET_MATHS_INPUT_RCQS_INDEX(MATHS_LABEL,INPUT_LABEL,
     &  RCQS_INDEX,ERROR,*)

C#### Subroutine: SET_MATHS_INPUT_RCQS_INDEX
C###  Description:
C###    Sets the RCQS index for a maths input variable.

      IMPLICIT NONE
      INCLUDE 'maths00.cmn'

!     Parameter List
      INTEGER RCQS_INDEX
      CHARACTER MATHS_LABEL*(*),INPUT_LABEL*(*),ERROR*(*)
!     Local Variables
      INTEGER MATHS_INDEX,INPUT_INDEX

      CALL ENTERS('SET_MATHS_INPUT_RCQS_INDEX',*9999)

      CALL GET_MATHS_INDEX(MATHS_LABEL,MATHS_INDEX,ERROR,*9999)
      CALL GET_MATHS_INPUT_INDEX(MATHS_LABEL,INPUT_LABEL,
     &  INPUT_INDEX,ERROR,*9999)
      
      CALL SET_INTEGER_IN_ARRAY(
     &  MATHS_IN_RCQS_INDEX_ARRAY,
     &  MATHS_IN_RCQS_INDEX_ALLOC_ARRAY,
     &  MATHS_IN_RCQS_INDEX_ARRAY_SIZE,
     &  MATHS_INDEX,INPUT_INDEX,RCQS_INDEX,
     &  ERROR,*9999)

      CALL EXITS('SET_MATHS_INPUT_RCQS_INDEX')
      RETURN
 9999 CALL ERRORS('SET_MATHS_INPUT_RCQS_INDEX',ERROR)
      CALL EXITS('SET_MATHS_INPUT_RCQS_INDEX')
      RETURN 1
      END


