      SUBROUTINE IPANAL(DIPOLE_CEN_NTIME,DIPOLE_DIR_NTIME,IBT,IDO,INP,
     '  NBJ,NDIPOLES,NEELEM,NENP,NKJE,NKH,NPF,
     '  NP_INTERFACE,NPNE,NPNODE,nr,NRE,NVHP,NVJE,nx,NYNP,CE,DIPOLE_CEN,
     '  DIPOLE_DIR,SE,XA,XE,XP,YP,YQ,ACTIVATION,ERROR,*)

C#### Subroutine: IPANAL
C###  Description:
C###    IPANAL inputs analytic solution parameters for region nr and
C###    problem nx.

      IMPLICIT NONE
      INCLUDE 'geom00.cmn'
      INCLUDE 'ityp00.cmn'
!     Parameter List
      INTEGER DIPOLE_CEN_NTIME(NDIPOLEM,NRM),
     '  DIPOLE_DIR_NTIME(NDIPOLEM,NRM),IBT(3,NIM,NBFM),
     '  IDO(NKM,NNM,0:NIM,NBFM),INP(NNM,NIM,NBFM),
     '  NBJ(NJM,NEM),NDIPOLES(NRM),NEELEM(0:NE_R_M,0:NRM),
     '  NENP(NPM,0:NEPM),NKJE(NKM,NNM,NJM,NEM),NKH(NHM,NPM,NCM,0:NRM),
     '  NPF(9,NFM),NP_INTERFACE(0:NPM,0:3),NPNE(NNM,NBFM,NEM),
     '  NPNODE(0:NP_R_M,0:NRM),nr,NRE(NEM),
     '  NVHP(NHM,NPM,NCM),NVJE(NNM,NBFM,NJM,NEM),nx,
     '  NYNP(NKM,NVM,NHM,NPM,0:NRCM,NCM,NRM)
      REAL*8 CE(NMM,NEM),DIPOLE_CEN(4,0:NDIPTIMM,NDIPOLEM,NRM),
     '  DIPOLE_DIR(4,0:NDIPTIMM,NDIPOLEM,NRM),SE(NSM,NBFM,NEM),
     '  XA(NAM,NJM,NEM),XE(NSM,NJM),
     '  XP(NKM,NVM,NJM,NPM),YP(NYM,NIYM),YQ(NYQM,NIQM,NAM)
      CHARACTER ERROR*(*)
CC AJPs 23/10/97
      LOGICAL ACTIVATION
CC AJPe
!     Local Variables

      CALL ENTERS('IPANAL',*9999)

CC AJPs 23/10/97 191297
      IF (ACTIVATION) THEN
        CALL IPACTV(NPNODE,nr,nx,NYNP,XP,YP,YQ,ERROR,*9999)
      ELSE IF(ITYP1(nr,nx).EQ.3) THEN
CC AJPe
        CALL IPANA3(DIPOLE_CEN_NTIME,DIPOLE_DIR_NTIME,IBT,IDO,INP,NBJ,
     '    NDIPOLES,NEELEM,NENP,NKJE,NKH(1,1,1,nr),NPF,
     '    NP_INTERFACE,NPNE,NPNODE,nr,NRE,NVHP,NVJE,nx,NYNP,CE,
     '    DIPOLE_CEN,DIPOLE_DIR,SE,
     '    XA,XE,XP,YP,ERROR,*9999)
      ELSE IF(ITYP1(nr,nx).EQ.4) THEN
        ERROR='>>Not implemented'
        GOTO 9999
C        CALL IPANA4(nr,nx,ERROR,*9999)
      ELSE IF(ITYP1(nr,nx).EQ.5) THEN
        ERROR='>>Not implemented'
        GOTO 9999
C        CALL IPANA5(ERROR,*9999)
      ELSE IF(ITYP1(nr,nx).EQ.9) THEN
        CALL IPANA9(DIPOLE_CEN_NTIME,DIPOLE_DIR_NTIME,IBT,IDO,INP,NBJ,
     '    NDIPOLES,NEELEM,NENP,NKJE,NKH,NPF,
     '    NP_INTERFACE,NPNE,NPNODE,nr,NRE,NVJE,nx,NYNP,CE,DIPOLE_CEN,
     '    DIPOLE_DIR,SE,XA,XE,XP,YP,ERROR,*9999)
      ELSE
        ERROR='>>Not implemented'
        GOTO 9999
      ENDIF

      CALL EXITS('IPANAL')
      RETURN
 9999 CALL ERRORS('IPANAL',ERROR)
      CALL EXITS('IPANAL')
      RETURN 1
      END


