      SUBROUTINE IPWIND(ERROR,*)

C#### Subroutine: IPWIND
C###  Description:
C###    IPWIND inputs transformation parameters for Phigs 3D window.

      IMPLICIT NONE
      INCLUDE 'b00.cmn'
      INCLUDE 'b01.cmn'
      INCLUDE 'geom00.cmn'
      INCLUDE 'graf00.cmn'
      INCLUDE 'inout00.cmn'
!     Parameter List
      CHARACTER ERROR*(*)
!     Local Variables
      INTEGER ICHAR,INFO,NOQUES
      LOGICAL FILEIP

      CALL ENTERS('IPWIND',*9999)
      FILEIP=.FALSE.
      NOQUES=0
      INFO=2
      ICHAR=999

      RDEFLT(1)=0.0D0
      FORMAT='($,'' Enter minimum X [0.0]: '',E12.4)'
      IF(IOTYPE.EQ.3) RDATA(1)=DBLE(XMIN)
      CALL GINOUT(IOTYPE,IPREAL,IVDU,IFILE,0,0,NOQUES,FILEIP,FORMAT,1,
     '  ADATA,ADEFLT,CDATA,CDEFLT,ICHAR,IDATA,IDEFLT,0,IMAX,
     '  LDATA,LDEFLT,RDATA,RDEFLT,-RMAX,RMAX,INFO,ERROR,*9999)
      IF(IOTYPE.NE.3) XMIN=REAL(RDATA(1))

      RDEFLT(1)=1.0D0
      FORMAT='($,'' Enter maximum X [1.0]: '',E12.4)'
      IF(IOTYPE.EQ.3) RDATA(1)=DBLE(XMAX)
      CALL GINOUT(IOTYPE,IPREAL,IVDU,IFILE,0,0,NOQUES,FILEIP,FORMAT,1,
     '  ADATA,ADEFLT,CDATA,CDEFLT,ICHAR,IDATA,IDEFLT,0,IMAX,
     '  LDATA,LDEFLT,RDATA,RDEFLT,-RMAX,RMAX,INFO,ERROR,*9999)
      IF(IOTYPE.NE.3) XMAX=REAL(RDATA(1))

      RDEFLT(1)=0.0D0
      FORMAT='($,'' Enter minimum Y [0.0]: '',E12.4)'
      IF(IOTYPE.EQ.3) RDATA(1)=DBLE(YMIN)
      CALL GINOUT(IOTYPE,IPREAL,IVDU,IFILE,0,0,NOQUES,FILEIP,FORMAT,1,
     '  ADATA,ADEFLT,CDATA,CDEFLT,ICHAR,IDATA,IDEFLT,0,IMAX,
     '  LDATA,LDEFLT,RDATA,RDEFLT,-RMAX,RMAX,INFO,ERROR,*9999)
      IF(IOTYPE.NE.3) YMIN=REAL(RDATA(1))

      RDEFLT(1)=1.0D0
      FORMAT='($,'' Enter maximum Y [1.0]: '',E12.4)'
      IF(IOTYPE.EQ.3) RDATA(1)=DBLE(YMAX)
      CALL GINOUT(IOTYPE,IPREAL,IVDU,IFILE,0,0,NOQUES,FILEIP,FORMAT,1,
     '  ADATA,ADEFLT,CDATA,CDEFLT,ICHAR,IDATA,IDEFLT,0,IMAX,
     '  LDATA,LDEFLT,RDATA,RDEFLT,-RMAX,RMAX,INFO,ERROR,*9999)
      IF(IOTYPE.NE.3) YMAX=REAL(RDATA(1))

      DIAG=SQRT((XMAX-XMIN)**2+(YMAX-YMIN)**2)

      IF(NJT.EQ.3) THEN
        RDEFLT(1)=0.0D0
        FORMAT='($,'' Enter minimum Z [0.0]: '',E12.4)'
        IF(IOTYPE.EQ.3) RDATA(1)=DBLE(ZMIN)
        CALL GINOUT(IOTYPE,IPREAL,IVDU,IFILE,0,0,NOQUES,FILEIP,FORMAT,1,
     '    ADATA,ADEFLT,CDATA,CDEFLT,ICHAR,IDATA,IDEFLT,0,IMAX,
     '    LDATA,LDEFLT,RDATA,RDEFLT,-RMAX,RMAX,INFO,ERROR,*9999)
        IF(IOTYPE.NE.3) ZMIN=REAL(RDATA(1))

        RDEFLT(1)=1.0D0
        FORMAT='($,'' Enter maximum Z [1.0]: '',E12.4)'
        IF(IOTYPE.EQ.3) RDATA(1)=DBLE(ZMAX)
        CALL GINOUT(IOTYPE,IPREAL,IVDU,IFILE,0,0,NOQUES,FILEIP,FORMAT,1,
     '    ADATA,ADEFLT,CDATA,CDEFLT,ICHAR,IDATA,IDEFLT,0,IMAX,
     '    LDATA,LDEFLT,RDATA,RDEFLT,-RMAX,RMAX,INFO,ERROR,*9999)
        IF(IOTYPE.NE.3) ZMAX=REAL(RDATA(1))
        DIAG=SQRT((XMAX-XMIN)**2+(YMAX-YMIN)**2+(ZMAX-ZMIN)**2)
      ENDIF

      RDEFLT(1)=49.0D0
      FORMAT='($,'' Enter screen %width (max 82)[49.0]: '',E12.4)'
      IF(IOTYPE.EQ.3) RDATA(1)=DBLE(SCREEN_WIDTH)
      CALL GINOUT(IOTYPE,IPREAL,IVDU,IFILE,0,0,NOQUES,FILEIP,FORMAT,1,
     '  ADATA,ADEFLT,CDATA,CDEFLT,ICHAR,IDATA,IDEFLT,0,IMAX,
     '  LDATA,LDEFLT,RDATA,RDEFLT,0.0D0,82.0D0,INFO,ERROR,*9999)
      IF(IOTYPE.NE.3) SCREEN_WIDTH=REAL(RDATA(1))

      CALL EXITS('IPWIND')
      RETURN
 9999 CALL ERRORS('IPWIND',ERROR)
      CALL EXITS('IPWIND')
      RETURN 1
      END


