      SUBROUTINE ADD_FIELD_COMPONENT(FIELD_LABEL,COMPONENT_LABEL,
     &  ERROR,*)

C#### Subroutine: ADD_FIELD_COMPONENT
C###  Description:
C###    Adds a new field component.

      IMPLICIT NONE
      INCLUDE 'field00.cmn'

!     Parameter List
      CHARACTER FIELD_LABEL*(*),COMPONENT_LABEL*(*),ERROR*(*)
!     Local Variables
      INTEGER FIELD_INDEX

      CALL ENTERS('ADD_FIELD_COMPONENT',*9999)

      CALL GET_FIELD_INDEX(FIELD_LABEL,FIELD_INDEX,ERROR,*9999)
      
      CALL SET_LABEL_IN_ARRAY(
     &  FIELD_COMPONENT_LABELS_ARRAY,
     &  FIELD_COMPONENT_TOTAL_ARRAY,
     &  FIELD_COMPONENT_ALLOC_ARRAY,
     &  FIELD_COMPONENT_ARRAY_SIZE,
     &  FIELD_INDEX,FIELD_COMPONENT_LABELS_LEN,COMPONENT_LABEL,
     &  ERROR,*9999)

      CALL EXITS('ADD_FIELD_COMPONENT')
      RETURN
 9999 CALL ERRORS('ADD_FIELD_COMPONENT',ERROR)
      CALL EXITS('ADD_FIELD_COMPONENT')
      RETURN 1
      END


