      BLOCK DATA FIELD00

      IMPLICIT NONE
      INCLUDE 'field00.cmn'

! Field Labels
      DATA FIELD_LABELS_PTR/0/
      DATA ALLOCATED_FIELD_LABELS/0/
      DATA TOTAL_FIELD_LABELS/0/

! Field number
      DATA FIELD_NJ_PTR/0/
      DATA ALLOCATED_FIELD_NJ/0/

! Field Components
      DATA FIELD_COMPONENT_LABELS_ARRAY/0/
      DATA FIELD_COMPONENT_TOTAL_ARRAY/0/
      DATA FIELD_COMPONENT_ALLOC_ARRAY/0/
      DATA FIELD_COMPONENT_ARRAY_SIZE/0/

! Field component nu index
      DATA FIELD_COMPONENT_NU_ARRAY/0/
      DATA FIELD_COMPONENT_NU_ALLOC_ARRAY/0/
      DATA FIELD_COMPONENT_NU_ARRAY_SIZE/0/

      END



