      SUBROUTINE GET_FIELD_INDEX(FIELD_LABEL,FIELD_INDEX,ERROR,*)

C#### Subroutine: GET_FIELD_INDEX
C###  Description:
C###    Returns an index given a field label.

      IMPLICIT NONE
      INCLUDE 'field00.cmn'

!     Parameter List
      INTEGER FIELD_INDEX
      CHARACTER FIELD_LABEL*(*),ERROR*(*)
      

      CALL ENTERS('GET_FIELD_INDEX',*9999)

      CALL GET_INDEX(FIELD_LABELS_PTR,
     &  TOTAL_FIELD_LABELS,ALLOCATED_FIELD_LABELS,
     &  FIELD_LABELS_LEN,FIELD_LABEL,FIELD_INDEX,ERROR,*9999)

      CALL EXITS('GET_FIELD_INDEX')
      RETURN
 9999 CALL ERRORS('GET_FIELD_INDEX',ERROR)
      CALL EXITS('GET_FIELD_INDEX')
      RETURN 1
      END


