      SUBROUTINE GET_FIELD_COMPONENT_TOTAL(FIELD_LABEL,
     &  TOTAL_FIELD_COMPONENT,ERROR,*)

C#### Subroutine: GET_FIELD_COMPONENT_TOTAL
C###  Description:
C###    Gets the total number of field components.

      IMPLICIT NONE
      INCLUDE 'field00.cmn'

!     COMPONENTeter List
      INTEGER TOTAL_FIELD_COMPONENT,FIELD_INDEX
      CHARACTER FIELD_LABEL*(FIELD_LABELS_LEN),ERROR*(*)

      CALL ENTERS('GET_FIELD_COMPONENT_TOTAL',*9999)
      
      CALL GET_FIELD_INDEX(FIELD_LABEL,FIELD_INDEX,ERROR,*9999)
      
      CALL GET_TOTAL_IN_ARRAY(
     &  %VAL(FIELD_COMPONENT_TOTAL_ARRAY),
     &  FIELD_COMPONENT_ARRAY_SIZE,
     &  FIELD_INDEX,TOTAL_FIELD_COMPONENT,ERROR,*9999)

      CALL EXITS('GET_FIELD_COMPONENT_TOTAL')
      RETURN
 9999 CALL ERRORS('GET_FIELD_COMPONENT_TOTAL',ERROR)
      CALL EXITS('GET_FIELD_COMPONENT_TOTAL')
      RETURN 1
      END


