      SUBROUTINE GET_FIELD_COMPONENT_LABEL(FIELD_LABEL,
     &  COMPONENT_INDEX,COMPONENT_LABEL,ERROR,*)

C#### Subroutine: GET_FIELD_COMPONENT_LABEL
C###  Description:
C###    Gets a field component label given an index.

      IMPLICIT NONE
      INCLUDE 'field00.cmn'

!     Parameter List
      INTEGER FIELD_INDEX,COMPONENT_INDEX
      CHARACTER FIELD_LABEL*(*),COMPONENT_LABEL*(*),ERROR*(*)

      CALL ENTERS('GET_FIELD_COMPONENT_LABEL',*9999)

      CALL GET_FIELD_INDEX(FIELD_LABEL,FIELD_INDEX,ERROR,*9999)

      CALL GET_LABEL_IN_ARRAY(FIELD_COMPONENT_LABELS_ARRAY,
     &  FIELD_COMPONENT_ALLOC_ARRAY,FIELD_COMPONENT_ARRAY_SIZE,
     &  FIELD_INDEX,COMPONENT_INDEX,FIELD_COMPONENT_LABELS_LEN,
     &  COMPONENT_LABEL,ERROR,*9999)

      CALL EXITS('GET_FIELD_COMPONENT_LABEL')
      RETURN
 9999 CALL ERRORS('GET_FIELD_COMPONENT_LABEL',ERROR)
      CALL EXITS('GET_FIELD_COMPONENT_LABEL')
      RETURN 1
      END


