      SUBROUTINE GET_FIELD_LABEL(FIELD_INDEX,FIELD_LABEL,ERROR,*)

C#### Subroutine: GET_FIELD_LABEL
C###  Description: GET_FIELD_LABEL
C###     Returns the field label given an index.

      IMPLICIT NONE
      INCLUDE 'field00.cmn'

!     Parameter List
      INTEGER FIELD_INDEX
      CHARACTER FIELD_LABEL*(*),ERROR*(*)

      CALL ENTERS('GET_FIELD_LABEL',*9999)

      CALL GET_LABEL(FIELD_LABELS_PTR,ALLOCATED_FIELD_LABELS,
     &  FIELD_INDEX,FIELD_LABELS_LEN,FIELD_LABEL,ERROR,*9999)

      CALL EXITS('GET_FIELD_LABEL')
      RETURN
 9999 CALL ERRORS('GET_FIELD_LABEL',ERROR)
      CALL EXITS('GET_FIELD_LABEL')
      RETURN 1
      END


