      SUBROUTINE GET_FIELD_COMPONENT_INDEX(FIELD_LABEL,COMPONENT_LABEL,
     &  COMPONENT_INDEX,ERROR,*)

C#### Subroutine: GET_FIELD_COMPONENT_INDEX
C###  Description:
C###    Returns the index of a field component.

      IMPLICIT NONE
      INCLUDE 'field00.cmn'

!     Parameter List
      INTEGER FIELD_INDEX,COMPONENT_INDEX
      CHARACTER FIELD_LABEL*(*),COMPONENT_LABEL*(*),ERROR*(*)
      

      CALL ENTERS('GET_FIELD_COMPONENT_INDEX',*9999)
      
      CALL GET_FIELD_INDEX(FIELD_LABEL,FIELD_INDEX,ERROR,*9999)

      CALL GET_INDEX_IN_ARRAY(FIELD_COMPONENT_LABELS_ARRAY,
     &  FIELD_COMPONENT_TOTAL_ARRAY,
     &  FIELD_COMPONENT_ALLOC_ARRAY,
     &  FIELD_COMPONENT_ARRAY_SIZE,FIELD_INDEX,
     &  FIELD_COMPONENT_LABELS_LEN,
     &  COMPONENT_LABEL,COMPONENT_INDEX,ERROR,*9999)

      CALL EXITS('GET_FIELD_COMPONENT_INDEX')
      RETURN
 9999 CALL ERRORS('GET_FIELD_COMPONENT_INDEX',ERROR)
      CALL EXITS('GET_FIELD_COMPONENT_INDEX')
      RETURN 1
      END


