      SUBROUTINE PRINT_FIELDS(ERROR,*)

C#### Subroutine: PRINT_FIELDS
C###  Description:
C###    Prints the fields and it's components.

      IMPLICIT NONE
      INCLUDE 'cbdi02.cmn'
      INCLUDE 'colours00.cmn'
      INCLUDE 'field00.cmn'

!     Parameter List
      CHARACTER ERROR*(*)

!     Local Variables
      INTEGER CINDEX,CTOTAL,PINDEX,PTOTAL,IB1,IE1
      CHARACTER CLABEL*(FIELD_COMPONENT_LABELS_LEN),
     &  PLABEL*(FIELD_LABELS_LEN)

      CALL ENTERS('PRINT_FIELDS',*9999)
          
      CALL GET_FIELD_TOTAL(PTOTAL,ERROR,*9999)
      
      DO PINDEX=1,PTOTAL
        CALL GET_FIELD_LABEL(PINDEX,PLABEL,ERROR,*9999)
        
        CALL STRING_TRIM(PLABEL,IB1,IE1)
        WRITE(OP_STRING,'(''FIELD: '//COLOUR_PARENT//PLABEL(IB1:IE1)
     &    //COLOUR_DEFAULT//''')')
        CALL WRITES(IOFI,OP_STRING,ERROR,*9999)
        WRITE(OP_STRING,'(4X,''Components:'')')
        CALL WRITES(IOFI,OP_STRING,ERROR,*9999)
        
        CALL GET_FIELD_COMPONENT_TOTAL(PLABEL,CTOTAL,ERROR,*9999)
        
        DO CINDEX=1,CTOTAL
          CALL GET_FIELD_COMPONENT_LABEL(PLABEL,CINDEX,CLABEL,
     &      ERROR,*9999)
          CALL STRING_TRIM(CLABEL,IB1,IE1)
          WRITE(OP_STRING,'(7X,'''//COLOUR_CHILD//CLABEL(IB1:IE1)
     &      //COLOUR_DEFAULT//''')')
          CALL WRITES(IOFI,OP_STRING,ERROR,*9999)
        ENDDO
        WRITE(OP_STRING,'()')
        CALL WRITES(IOFI,OP_STRING,ERROR,*9999)
      ENDDO 

      CALL EXITS('PRINT_FIELDS')
      RETURN
 9999 CALL ERRORS('PRINT_FIELDS',ERROR)
      CALL EXITS('PRINT_FIELDS')
      RETURN 1
      END


