      SUBROUTINE SET_FIELD_COMPONENT_NU(FIELD_LABEL,
     &  COMPONENT_LABEL,NU,ERROR,*)

C#### Subroutine: SET_FIELD_COMPONENT_NU
C###  Description:
C###    Sets the nu index for a field component.

      IMPLICIT NONE
      INCLUDE 'field00.cmn'

!     Parameter List
      INTEGER NU
      CHARACTER FIELD_LABEL*(*),COMPONENT_LABEL*(*),ERROR*(*)
!     Local Variables
      INTEGER FIELD_INDEX,COMPONENT_INDEX

      CALL ENTERS('SET_FIELD_COMPONENT_NU',*9999)

      CALL GET_FIELD_INDEX(FIELD_LABEL,FIELD_INDEX,ERROR,*9999)
      CALL GET_FIELD_COMPONENT_INDEX(FIELD_LABEL,COMPONENT_LABEL,
     &  COMPONENT_INDEX,ERROR,*9999)
      
      CALL SET_INTEGER_IN_ARRAY(
     &  FIELD_COMPONENT_NU_ARRAY,
     &  FIELD_COMPONENT_NU_ALLOC_ARRAY,
     &  FIELD_COMPONENT_NU_ARRAY_SIZE,
     &  FIELD_INDEX,COMPONENT_INDEX,NU,
     &  ERROR,*9999)

      CALL EXITS('SET_FIELD_COMPONENT_NU')
      RETURN
 9999 CALL ERRORS('SET_FIELD_COMPONENT_NU',ERROR)
      CALL EXITS('SET_FIELD_COMPONENT_NU')
      RETURN 1
      END


