      SUBROUTINE SET_FIELD_NJ(FIELD_LABEL,FIELD_NJ,ERROR,*)

C#### Subroutine: SET_FIELD_NJ
C###  Description:
C###    Sets the nj index of the field.

      IMPLICIT NONE
      INCLUDE 'field00.cmn'

!     Parameter List
      INTEGER FIELD_INDEX,FIELD_NJ
      CHARACTER FIELD_LABEL*(*),ERROR*(*)

      CALL ENTERS('SET_FIELD_NJ',*9999)

      CALL GET_FIELD_INDEX(FIELD_LABEL,FIELD_INDEX,ERROR,*9999)

      CALL SET_INTEGER(FIELD_NJ_PTR,ALLOCATED_FIELD_NJ,
     &  FIELD_INDEX,FIELD_NJ,ERROR,*9999)

      CALL EXITS('SET_FIELD_NJ')
      RETURN
 9999 CALL ERRORS('SET_FIELD_NJ',ERROR)
      CALL EXITS('SET_FIELD_NJ')
      RETURN 1
      END


