      SUBROUTINE SETUP_FIELD(FIELD_LABEL,NJ,ERROR,*)

C#### Subroutine: SETUP_FIELD
C###  Description:
C###    This routine sets up a field and it's components.

      IMPLICIT NONE
      INCLUDE 'geom00.cmn'
      INCLUDE 'field00.cmn'
      INCLUDE 'loc00.cmn'
      INCLUDE 'loc00.inc'

!     Parameter List
      INTEGER nj
      CHARACTER FIELD_LABEL*(*),ERROR*(*)
      
!     Local Variables
      CHARACTER COMPONENT_LABEL*(FIELD_COMPONENT_LABELS_LEN)
      
      CALL ENTERS('SETUP_FIELD',*9999)
      
      CALL ADD_FIELD(FIELD_LABEL,ERROR,*9999)
      CALL SET_FIELD_NJ(FIELD_LABEL,nj,ERROR,*9999)
      
      IF(NJT.GE.1)THEN
        
        COMPONENT_LABEL='value'
        CALL ADD_FIELD_COMPONENT(FIELD_LABEL,COMPONENT_LABEL,
     &    ERROR,*9999)
        CALL SET_FIELD_COMPONENT_NU(FIELD_LABEL,COMPONENT_LABEL,
     &    1,ERROR,*9999)

        COMPONENT_LABEL='derivative_dxi1'
        CALL ADD_FIELD_COMPONENT(FIELD_LABEL,COMPONENT_LABEL,
     &    ERROR,*9999)
        CALL SET_FIELD_COMPONENT_NU(FIELD_LABEL,COMPONENT_LABEL,
     &    2,ERROR,*9999)

        COMPONENT_LABEL='derivative_dxi1dxi1'
        CALL ADD_FIELD_COMPONENT(FIELD_LABEL,COMPONENT_LABEL,
     &    ERROR,*9999)
        CALL SET_FIELD_COMPONENT_NU(FIELD_LABEL,COMPONENT_LABEL,
     &    3,ERROR,*9999)

      ENDIF
      
      IF(NJT.GE.2)THEN
        
        COMPONENT_LABEL='derivative_dxi2'
        CALL ADD_FIELD_COMPONENT(FIELD_LABEL,COMPONENT_LABEL,
     &    ERROR,*9999)
        CALL SET_FIELD_COMPONENT_NU(FIELD_LABEL,COMPONENT_LABEL,
     &    4,ERROR,*9999)

        COMPONENT_LABEL='derivative_dxi2dxi2'
        CALL ADD_FIELD_COMPONENT(FIELD_LABEL,COMPONENT_LABEL,
     &    ERROR,*9999)
        CALL SET_FIELD_COMPONENT_NU(FIELD_LABEL,COMPONENT_LABEL,
     &    5,ERROR,*9999)

        COMPONENT_LABEL='derivative_dxi1dxi2'
        CALL ADD_FIELD_COMPONENT(FIELD_LABEL,COMPONENT_LABEL,
     &    ERROR,*9999)
        CALL SET_FIELD_COMPONENT_NU(FIELD_LABEL,COMPONENT_LABEL,
     &    6,ERROR,*9999)

      ENDIF
      
      IF(NJT.GE.3)THEN
        
        COMPONENT_LABEL='derivative_dxi3'
        CALL ADD_FIELD_COMPONENT(FIELD_LABEL,COMPONENT_LABEL,
     &    ERROR,*9999)
        CALL SET_FIELD_COMPONENT_NU(FIELD_LABEL,COMPONENT_LABEL,
     &    7,ERROR,*9999)

        COMPONENT_LABEL='derivative_dxi3dxi3'
        CALL ADD_FIELD_COMPONENT(FIELD_LABEL,COMPONENT_LABEL,
     &    ERROR,*9999)
        CALL SET_FIELD_COMPONENT_NU(FIELD_LABEL,COMPONENT_LABEL,
     &    8,ERROR,*9999)

        COMPONENT_LABEL='derivative_dxi1dxi3'
        CALL ADD_FIELD_COMPONENT(FIELD_LABEL,COMPONENT_LABEL,
     &    ERROR,*9999)
        CALL SET_FIELD_COMPONENT_NU(FIELD_LABEL,COMPONENT_LABEL,
     &    9,ERROR,*9999)

        COMPONENT_LABEL='derivative_dxi2dxi3'
        CALL ADD_FIELD_COMPONENT(FIELD_LABEL,COMPONENT_LABEL,
     &    ERROR,*9999)
        CALL SET_FIELD_COMPONENT_NU(FIELD_LABEL,COMPONENT_LABEL,
     &    10,ERROR,*9999)

        COMPONENT_LABEL='derivative_dxi1dxi2dxi3'
        CALL ADD_FIELD_COMPONENT(FIELD_LABEL,COMPONENT_LABEL,
     &    ERROR,*9999)
        CALL SET_FIELD_COMPONENT_NU(FIELD_LABEL,COMPONENT_LABEL,
     &    11,ERROR,*9999)

      ENDIF
      
      CALL EXITS('SETUP_FIELD')
      RETURN
 9999 CALL ERRORS('SETUP_FIELD',ERROR)
      CALL EXITS('SETUP_FIELD')
      RETURN 1
      END
