#!/bin/sh

UNAME=`uname`

case $UNAME in
  #
  # Linux
  #
  "Linux")
    BLURB="Building for a Linux platform"
    LIST=""
    ;;

  #
  # IBM/AIX
  #
  "AIX")
    BLURB="Building for an IBM AIX Platform"
    LIST="ABI=32,MP= ABI=32,OPT=,MP= ABI=64,MP= ABI=64,OPT=,MP="
    ;;

  #
  # SGI/IRIX 32 bit
  #
  "IRIX")
    BLURB="Building for an IRIX box"
    LIST="ABI=n32,MP= ABI=n32,OPT=,MP="
    ;;

  #
  # SGI/IRIX 64 bit
  #
  "IRIX64")
    BLURB="Building for an IRIX 64 box"
    LIST="ABI=n32,MP= ABI=n32,OPT=,MP= ABI=64,MP= ABI=64,OPT=,MP="
    ;;

  #
  # Unknown
  #
  *)
    echo "Unknown platform"
    exit -1
    ;;
esac

echo $BLURB

gmake clean
for OPTION in $LIST
do
  SWITCH=`echo $OPTION | sed 's/,/ /g'`

  gmake $SWITCH lib
  gmake $SWITCH clean
done
