      SUBROUTINE OPOUTP(IBT,IDO,INP,LGE,NAN,NBH,NBHF,NBJ,NBJF,NEELEM,
     &  NELIST,NENP,NFF,NFFACE,NGAP,NHE,NHP,NKB,NKEF,NKH,NKHE,NKJE,NLL,
     &  NNB,NNF,NP_INTERFACE,NPF,NPNE,NPNODE,NPNY,nr,NRE,NSB,NVHE,NVHP,
     &  NVJE,NVJP,NW,nx,NXI,NYNE,NYNP,NYNR,Z_CONT_LIST,
     '  CE,CG,CGE,CP,CURVCORRECT,DET,DL,DRDN,FEXT,PG,RAD,
     '  RD,RE1,RG,SE,WG,XA,XE,XG,XG1,XIG,XN,XP,XR,
     '  YD,YG,YGF,YP,ZA,ZA1,Z_CONT,ZE,ZE1,ZF,ZG,ZP,ZP1,
     '  FIX,ERROR,*)

C#### Subroutine: OPOUTP
C###  Description:
C###    OPOUTP outputs output.

      IMPLICIT NONE
      INCLUDE 'geom00.cmn'
      INCLUDE 'ityp00.cmn'
      INCLUDE 'loc00.cmn'
      INCLUDE 'loc00.inc'
!     Parameter List
      INTEGER IBT(3,NIM,NBFM),IDO(NKM,NNM,0:NIM,NBFM),INP(NNM,NIM,NBFM),
     '  LGE(NHM*NSM),NAN(NIM,NAM,NBFM),NBH(NHM,NCM,NEM),
     '  NBHF(NHM,NCM,NFM),NBJ(NJM,NEM),NBJF(NJM,NFM),
     '  NEELEM(0:NE_R_M,0:NRM),NELIST(0:NEM),NENP(NPM,0:NEPM),
     &  NFF(6,NEM),NFFACE(0:NF_R_M,NRM),NGAP(NIM,NBM),NHE(NEM),NHP(NPM),
     &  NKB(2,2,2,NNM,NBFM),NKEF(0:4,16,6,NBFM),NKH(NHM,NPM,NCM),
     '  NKHE(NKM,NNM,NHM,NEM),NKJE(NKM,NNM,NJM,NEM),NLL(12,NEM),
     '  NNB(4,4,4,NBFM),NNF(0:17,6,NBFM),
     '  NP_INTERFACE(0:NPM,0:3),NPF(9,NFM),NPNE(NNM,NBFM,NEM),
     '  NPNODE(0:NP_R_M,0:NRM),NPNY(0:6,NYM,0:NRCM),nr,NRE(NEM),
     '  NSB(NKM,NNM,NBFM),NVHE(NNM,NBFM,NHM,NEM),NVHP(NHM,NPM,NCM),
     '  NVJE(NNM,NBFM,NJM,NEM),NVJP(NJM,NPM),NW(NEM,3),nx,
     '  NXI(-NIM:NIM,0:NEIM,0:NEM),NYNE(NAM,NHM,0:NRCM,NCM,NEM),
     '  NYNP(NKM,NVM,NHM,NPM,0:NRCM,NCM,NRM),NYNR(0:NY_R_M,0:NRCM,NCM),
     '  Z_CONT_LIST(NDM,2,7)
      REAL*8 CE(NMM,NEM),CG(NMM,NGM),CGE(NMM,NGM,NEM),
     '  CP(NMM,NPM),
     '  CURVCORRECT(2,2,NNM,NEM),DET(NBFM,0:NNM,NGM,6),
     '  DL(3,NLM),DRDN(NGM),FEXT(NIFEXTM,NGM,NEM),
     '  PG(NSM,NUM,NGM,NBM),RAD(NGM),RD(NGM),RE1(NSM,NHM),
     '  RG(NGM),SE(NSM,NBFM,NEM),WG(NGM,NBM),
     '  XA(NAM,NJM,NEM),XE(NSM,NJM),XG(NJM,NUM),XG1(NJM,NUM,NGM),
     '  XIG(NIM,NGM,NBM),XN(NJM,NGM),XP(NKM,NVM,NJM,NPM),XR(NJM,NGM),
     '  YD(NHM),
     '  YG(NIYGM,NGM,NEM),YGF(NIYGFM,NGFM,NFM),YP(NYM,NIYM),
     '  ZA(NAM,NHM,NCM,NEM),ZA1(NAM,NHM,NCM,NEM),Z_CONT(NDM,2,67),
     '  ZE(NSM,NHM),ZE1(NSM,NHM),ZF(NSM,NHM),ZG(NHM,NUM),
     '  ZP(NKM,NVM,NHM,NPM,NCM),ZP1(NKM,NVM,NHM,NPM,NCM)
      LOGICAL FIX(NYM,NIYFIXM)
      CHARACTER ERROR*(*)
!     Local Variables
      INTEGER nb,ne,noelem

      CALL ENTERS('OPOUTP',*9999)
      IF(ITYP6(nr,nx).EQ.2) THEN !nonlinear
        CALL ZPRP(IBT,IDO,INP,LGE,NAN,NBH,NBHF,NBJ,NBJF,NEELEM,NFF,
     '    NFFACE,NGAP,NHE,NHP,NKB,NKEF,NKH,NKHE,NKJE,NNB,NNF,NPF,
     '    NPNE,NPNODE,NPNY,nr,NRE,NSB,NVHE,NVHP,NVJP,NW,nx,NXI,NYNE,
     '    NYNP,NYNR,Z_CONT_LIST,CE,CG,CGE,CP,CURVCORRECT,
     '    FEXT,PG,RE1,
     '    RG,SE,WG,XA,XG,XP,YG,YGF,YP,ZA,ZA1,%VAL(0),
     '    Z_CONT,ZE,ZE1,ZP,ZP1,
     '    %VAL(0),FIX,ERROR,*9999)
        CALL ZPOP(4,NBH,1,NEELEM,NHP,NKH,NPNODE,nr,NVHP,nx,
     '    NYNE,NYNP,YP(1,4),ZA,ZP,FIX(4,1),ERROR,*9999)
      ENDIF
      IF(ITYP1(nr,nx).EQ.3) THEN      !pdes
        IF(ITYP2(nr,nx).EQ.11) THEN !pulmonary transport problems
          CALL OUTP_LUNG(NBJ,NELIST,NENP,NPNE,nr,nx,NYNE,
     &      NYNP(1,1,1,1,0,1,nr),CE,YP,ERROR,*9999)
        ELSE
          CALL OPC30(IBT,IDO,INP,NBH,NBJ,NEELEM,NHE,NHP,NKH,NKHE,NKJE,
     '      NPF,NPNE,NPNODE,nr,NRE,NVHE,NVHP,NVJE,NW,NYNE,NYNP,CE,CG,
     &      CGE,CP,CURVCORRECT,PG,RG,SE,WG,XA,XE,XG,XP,YP,ZA,ZE,ZG,ZP,
     &      ERROR,*9999)
        ENDIF
      ELSE IF(ITYP1(nr,nx).EQ.4) THEN !linear elasticity
        CALL OPC40(IBT,IDO,INP,NBH,NBJ,NEELEM,NHE,NHP,NKHE,NKH,
     '    NPF,NPNE,NPNODE,nr,NRE,NVHE,NVHP,NVJE,NW,nx,NYNE,NYNP,CE,CG,
     '    CGE,CP,PG,RG,SE,XA,XE,XG,XP,YP,ZA,ZE,ZP,ERROR,*9999)
      ELSE IF(ITYP1(nr,nx).EQ.5) THEN !finite elasticity
        DO noelem=1,NEELEM(0,nr)
          ne=NEELEM(noelem,nr)
          nb=NBH(NH_LOC(1,nx),1,ne)
          CALL XPXE(NBJ(1,ne),NKJE(1,1,1,ne),NPF(1,1),
     '      NPNE(1,1,ne),nr,NVJE(1,1,1,ne),
     '      SE(1,1,ne),XA(1,1,ne),XE,XP,ERROR,*9999)
          CALL ZPZE(NBH(1,1,ne),1,NHE(ne),NKHE(1,1,1,ne),NPF(1,1),
     '      NPNE(1,1,ne),nr,NVHE(1,1,1,ne),NW(ne,1),nx,
     '      CURVCORRECT(1,1,1,ne),SE(1,1,ne),ZA(1,1,1,ne),ZE,ZP,
     '      ERROR,*9999)
          CALL CPCG(1,NBH(1,1,ne),NPNE(1,1,ne),nr,nx,
     '      CE(1,ne),CG,CGE(1,1,ne),CP,PG,ERROR,*9999)
          CALL OPC50(IBT,IDO,INP,NAN,NBH(1,1,ne),NBJ(1,ne),ne,
     '      NHE(ne),NPNE(1,1,ne),nr,nx,
     '      CE(1,ne),CG,CP,FEXT(1,1,ne),PG,RG,
     '      XE,XG,XIG(1,1,nb),YG(1,1,ne),ZE,ZG,ERROR,*9999)
        ENDDO

      ELSE IF(ITYP1(nr,nx).EQ.9) THEN !boundary elements
!news AJP 12/4/95
        IF(ITYP5(nr,nx).EQ.1.AND.ITYP2(nr,nx).EQ.1) THEN
          !Static linear elasticity
          CALL OPC40(IBT,IDO,INP,NBH,NBJ,NEELEM,NHE,NHP,NKHE,NKH,
     '      NPF,NPNE,NPNODE,nr,NRE,NVHE,NVHP,NVJE,NW,nx,NYNE,NYNP,CE,
     '      CG,CGE,CP,PG,RG,SE,XA,XE,XG,XP,YP,ZA,ZE,ZP,ERROR,*9999)
        ELSE !rest of BEM
          CALL OPC90(IBT,NBH,NBJ,NEELEM,
     '      NHE,NHP,NKH,NKHE,NKJE,NLL,NP_INTERFACE,NPF,NPNE,NPNODE,
     '      nr,NRE,NVHE,NVHP,NVJE,NW,nx,NYNE,NYNP,
     '      CE,CURVCORRECT,DET,DL,DRDN,PG,RAD,RD,RG,SE,WG,XA,XE,
     '      XG,XG1,XN,XP,XR,YD,YP,ZA,ZE,ZF,ZG,ZP,ERROR,*9999)
        ENDIF
!newe
      ENDIF

      CALL EXITS('OPOUTP')
      RETURN
 9999 CALL ERRORS('OPOUTP',ERROR)
      CALL EXITS('OPOUTP')
      RETURN 1
      END


