      SUBROUTINE ALLOCATE_LATTICE(NLATNE_PTR,NLATNQ_PTR,NLATPNQ_PTR,
     &  NQNLAT_PTR,ERROR,*)

      IMPLICIT NONE

      INCLUDE 'cbfe01.cmn'
      INCLUDE 'geom00.cmn'
      INCLUDE 'grid00.cmn'
      INCLUDE 'mach00.inc'
!     Parameter List
      INTEGER*4 NLATNE_PTR,NLATNQ_PTR,NLATPNQ_PTR,NQNLAT_PTR
      CHARACTER ERROR*(*)

      CALL ENTERS('ALLOCATE_LATTICE',*9999)

      NLATNE_PTR=0
      CALL ALLOCATE_MEMORY((NEQM+1),0,INTTYPE,
     '  NLATNE_PTR,MEM_INIT,ERROR,*9999) 
      NLATNQ_PTR=0
      CALL ALLOCATE_MEMORY(NEQM*NQEM,0,INTTYPE,
     '  NLATNQ_PTR,MEM_INIT,ERROR,*9999)
      NLATPNQ_PTR=0
      CALL ALLOCATE_MEMORY(NQM,0,INTTYPE,
     '  NLATPNQ_PTR,MEM_INIT,ERROR,*9999)
      NQNLAT_PTR=0
      CALL ALLOCATE_MEMORY(NEQM*NQEM,0,INTTYPE,
     '  NQNLAT_PTR,MEM_INIT,ERROR,*9999)

      CALL EXITS('ALLOCATE_LATTICE')
      RETURN
 9999 CALL ERRORS('ALLOCATE_LATTICE',ERROR)
      CALL EXITS('ALLOCATE_LATTICE')
      RETURN 1
      END


