      SUBROUTINE FACCAL(IBT,IDO,INP,NBJ,NBJF,NEELEM,NFF,NFFACE,
     '  NKJE,NKEF,NLF,NNF,NNL,NPF,NPL,NPNE,NPNF,NRE,NVJE,
     '  NVJF,DF,PG,RG,SE,SF,WG,XA,XE,XG,XP,ERROR,*)

C#### Subroutine: FACCAL
C###  Description:
C###    FACCAL calculates the various parameters associated with
C###    global face segments nf=1,NFT by calling FACSEG and AREA.

      IMPLICIT NONE
      INCLUDE 'call00.cmn'
      INCLUDE 'geom00.cmn'
!     Parameter List
      INTEGER IBT(3,NIM,NBFM),IDO(NKM,NNM,0:NIM,NBFM),INP(NNM,NIM,NBFM),
     '  NBJ(NJM,NEM),NBJF(NJM,NFM),NEELEM(0:NE_R_M,0:NRM),NFF(6,NEM),
     '  NFFACE(0:NF_R_M,NRM),NKJE(NKM,NNM,NJM,NEM),
     '  NKEF(0:4,16,6,NBFM),NLF(4,NFM),
     '  NNF(0:17,6,NBFM),NNL(0:4,12,NBFM),NPF(9,NFM),NPL(5,0:3,NLM),
     '  NPNE(NNM,NBFM,NEM),NPNF(NNM,NBFM),NRE(NEM),
     '  NVJE(NNM,NBFM,NJM,NEM),NVJF(NNM,NBFM,NJM)
      REAL*8 DF(NFM),PG(NSM,NUM,NGM,NBM),RG(NGM),SE(NSM,NBFM,NEM),
     '  SF(NSM,NBFM),WG(NGM,NBM),
     '  XA(NAM,NJM,NEM),XE(NSM,NJM),XG(NJM,NUM),XP(NKM,NVM,NJM,NPM)
      CHARACTER ERROR*(*)
!     Local Variables
      INTEGER nb
      LOGICAL THREED

      CALL ENTERS('FACCAL',*9999)

      CALL FACSEG(IBT,IDO,INP,NBJ,NBJF,NEELEM,NFF,NFFACE,NKJE,NKEF,
     '  NLF,NNF,NNL,NPF,NPL,NPNE,NPNF,NRE,NVJE,NVJF,SE,SF,XP,
     '  ERROR,*9999)
      THREED=.FALSE.
      DO nb=1,NBFT
        IF(NIT(nb).EQ.3) THREED=.TRUE.
      ENDDO
      IF(THREED) THEN
        CALL AREA(NBJ,NBJF,NKJE,NKEF,NNF,NPF,NPNE,NPNF,NRE,
     '    NVJE,NVJF,DF,PG,RG,SE,SF,WG,XA,XE,XG,XP,ERROR,*9999)
      ENDIF
      CALL_FACE=.TRUE.

      CALL EXITS('FACCAL')
      RETURN
 9999 CALL ERRORS('FACCAL',ERROR)
      CALL EXITS('FACCAL')
      RETURN 1
      END



