! cell_br.inc

      INTEGER G,Cai,d,f1,GNa,GNaC,Gs,h,j,m,Vmrest,VNa,x1
      PARAMETER(m=2)         !Y,DY
      PARAMETER(h=3)         !Y,DY
      PARAMETER(j=4)         !Y,DY
      PARAMETER(d=5)         !Y,DY
      PARAMETER(f1=6)        !Y,DY
      PARAMETER(x1=7)        !Y,DY
      PARAMETER(Cai=8)       !Y,DY
      PARAMETER(G=9)         !Y,DY
      PARAMETER(Vmrest=3)    !PARAMETERS
      PARAMETER(VNa=4)       !PARAMETERS
      PARAMETER(GNa=5)       !PARAMETERS
      PARAMETER(GNaC=6)      !PARAMETERS
      PARAMETER(Gs=7)        !PARAMETERS
