! cell_fhn.inc

      INTEGER B,Cai,CaTime,C1,C2,D,Mu2,Recov,Vmplat,Vmrest,Vmthres
      PARAMETER(Recov=2)     !Y,DY
      PARAMETER(Cai=3)       !Y,DY
      PARAMETER(Vmrest=3)    !PARAMETERS
      PARAMETER(Vmplat=4)    !PARAMETERS
      PARAMETER(Vmthres=5)   !PARAMETERS
      PARAMETER(C1=6)        !PARAMETERS
      PARAMETER(C2=7)        !PARAMETERS
      PARAMETER(B=8)         !PARAMETERS
      PARAMETER(D=9)         !PARAMETERS
      PARAMETER(Mu2=10)      !PARAMETERS
      PARAMETER(CaTime=11)   !PARAMETERS
