#!/usr/bin/perl -w

use strict;

my $filename = shift;
my $perl;

open (PLFILE, "<$filename") || die "can't open $filename: $!\n";
while (defined ($perl = <PLFILE>))
  {
	 chomp $perl;

	 if ($perl !~m|\#|)
	 {
		if (($perl =~m%gfx%) || ($perl =~m%open\s+(commands|comfile|example|menu|url)%) || ($perl =~m%set%))
		{
		  $perl =~ s%\"%\\\\\\"%g;
		  $perl =~ s%gfx%cmiss::cmiss(\\"gfx%g;
		  $perl =~ s%open(\s+)(commands|comfile|example|menu|url)%cmiss::cmiss(\\"open$1$2%g;
		  $perl =~ s%set directory%cmiss::cmiss(\\"set directory%g;
		  $perl =~ s%;%%g;
		  print "\"$perl\\\");\"\n";

		} 
		else
		{
		  # Escape \ and "
		  $perl =~ s%\\%\\\\%g;
		  $perl =~ s%\"%\\\"%g;
		  print "\"$perl\"\n";
		}
	 }
  }
close PLFILE;
