      SUBROUTINE IPMESH8(IBT,IDO,INP,NBJ,NEELEM,NKJE,NKJ,NPF,
     '  NP_INTERFACE,NPNE,NPNODE,nr,NRE,NVJE,NVJP,NXI,SE,XA,XE,XP,
     '  ERROR,*)

C#### Subroutine: IPMESH8
C###  Description:
C###    defines mesh parameters for a Purkinje fibre tree.
C###    The tree is grown over an existing FE mesh.
C###    This routine dynamically allocates the local arrays
C###    for use in the subroutine IPMESH8_DYNAM.
C***  Martin Buist December 1996

      IMPLICIT NONE
      INCLUDE 'geom00.cmn'

!  Parameter list
      INTEGER IBT(3,NIM,NBFM),IDO(NKM,NNM,0:NIM,NBFM),
     '  INP(NNM,NIM,NBFM),NBJ(NJM,NEM),NEELEM(0:NE_R_M,0:NRM),
     '  NKJE(NKM,NNM,NJM,NEM),NKJ(NJM,NPM),
     '  NPF(9,NFM),NP_INTERFACE(0:NPM,0:3),NPNE(NNM,NBFM,NEM),
     '  NPNODE(0:NP_R_M,0:NRM),nr,NRE(NEM),
     '  NVJE(NNM,NBFM,NJM,NEM),NVJP(NJM,NPM),NXI(-NIM:NIM,0:NEIM,0:NEM)
      REAL*8 SE(NSM,NBFM,NEM),XA(NAM,NJM,NEM),XE(NSM,NJM),
     '  XP(NKM,NVM,NJM,NPM)
      CHARACTER ERROR*(*)
!  Local variables
      INTEGER BMAX,MAX_RAN_PTS,MAX_BRANCH,TMAX
      PARAMETER (BMAX=4)
      PARAMETER (MAX_RAN_PTS=100000)
      PARAMETER (MAX_BRANCH=256)
      PARAMETER (TMAX=8)
      INTEGER*4 AMAP_PTR,AREANUM_PTR,ELEMLIST_PTR,GEOMFRAC_PTR,
     '  POINTCOORD_PTR,POINTS_PTR,PTAR_PTR,PWEIGHT_PTR,RANDOM_COORD_PTR,
     '  START_PTR,STARTNODE_PTR,TCX_PTR,WEIGHTS_PTR,XJPOWER_PTR

      CALL ENTERS('IPMESH8',*9999)

C dynamically allocate local arrays
      AMAP_PTR=0
      AREANUM_PTR=0
      ELEMLIST_PTR=0
      GEOMFRAC_PTR=0
      POINTCOORD_PTR=0
      POINTS_PTR=0
      PTAR_PTR=0
      PWEIGHT_PTR=0
      RANDOM_COORD_PTR=0
      START_PTR=0
      STARTNODE_PTR=0
      TCX_PTR=0
      WEIGHTS_PTR=0
      XJPOWER_PTR=0

      CALL ALLOCATE_MEMORY(MAX_BRANCH,0,1,AMAP_PTR,.TRUE.,
     '  ERROR,*9999)
      CALL ALLOCATE_MEMORY(MAX_RAN_PTS,0,1,AREANUM_PTR,.TRUE.,
     '  ERROR,*9999)
      CALL ALLOCATE_MEMORY(4*MAX_BRANCH,0,1,ELEMLIST_PTR,.TRUE.,
     '  ERROR,*9999)
      CALL ALLOCATE_MEMORY(MAX_BRANCH*6,0,3,GEOMFRAC_PTR,.TRUE.,
     '  ERROR,*9999)
      CALL ALLOCATE_MEMORY(MAX_BRANCH*3,0,3,POINTCOORD_PTR,.TRUE.,
     '  ERROR,*9999)
      CALL ALLOCATE_MEMORY(MAX_BRANCH,0,5,POINTS_PTR,.TRUE.,
     '  ERROR,*9999)
      CALL ALLOCATE_MEMORY(MAX_BRANCH,0,1,PTAR_PTR,.TRUE.,
     '  ERROR,*9999)
      CALL ALLOCATE_MEMORY(MAX_RAN_PTS,0,3,PWEIGHT_PTR,.TRUE.,
     '  ERROR,*9999)
      CALL ALLOCATE_MEMORY(MAX_RAN_PTS*NJT,0,3,RANDOM_COORD_PTR,.TRUE.,
     '  ERROR,*9999)
      CALL ALLOCATE_MEMORY(TMAX*3,0,3,START_PTR,.TRUE.,
     '  ERROR,*9999)
      CALL ALLOCATE_MEMORY(2*TMAX,0,1,STARTNODE_PTR,.TRUE.,
     '  ERROR,*9999)
      CALL ALLOCATE_MEMORY(2*(NP_R_M+1)*(BMAX+1),0,1,TCX_PTR,.TRUE.,
     '  ERROR,*9999)
      CALL ALLOCATE_MEMORY(MAX_BRANCH,0,3,WEIGHTS_PTR,.TRUE.,
     '  ERROR,*9999)
      CALL ALLOCATE_MEMORY(MAX_BRANCH*3,0,3,XJPOWER_PTR,.TRUE.,
     '  ERROR,*9999)

      CALL IPMESH8_DYNAM(%VAL(AMAP_PTR),%VAL(AREANUM_PTR),BMAX,
     '  %VAL(ELEMLIST_PTR),%VAL(GEOMFRAC_PTR),IBT,IDO,INP,MAX_BRANCH,
     '  MAX_RAN_PTS,NBJ,NEELEM,NKJE,NKJ,NPF,NP_INTERFACE,
     '  NPNE,NPNODE,nr,NRE,NVJE,NVJP,NXI,%VAL(POINTS_PTR),
     '  %VAL(POINTCOORD_PTR),%VAL(PTAR_PTR),%VAL(PWEIGHT_PTR),
     '  %VAL(RANDOM_COORD_PTR),SE,%VAL(START_PTR),%VAL(STARTNODE_PTR),
     '  %VAL(TCX_PTR),TMAX,%VAL(WEIGHTS_PTR),XA,XE,%VAL(XJPOWER_PTR),
     '  XP,ERROR,*9999)

      CALL FREE_MEMORY(AMAP_PTR,ERROR,*9999)
      CALL FREE_MEMORY(AREANUM_PTR,ERROR,*9999)
      CALL FREE_MEMORY(ELEMLIST_PTR,ERROR,*9999)
      CALL FREE_MEMORY(GEOMFRAC_PTR,ERROR,*9999)
      CALL FREE_MEMORY(POINTCOORD_PTR,ERROR,*9999)
      CALL FREE_MEMORY(POINTS_PTR,ERROR,*9999)
      CALL FREE_MEMORY(PTAR_PTR,ERROR,*9999)
      CALL FREE_MEMORY(PWEIGHT_PTR,ERROR,*9999)
      CALL FREE_MEMORY(RANDOM_COORD_PTR,ERROR,*9999)
      CALL FREE_MEMORY(START_PTR,ERROR,*9999)
      CALL FREE_MEMORY(STARTNODE_PTR,ERROR,*9999)
      CALL FREE_MEMORY(TCX_PTR,ERROR,*9999)
      CALL FREE_MEMORY(WEIGHTS_PTR,ERROR,*9999)
      CALL FREE_MEMORY(XJPOWER_PTR,ERROR,*9999)

      CALL EXITS('IPMESH8')
      RETURN
 9999 CALL ERRORS('IPMESH8',ERROR)
      CALL EXITS('IPMESH8')
      RETURN 1
      END


