      SUBROUTINE IPMESH10(IBT,IDO,INP,LD,NBJ,NEELEM,
     '  NENP,NEP,NKJE,NPE,NPF,NP_INTERFACE,NPNE,NPNODE,
     '  nr,nr_coronary,NRE,NVJE,SE,XA,XE,XID,
     '  XIP,XP,ZD,ERROR,*)

C#### Subroutine: IPMESH10
C###  Description:
C###    IPMESH10 wraps IPMESH10_SUB dynamically allocating and freeing
C###    the arrays required in IPMESH10_SUB

      IMPLICIT NONE
      INCLUDE 'geom00.cmn'
      INCLUDE 'loc00.inc'

!     Parameter List
      INTEGER IBT(3,NIM,NBFM),IDO(NKM,NNM,0:NIM,NBFM),
     '  INP(NNM,NIM,NBFM),LD(NDM),
     '  NBJ(NJM,NEM),NEELEM(0:NE_R_M,0:NRM),
     '  NENP(NPM,0:NEPM,0:NRM),NEP(NPM),
     '  NKJE(NKM,NNM,NJM,NEM),NP_INTERFACE(0:NPM,0:3),
     '  NPE(0:NPM,NEM,NRM),
     '  NPF(9,NFM),NPNE(NNM,NBFM,NEM),
     '  NPNODE(0:NP_R_M,0:NRM),nr,nr_coronary,NRE(NEM),
     '  NVJE(NNM,NBFM,NJM,NEM)
      REAL*8 SE(NSM,NBFM,NEM),XA(NAM,NJM,NEM),XIP(NIM,NPM),
     '  XP(NKM,NVM,NJM,NPM),XE(NSM,NJM),XID(NIM,NDM),
     '  ZD(NJM,NDM)
      CHARACTER ERROR*(*)
!     Local Variables
      INTEGER*4 MAP_OLD2NEW_PTR,LARG_TOL_PTR

      CALL ENTERS('IPMESH10',*9999)

      MAP_OLD2NEW_PTR=0
      LARG_TOL_PTR=0

      CALL ALLOCATE_MEMORY(NP_R_M,0,1,MAP_OLD2NEW_PTR,.TRUE.,
     '  ERROR,*9999)
      CALL ALLOCATE_MEMORY(NDM,0,5,LARG_TOL_PTR,.TRUE.,
     '  ERROR,*9999)

      CALL IPMESH10_SUB(IBT,IDO,INP,LD,%VAL(LARG_TOL_PTR),
     '  %VAL(MAP_OLD2NEW_PTR),NBJ,NEELEM,
     '  NENP,NEP,NKJE,NPE,NPF,NP_INTERFACE,NPNE,NPNODE,
     '  nr,nr_coronary,NRE,NVJE,SE,XA,XE,XID,
     '  XIP,XP,ZD,ERROR,*9999)

      CALL FREE_MEMORY(MAP_OLD2NEW_PTR,ERROR,*9999)
      CALL FREE_MEMORY(LARG_TOL_PTR,ERROR,*9999)

      CALL EXITS('IPMESH10')
      RETURN
 9999 CALL ERRORS('IPMESH10',ERROR)
      CALL EXITS('IPMESH10')
      RETURN 1
      END


