      SUBROUTINE IPMESH6(IBT,IDO,INP,NBJ,NEELEM,
     '  NENP,NEP,NKJE,NKJ,NPE,
     '  NPF,NP_INTERFACE,NPNE,NPNODE,nr,nr_coronary,
     '  NRE,NXI,NVJE,NVJP,
     '  SE,XA,XE,XIP,XP,INPUT_PATH,ERROR,*)

C#### Subroutine: IPMESH6
C###  Description:
C###    IPMESH6 wraps IPMESH6_SUB dynamically allocating and freeing
C###    the arrays required in IPMESH6_SUB

      IMPLICIT NONE

      INCLUDE 'geom00.cmn'

!     Parameter List
      INTEGER IBT(3,NIM,NBFM),IDO(NKM,NNM,0:NIM,NBFM),
     '  INP(NNM,NIM,NBFM),NBJ(NJM,NEM),NEELEM(0:NE_R_M,0:NRM),
     '  NENP(NPM,0:NEPM,0:NRM),NEP(NPM),NKJE(NKM,NNM,NJM,NEM),
     '  NKJ(NJM,NPM),NPE(0:NPM,NEM,NRM),NP_INTERFACE(0:NPM,0:3),
     '  NPF(9,NFM),NPNE(NNM,NBFM,NEM),NPNODE(0:NP_R_M,0:NRM),nr,
     '  nr_coronary,NRE(NEM),NXI(-NIM:NIM,0:NEIM,0:NEM),
     '  NVJE(NNM,NBFM,NJM,NEM),NVJP(NJM,NPM)
      REAL*8 SE(NSM,NBFM,NEM),XA(NAM,NJM,NEM),XIP(NIM,NPM),
     '  XP(NKM,NVM,NJM,NPM),XE(NSM,NJM)
      CHARACTER*(*) INPUT_PATH
      CHARACTER ERROR*(*)
!     Local Variables
      INTEGER*4 AVOID_PT_PTR,AVOID_WT_PTR,AVOID_HOST_PTR,
     '  CART_NODE_PTR,ELE_LENGTH_PTR,NODE_ORDER_PTR,
     '  SITE_BRANCH_PTR,SITE_NUM_PTR,SITE_VALUE_PTR,
     '  SITE_VECTOR_PTR

      CALL ENTERS('IPMESH6',*9999)

      ELE_LENGTH_PTR=0
      CART_NODE_PTR=0
      NODE_ORDER_PTR=0
      SITE_VALUE_PTR=0
      SITE_VECTOR_PTR=0
      SITE_NUM_PTR=0
      SITE_BRANCH_PTR=0
      AVOID_PT_PTR=0
      AVOID_WT_PTR=0
      AVOID_HOST_PTR=0

      CALL ALLOCATE_MEMORY((NE_R_M+1),0,3,ELE_LENGTH_PTR,.TRUE.,
     '  ERROR,*9999)
      CALL ALLOCATE_MEMORY((3*NP_R_M),0,3,CART_NODE_PTR,.TRUE.,
     '  ERROR,*9999)
      CALL ALLOCATE_MEMORY(NP_R_M,0,1,NODE_ORDER_PTR,.TRUE.,
     '  ERROR,*9999)
      CALL ALLOCATE_MEMORY((4*NORM),0,3,SITE_VALUE_PTR,.TRUE.,
     '  ERROR,*9999)
      CALL ALLOCATE_MEMORY(3*NORM,0,3,SITE_VECTOR_PTR,.TRUE.,
     '  ERROR,*9999)
      CALL ALLOCATE_MEMORY(4*NORM,0,1,SITE_NUM_PTR,.TRUE.,
     '  ERROR,*9999)
      CALL ALLOCATE_MEMORY(NORM,0,1,SITE_BRANCH_PTR,.TRUE.,
     '  ERROR,*9999)
      CALL ALLOCATE_MEMORY((3*17*NORM),0,3,AVOID_PT_PTR,.TRUE.,
     '  ERROR,*9999)
      CALL ALLOCATE_MEMORY((17*NORM),0,3,AVOID_WT_PTR,.TRUE.,
     '  ERROR,*9999)
      CALL ALLOCATE_MEMORY((60*(1+(8*NORM))),0,1,
     '  AVOID_HOST_PTR,.TRUE.,ERROR,*9999)


      CALL IPMESH6_SUB(%VAL(AVOID_HOST_PTR),%VAL(AVOID_PT_PTR),
     '  %VAL(AVOID_WT_PTR),%VAL(CART_NODE_PTR),%VAL(ELE_LENGTH_PTR),
     '  IBT,IDO,INP,NBJ,NEELEM,
     '  NENP,NEP,NKJE,NKJ,%VAL(NODE_ORDER_PTR),NPE,
     '  NPF,NP_INTERFACE,NPNE,NPNODE,nr,nr_coronary,
     '  NRE,NXI,NVJE,NVJP,SE,
     '  %VAL(SITE_NUM_PTR),%VAL(SITE_BRANCH_PTR),
     '  %VAL(SITE_VALUE_PTR),
     '  %VAL(SITE_VECTOR_PTR),XA,XE,XIP,
     '  XP,INPUT_PATH,ERROR,*9999)

      CALL FREE_MEMORY(ELE_LENGTH_PTR,ERROR,*9999)
      CALL FREE_MEMORY(CART_NODE_PTR,ERROR,*9999)
      CALL FREE_MEMORY(NODE_ORDER_PTR,ERROR,*9999)
      CALL FREE_MEMORY(SITE_NUM_PTR,ERROR,*9999)
      CALL FREE_MEMORY(SITE_BRANCH_PTR,ERROR,*9999)
      CALL FREE_MEMORY(SITE_VALUE_PTR,ERROR,*9999)
      CALL FREE_MEMORY(SITE_VECTOR_PTR,ERROR,*9999)
      CALL FREE_MEMORY(AVOID_WT_PTR,ERROR,*9999)
      CALL FREE_MEMORY(AVOID_PT_PTR,ERROR,*9999)
      CALL FREE_MEMORY(AVOID_HOST_PTR,ERROR,*9999)

      CALL EXITS('IPMESH6')
      RETURN
 9999 CALL ERRORS('IPMESH6',ERROR)
      CALL EXITS('IPMESH6')
      RETURN 1
      END


