      SUBROUTINE ADD_CONSTANT(LABEL,ERROR,*)

C#### Subroutine: ADD_CONSTANT
C###  Description:
C###    Adds a constant.

      IMPLICIT NONE
      INCLUDE 'constant00.cmn'

!     Parameter List
      CHARACTER LABEL*(*),ERROR*(*)

      CALL ENTERS('ADD_CONSTANT',*9999)

      CALL SET_LABEL(CONSTANT_LABELS_PTR,TOTAL_CONSTANT_LABELS,
     &  ALLOCATED_CONSTANT_LABELS,CONSTANT_LABELS_LEN,LABEL,ERROR,*9999)

      CALL EXITS('ADD_CONSTANT')
      RETURN
 9999 CALL ERRORS('ADD_CONSTANT',ERROR)
      CALL EXITS('ADD_CONSTANT')
      RETURN 1
      END

