      SUBROUTINE ADD_CONSTANT_COMPONENT(CONSTANT_LABEL,COMPONENT_LABEL,
     &  ERROR,*)

C#### Subroutine: ADD_CONSTANT_COMPONENT
C###  Description:
C###    Adds a constant component label for a constant.

      IMPLICIT NONE
      INCLUDE 'constant00.cmn'

!     Parameter List
      CHARACTER CONSTANT_LABEL*(*),COMPONENT_LABEL*(*),ERROR*(*)
!     Local Variables
      INTEGER CONSTANT_INDEX

      CALL ENTERS('ADD_CONSTANT_COMPONENT',*9999)

      CALL GET_CONSTANT_INDEX(CONSTANT_LABEL,CONSTANT_INDEX,ERROR,*9999)
      
      CALL SET_LABEL_IN_ARRAY(
     &  CONST_COMPNT_LABELS_ARRAY,
     &  CONST_COMPNT_TOTAL_ARRAY,
     &  CONST_COMPNT_ALLOC_ARRAY,
     &  CONST_COMPNT_ARRAY_SIZE,
     &  CONSTANT_INDEX,CONST_COMPNT_LABELS_LEN,COMPONENT_LABEL,
     &  ERROR,*9999)

      CALL EXITS('ADD_CONSTANT_COMPONENT')
      RETURN
 9999 CALL ERRORS('ADD_CONSTANT_COMPONENT',ERROR)
      CALL EXITS('ADD_CONSTANT_COMPONENT')
      RETURN 1
      END


