      BLOCK DATA CONSTANT00

      IMPLICIT NONE
      INCLUDE 'constant00.cmn'

! Constant Labels
      DATA CONSTANT_LABELS_PTR/0/
      DATA ALLOCATED_CONSTANT_LABELS/0/
      DATA TOTAL_CONSTANT_LABELS/0/

! Constant Component Labels
      DATA CONST_COMPNT_LABELS_ARRAY/0/
      DATA CONST_COMPNT_TOTAL_ARRAY/0/
      DATA CONST_COMPNT_ALLOC_ARRAY/0/
      DATA CONST_COMPNT_ARRAY_SIZE/0/

! Constant Component Values
      DATA CONST_COMPNT_VALUE_ARRAY/0/
      DATA CONST_COMPNT_VALUE_ALLOC_ARRAY/0/
      DATA CONST_COMPNT_VALUE_ARRAY_SIZE/0/

      END



