      SUBROUTINE GET_CONSTANT_LABEL(CONSTANT_INDEX,CONSTANT_LABEL,
     &  ERROR,*)

C#### Subroutine: GET_CONSTANT_LABEL
C###  Description: GET_CONSTANT_LABEL
C###     Returns the label for a constant given an index.

      IMPLICIT NONE
      INCLUDE 'constant00.cmn'

!     Parameter List
      INTEGER CONSTANT_INDEX
      CHARACTER CONSTANT_LABEL*(*),ERROR*(*)

      CALL ENTERS('GET_CONSTANT_LABEL',*9999)

      CALL GET_LABEL(CONSTANT_LABELS_PTR,ALLOCATED_CONSTANT_LABELS,
     &  CONSTANT_INDEX,CONSTANT_LABELS_LEN,CONSTANT_LABEL,ERROR,*9999)

      CALL EXITS('GET_CONSTANT_LABEL')
      RETURN
 9999 CALL ERRORS('GET_CONSTANT_LABEL',ERROR)
      CALL EXITS('GET_CONSTANT_LABEL')
      RETURN 1
      END


