      SUBROUTINE GET_CONSTANT_COMPONENT_LABEL(CONSTANT_LABEL,
     &  COMPONENT_INDEX,COMPONENT_LABEL,ERROR,*)

C#### Subroutine: GET_CONSTANT_COMPONENT_LABEL
C###  Description:
C###    Gets a constant component label given an index.

      IMPLICIT NONE
      INCLUDE 'constant00.cmn'

!     Parameter List
      INTEGER CONSTANT_INDEX,COMPONENT_INDEX
      CHARACTER CONSTANT_LABEL*(*),COMPONENT_LABEL*(*),ERROR*(*)

      CALL ENTERS('GET_CONSTANT_COMPONENT_LABEL',*9999)

      CALL GET_CONSTANT_INDEX(CONSTANT_LABEL,CONSTANT_INDEX,ERROR,*9999)

      CALL GET_LABEL_IN_ARRAY(CONST_COMPNT_LABELS_ARRAY,
     &  CONST_COMPNT_ALLOC_ARRAY,
     &  CONST_COMPNT_ARRAY_SIZE,CONSTANT_INDEX,COMPONENT_INDEX,
     &  CONST_COMPNT_LABELS_LEN,COMPONENT_LABEL,ERROR,*9999)

      CALL EXITS('GET_CONSTANT_COMPONENT_LABEL')
      RETURN
 9999 CALL ERRORS('GET_CONSTANT_COMPONENT_LABEL',ERROR)
      CALL EXITS('GET_CONSTANT_COMPONENT_LABEL')
      RETURN 1
      END


