      SUBROUTINE GET_CONSTANT_COMPONENT_INDEX(CONSTANT_LABEL,
     &  COMPONENT_LABEL,COMPONENT_INDEX,ERROR,*)

C#### Subroutine: GET_CONSTANT_COMPONENT_INDEX
C###  Description:
C###    Returns the index of a constant component.

      IMPLICIT NONE
      INCLUDE 'constant00.cmn'

!     Parameter List
      INTEGER CONSTANT_INDEX,COMPONENT_INDEX
      CHARACTER CONSTANT_LABEL*(*),COMPONENT_LABEL*(*),ERROR*(*)
      

      CALL ENTERS('GET_CONSTANT_COMPONENT_INDEX',*9999)
      
      CALL GET_CONSTANT_INDEX(CONSTANT_LABEL,CONSTANT_INDEX,ERROR,*9999)

      CALL GET_INDEX_IN_ARRAY(CONST_COMPNT_LABELS_ARRAY,
     &  CONST_COMPNT_TOTAL_ARRAY,
     &  CONST_COMPNT_ALLOC_ARRAY,
     &  CONST_COMPNT_ARRAY_SIZE,CONSTANT_INDEX,
     &  CONST_COMPNT_LABELS_LEN,
     &  COMPONENT_LABEL,COMPONENT_INDEX,ERROR,*9999)

      CALL EXITS('GET_CONSTANT_COMPONENT_INDEX')
      RETURN
 9999 CALL ERRORS('GET_CONSTANT_COMPONENT_INDEX',ERROR)
      CALL EXITS('GET_CONSTANT_COMPONENT_INDEX')
      RETURN 1
      END


