      SUBROUTINE GET_CONSTANT_COMPONENT_TOTAL(CONSTANT_LABEL,
     &  TOTAL_CONSTANT_COMPONENT,ERROR,*)

C#### Subroutine: GET_CONSTANT_COMPONENT_TOTAL
C###  Description:
C###    Gets the total number of constant components.

      IMPLICIT NONE
      INCLUDE 'constant00.cmn'

!     Parameter List
      INTEGER TOTAL_CONSTANT_COMPONENT,CONSTANT_INDEX
      CHARACTER CONSTANT_LABEL*(CONSTANT_LABELS_LEN),ERROR*(*)

      CALL ENTERS('GET_CONSTANT_COMPONENT_TOTAL',*9999)
      
      CALL GET_CONSTANT_INDEX(CONSTANT_LABEL,CONSTANT_INDEX,ERROR,*9999)
      
      CALL GET_TOTAL_IN_ARRAY(
     &  %VAL(CONST_COMPNT_TOTAL_ARRAY),
     &  CONST_COMPNT_ARRAY_SIZE,
     &  CONSTANT_INDEX,TOTAL_CONSTANT_COMPONENT,ERROR,*9999)

      CALL EXITS('GET_CONSTANT_COMPONENT_TOTAL')
      RETURN
 9999 CALL ERRORS('GET_CONSTANT_COMPONENT_TOTAL',ERROR)
      CALL EXITS('GET_CONSTANT_COMPONENT_TOTAL')
      RETURN 1
      END


