      SUBROUTINE GET_CONSTANT_COMPONENT_VALUE(CONSTANT_LABEL,
     &  COMPONENT_LABEL,VALUE,ERROR,*)

C#### Subroutine: GET_CONSTANT_COMPONENT_VALUE
C###  Description:
C###    Gets the value for a constant component.

      IMPLICIT NONE
      INCLUDE 'constant00.cmn'

!     Parameter List
      INTEGER CONSTANT_INDEX,COMPONENT_INDEX
      REAL*8 VALUE
      CHARACTER CONSTANT_LABEL*(*),COMPONENT_LABEL*(*),ERROR*(*)

      CALL ENTERS('GET_CONSTANT_COMPONENT_VALUE',*9999)

      CALL GET_CONSTANT_INDEX(CONSTANT_LABEL,CONSTANT_INDEX,ERROR,*9999)
      CALL GET_CONSTANT_COMPONENT_INDEX(CONSTANT_LABEL,COMPONENT_LABEL,
     &  COMPONENT_INDEX,ERROR,*9999)

      CALL GET_REAL_IN_ARRAY(CONST_COMPNT_VALUE_ARRAY,
     &  CONST_COMPNT_VALUE_ALLOC_ARRAY,
     &  CONST_COMPNT_VALUE_ARRAY_SIZE,
     &  CONSTANT_INDEX,COMPONENT_INDEX,VALUE,ERROR,*9999)

      CALL EXITS('GET_CONSTANT_COMPONENT_VALUE')
      RETURN
 9999 CALL ERRORS('GET_CONSTANT_COMPONENT_VALUE',ERROR)
      CALL EXITS('GET_CONSTANT_COMPONENT_VALUE')
      RETURN 1
      END


