      SUBROUTINE GET_CONSTANT_INDEX(CONSTANT_LABEL,CONSTANT_INDEX,
     &  ERROR,*)

C#### Subroutine: GET_CONSTANT_INDEX
C###  Description:
C###    Returns the index of a constant.

      IMPLICIT NONE
      INCLUDE 'constant00.cmn'

!     Parameter List
      INTEGER CONSTANT_INDEX
      CHARACTER CONSTANT_LABEL*(*),ERROR*(*)
      

      CALL ENTERS('GET_CONSTANT_INDEX',*9999)

      CALL GET_INDEX(CONSTANT_LABELS_PTR,
     &  TOTAL_CONSTANT_LABELS,ALLOCATED_CONSTANT_LABELS,
     &  CONSTANT_LABELS_LEN,CONSTANT_LABEL,CONSTANT_INDEX,ERROR,*9999)

      CALL EXITS('GET_CONSTANT_INDEX')
      RETURN
 9999 CALL ERRORS('GET_CONSTANT_INDEX',ERROR)
      CALL EXITS('GET_CONSTANT_INDEX')
      RETURN 1
      END


