      SUBROUTINE PRINT_CONSTANTS(ERROR,*)

C#### Subroutine: PRINT_CONSTANTS
C###  Description:
C###    Prints constants details.

      IMPLICIT NONE
      INCLUDE 'cbdi02.cmn'
      INCLUDE 'colours00.cmn'
      INCLUDE 'constant00.cmn'

!     Parameter List
      CHARACTER ERROR*(*)

!     Local Variables
      INTEGER CINDEX,CTOTAL,PINDEX,PTOTAL,IB1,IE1
      REAL*8 VALUE
      CHARACTER CLABEL*(CONST_COMPNT_LABELS_LEN),
     &  PLABEL*(CONSTANT_LABELS_LEN)

      CALL ENTERS('PRINT_CONSTANTS',*9999)
          
      CALL GET_CONSTANT_TOTAL(PTOTAL,ERROR,*9999)
      
      DO PINDEX=1,PTOTAL
        CALL GET_CONSTANT_LABEL(PINDEX,PLABEL,ERROR,*9999)
        
        CALL STRING_TRIM(PLABEL,IB1,IE1)
        WRITE(OP_STRING,'(''CONSTANT: '//COLOUR_PARENT//PLABEL(IB1:IE1)
     &    //COLOUR_DEFAULT//''')')
        CALL WRITES(IOFI,OP_STRING,ERROR,*9999)
        WRITE(OP_STRING,'(4X,''Components:'')')
        CALL WRITES(IOFI,OP_STRING,ERROR,*9999)
        
        CALL GET_CONSTANT_COMPONENT_TOTAL(PLABEL,CTOTAL,ERROR,*9999)
        
       DO CINDEX=1,CTOTAL
          CALL GET_CONSTANT_COMPONENT_LABEL(PLABEL,CINDEX,CLABEL,
     &      ERROR,*9999)
          CALL GET_CONSTANT_COMPONENT_VALUE(PLABEL,CLABEL,VALUE,
     &      ERROR,*9999)
          CALL STRING_TRIM(CLABEL,IB1,IE1)
          WRITE(OP_STRING,'(7X,'''//COLOUR_CHILD//CLABEL(IB1:IE1)
     &      //COLOUR_DEFAULT//' = '',D12.5)') VALUE
          CALL WRITES(IOFI,OP_STRING,ERROR,*9999)
        ENDDO
        WRITE(OP_STRING,'()')
        CALL WRITES(IOFI,OP_STRING,ERROR,*9999)
      ENDDO 

      CALL EXITS('PRINT_CONSTANTS')
      RETURN
 9999 CALL ERRORS('PRINT_CONSTANTS',ERROR)
      CALL EXITS('PRINT_CONSTANTS')
      RETURN 1
      END


