      SUBROUTINE SET_CONSTANT_COMPONENT_VALUE(CONSTANT_LABEL,
     &  COMPONENT_LABEL,VALUE,ERROR,*)

C#### Subroutine: SET_CONSTANT_COMPONENT_VALUE
C###  Description:
C###    Sets the value for a constant component.

      IMPLICIT NONE
      INCLUDE 'constant00.cmn'

!     Parameter List
      REAL*8 VALUE
      CHARACTER CONSTANT_LABEL*(*),COMPONENT_LABEL*(*),ERROR*(*)
!     Local Variables
      INTEGER CONSTANT_INDEX,COMPONENT_INDEX

      CALL ENTERS('SET_CONSTANT_COMPONENT_VALUE',*9999)

      CALL GET_CONSTANT_INDEX(CONSTANT_LABEL,CONSTANT_INDEX,ERROR,*9999)
      CALL GET_CONSTANT_COMPONENT_INDEX(CONSTANT_LABEL,COMPONENT_LABEL,
     &  COMPONENT_INDEX,ERROR,*9999)
      
      CALL SET_REAL_IN_ARRAY(
     &  CONST_COMPNT_VALUE_ARRAY,
     &  CONST_COMPNT_VALUE_ALLOC_ARRAY,
     &  CONST_COMPNT_VALUE_ARRAY_SIZE,
     &  CONSTANT_INDEX,COMPONENT_INDEX,VALUE,
     &  ERROR,*9999)

      CALL EXITS('SET_CONSTANT_COMPONENT_VALUE')
      RETURN
 9999 CALL ERRORS('SET_CONSTANT_COMPONENT_VALUE',ERROR)
      CALL EXITS('SET_CONSTANT_COMPONENT_VALUE')
      RETURN 1
      END


