      SUBROUTINE SGGRID_NORM(ISEG,iw,NQLIST,NWQ,
     '  NXQ,DXDXIQ,DXDXIQ2,SCALE,XQ,CSEG,ERROR,*)

C#### Subroutine: SGGRID_NORM
C###  Description:
C###    SGGRID_NORM creates GRID normal vectors

      IMPLICIT NONE

      INCLUDE 'geom00.cmn'

!     Parameter List
      INTEGER ISEG(*),iw,NQLIST(0:NQM),NWQ(8,0:NQM),
     '  NXQ(-NIM:NIM,0:4,0:NQM)
      REAL*8 DXDXIQ(3,3,NQM),DXDXIQ2(3,3,NQM),SCALE,XQ(NJM,NQM)
      CHARACTER CSEG(*)*(*),ERROR*(*)
!     Local Variables
      INTEGER INDEXNORM,INDEX_POLYLINE,INDEX_OLD,ISNORM,nj,nq,nqq
      REAL*8 CENTER(3),DIRECTION(3),XNLOCAL(3)
      CHARACTER CLABEL*15

      CALL ENTERS('SGGRID_NORM',*9999)

      INDEXNORM=INDEX_POLYLINE(0,'SOLID','WIDTH2','BLACK')
      ISNORM=0
      CLABEL='NORMALS'

      CALL OPEN_SEGMENT(ISNORM,ISEG,iw,CLABEL,INDEXNORM,INDEX_OLD,
     '  0,1,CSEG,ERROR,*9999)

      DO nqq=1,NQLIST(0)
        nq=NQLIST(nqq)
        IF(NWQ(1,nq).GT.0) THEN
          CALL NORM31(NJT,nq,NXQ,DXDXIQ,DXDXIQ2,XNLOCAL,ERROR,*9999)
          DO nj=1,NJT
            CENTER(nj)=XQ(nj,nq)
            DIRECTION(nj)=XNLOCAL(nj)
          ENDDO !nj
          CENTER(3)=0.0d0
          DIRECTION(3)=0.0d0
          CALL VECTOR(INDEXNORM,iw,CENTER,DIRECTION,SCALE,ERROR,*9999)
        ENDIF
      ENDDO

      CALL CLOSE_SEGMENT(ISNORM,iw,ERROR,*9999)

      CALL EXITS('SGGRID_NORM')
      RETURN
 9999 CALL ERRORS('SGGRID_NORM',ERROR)
      CALL EXITS('SGGRID_NORM')
      RETURN 1
      END


