      SUBROUTINE SGSHEE(INDEX,IBT,IDO,INP,ISEG,ISSHEE,iw,
     '  NAN,NBJ,ne,NEELEM,NKJE,NPF,NPNE,NRE,NVJE,NXI,
     '  DXI2,DXI3,SE,THETA,XA,XE,XG,XP,CSEG,ERROR,*)

C#### Subroutine: SGSHEE
C###  Description:
C###    SGSHEE creates element sheet segment ISSHEE.

      IMPLICIT NONE
      INCLUDE 'geom00.cmn'
!     Parameter List
      INTEGER IBT(3,NIM,NBFM),IDO(NKM,NNM,0:NIM,NBFM),INDEX,
     '  INP(NNM,NIM,NBFM),ISEG(*),ISSHEE,iw,
     '  NAN(NIM,NAM,NBFM),NBJ(NJM,NEM),ne,
     '  NEELEM(0:NE_R_M,0:NRM),NKJE(NKM,NNM,NJM,NEM),
     '  NPF(9,NFM),NPNE(NNM,NBFM,NEM),
     '  NRE(NEM),NVJE(NNM,NBFM,NJM,NEM),
     '  NXI(-NIM:NIM,0:NEIM,0:NEM)
      REAL*8 DXI2,DXI3,SE(NSM,NBFM,NEM),THETA,
     '  XA(NAM,NJM,NEM),XE(NSM,NJM),XG(NJM,NUM),XP(NKM,NVM,NJM,NPM)
      CHARACTER CSEG(*)*(*),ERROR*(*)
!     Local Variables
      INTEGER INDEX_OLD

      CALL ENTERS('SGSHEE',*9999)
      CALL OPEN_SEGMENT(ISSHEE,ISEG,iw,'SHEE',INDEX,INDEX_OLD,
     '  ne,1,CSEG,ERROR,*9999)

      CALL SHEET1(INDEX,IBT,IDO,INP,iw,NAN,NBJ,ne,NEELEM,
     '  NKJE,NPF,NPNE,NRE,NVJE,NXI,
     '  DXI2,DXI3,SE,THETA,XA,XE,XG,XP,ERROR,*9999)

      CALL CLOSE_SEGMENT(ISSHEE,iw,ERROR,*9999)

      CALL EXITS('SGSHEE')
      RETURN
 9999 CALL ERRORS('SGSHEE',ERROR)
      CALL EXITS('SGSHEE')
      RETURN 1
      END


