      SUBROUTINE BINCLOSEFILE(FILEID,ERROR,*)

C#### Subroutine: BINCLOSEFILE
C###  Description:
C###    BINCLOSEFILE closes the binary file specified by FILEID.

      IMPLICIT NONE
!     Parameter List
      INTEGER FILEID
      CHARACTER ERROR*(*)
!     Local Variables
      INTEGER CERROR(50),CERRLEN,ERR

      CALL ENTERS('BINCLOSEFILE',*9999)

      CALL BINARYCLOSEFILE(FILEID,ERR,CERROR)
      IF(ERR.NE.0) THEN
        CALL CSTRINGLEN(CERRLEN,CERROR)
        CALL C2FSTRING(CERROR,CERRLEN,ERROR)
        GOTO 9999
      ENDIF

      CALL EXITS('BINCLOSEFILE')
      RETURN
 9999 CALL ERRORS('BINCLOSEFILE',ERROR)
      CALL EXITS('BINCLOSEFILE')
      RETURN 1
      END


