      SUBROUTINE BINSKIPFILE(FILEID,NUM_BYTES,ERROR,*)

C#### Subroutine: BINSKIPFILE
C###  Description:
C###    BINSKIPFILE skips num_bytes of data in a binary
C###    file specified by FILEID.

      IMPLICIT NONE
!     Parameter List
      INTEGER FILEID,NUM_BYTES
      CHARACTER ERROR*(*)
!     Local Variables
      INTEGER CERROR(50),CERRLEN,ERR

      CALL ENTERS('BINSKIPFILE',*9999)

      CALL BINARYSKIPFILE(FILEID,NUM_BYTES,ERR,CERROR)
      IF(ERR.NE.0) THEN
        CALL CSTRINGLEN(CERRLEN,CERROR)
        CALL C2FSTRING(CERROR,CERRLEN,ERROR)
        GOTO 9999
      ENDIF

      CALL EXITS('BINSKIPFILE')
      RETURN
 9999 CALL ERRORS('BINSKIPFILE',ERROR)
      CALL EXITS('BINSKIPFILE')
      CALL BINARYCLOSEFILE(FILEID,ERR,CERROR)
      RETURN 1
      END


