      SUBROUTINE DUMMY_TEST(routine,bob)

      IMPLICIT NONE

      INTEGER bob
      EXTERNAL routine

      INTEGER SIZES(11)
      INTEGER CONTROL(100),MODEL(100),VARIANT,AII(100),AIO(100),ERR_CODE
      REAL*8 TIME(100),Y(100),DY(100),DERIVED(100),PARAM(100),
     '  PROTOCOL(100),ARI(100),ARO(100)

      write(*,*) 'bob = ',bob
      CALL ROUTINE(TIME,Y,DY,CONTROL,MODEL,SIZES,VARIANT,
     '  DERIVED,PARAM,PROTOCOL,AII,AIO,ARI,ARO,ERR_CODE)

      RETURN
      END


