      SUBROUTINE ZGTG53EVALCELL_DYNAM(LOCAL_ICQS,LOCAL_RCQS,nq,
     &  RHSROUTINE,SIZES,VARIANT,YQS,ERROR,*)
C#### Subroutine: ZGTG53EVALCELL_DYNAM
C###  Description:
C###    Evaluates a cellml file for 1 grid point

      IMPLICIT NONE
      INCLUDE 'mxch.inc'
      INCLUDE 'cbdi02.cmn'
      INCLUDE 'cbdi10.cmn'
      INCLUDE 'cell02.cmn'
      INCLUDE 'cellml.cmn'
      INCLUDE 'cell_reserved.inc'
      INCLUDE 'geom00.cmn'
      INCLUDE 'grid00.cmn'
      INCLUDE 'ptr00.cmn'
!     Parameter List
      INTEGER LOCAL_ICQS(NQIM),nq,SIZES(11),VARIANT
      REAL*8 LOCAL_RCQS(NQRM),YQS(NIQSM,NQM)
      EXTERNAL RHSROUTINE
      CHARACTER ERROR*(*)
!     Local Variables
      INTEGER ERR
      REAL*8 DY(500),TIME(2)

      CALL ENTERS('ZGTG53EVALCELL_DYNAM',*9999)
C VJ 2Feb2004: Calling RHSROUTINE to evaluate CellML file at 1 grid point
      ERR=0
      CALL RHSROUTINE(TIME,
     &  YQS(CELL_STATE_OFFSET(VARIANT),nq),DY,
     &  LOCAL_ICQS(CELL_CONTROL_OFFSET(VARIANT)),
     &  LOCAL_ICQS(CELL_MODEL_OFFSET(VARIANT)),
     &  SIZES,LOCAL_ICQS(CELL_VARIANT_OFFSET),
     &  YQS(CELL_DERIVED_OFFSET(VARIANT),nq),
     &  LOCAL_RCQS(CELL_PARAMETERS_OFFSET(VARIANT)),
     &  LOCAL_RCQS(CELL_PROTOCOL_OFFSET(VARIANT)),
     &  LOCAL_ICQS(CELL_AII_OFFSET(VARIANT)),
     &  LOCAL_ICQS(CELL_AIO_OFFSET(VARIANT)),
     &  LOCAL_RCQS(CELL_ARI_OFFSET(VARIANT)),
     &  LOCAL_RCQS(CELL_ARO_OFFSET(VARIANT)),ERR)

      CALL EXITS('ZGTG53EVALCELL_DYNAM')
      RETURN
 9999 CALL ERRORS('ZGTG53EVALCELL_DYNAM',ERROR)
      CALL EXITS('ZGTG53EVALCELL_DYNAM')
      RETURN 1
      END

