      SUBROUTINE ZGTG53EVALCELL(CELL_ICQS_VALUE,CELL_RCQS_VALUE,
     &  ICQS_SPATIAL,IICQS_SPATIAL,IRCQS_SPATIAL,
     &  ne,ng,NQNE,RCQS_SPATIAL,
     &  YQS,ERROR,*)

C#### Subroutine: ZGTG53EVALCELL
C###  Description:
C###    ZGTG53CELL evaluates cell equations at 1 grid point

      IMPLICIT NONE
      INCLUDE 'mxch.inc'
      INCLUDE 'cbdi02.cmn'
      INCLUDE 'cbdi10.cmn'
      INCLUDE 'cell02.cmn'
      INCLUDE 'cellml.cmn'
      INCLUDE 'cell_reserved.inc'
      INCLUDE 'geom00.cmn'
      INCLUDE 'grid00.cmn'
      INCLUDE 'ptr00.cmn'
!     Parameter List
      INTEGER CELL_ICQS_VALUE(NQIM,NQVM),ICQS_SPATIAL(NQISVM,NQM),
     &  IICQS_SPATIAL(NQISVM,NQM),IRCQS_SPATIAL(0:NQRSVM,NQVM),
     &  ne,ng,NQNE(NEQM,NQEM)
      REAL*8 CELL_RCQS_VALUE(NQRM,NQVM),
     &  RCQS_SPATIAL(NQRSVM,NQM),YQS(NIQSM,NQM)
      CHARACTER ERROR*(*)
!     Local Variables
      INTEGER LOCAL_ICQS(NQIM),VARIANT,SIZES(11),nq
      REAL*8 LOCAL_RCQS(NQRM)

      CALL ENTERS('ZGTG53EVALCELL',*9999)
C obtain global grid point number
      nq=NQNE(ne,ng)
      CALL CELL_ASSIGN_SPATIAL(CELL_ICQS_VALUE,LOCAL_ICQS,
     &   ICQS_SPATIAL,IICQS_SPATIAL,IRCQS_SPATIAL,nq,CELL_RCQS_VALUE,
     &   LOCAL_RCQS,RCQS_SPATIAL,ERROR,*9999)
      VARIANT = LOCAL_ICQS(CELL_VARIANT_OFFSET)
      SIZES(NUM_EQN)=CELL_NUM_STATE(VARIANT)
      SIZES(NUM_CONTROL)=CELL_NUM_CONTROL(VARIANT)
      SIZES(NUM_MODEL)=CELL_NUM_MODEL(VARIANT)
      SIZES(NUM_DERIVED)=CELL_NUM_DERIVED(VARIANT)
      SIZES(NUM_PARAM)=CELL_NUM_PARAMETERS(VARIANT)
      SIZES(NUM_PROTOCOL)=CELL_NUM_PROTOCOL(VARIANT)
      SIZES(NUM_AII)=CELL_NUM_AII(VARIANT)
      SIZES(NUM_AIO)=CELL_NUM_AIO(VARIANT)
      SIZES(NUM_ARI)=CELL_NUM_ARI(VARIANT)
      SIZES(NUM_ARO)=CELL_NUM_ARO(VARIANT)
      SIZES(NUM_TIME)=2
C call the RHSROUTINE through ZGTG53EVALCELL_DYNAM
      CALL ZGTG53EVALCELL_DYNAM(LOCAL_ICQS,LOCAL_RCQS,nq,
     &  %VAL(CELLML_ROUTINES(VARIANT)),SIZES,
     &  VARIANT,YQS,ERROR,*9999)

      CALL EXITS('ZGTG53EVALCELL')
      RETURN
 9999 CALL ERRORS('ZGTG53EVALCELL',ERROR)
      CALL EXITS('ZGTG53EVALCELL')
      RETURN 1
      END

