      BLOCK DATA BDGROU00

      IMPLICIT NONE
      INCLUDE 'grou00.cmn'

      DATA NTGRDA/0/
      DATA NTGREL/0/
      DATA NTGRFA/0/
      DATA NTGRGA/0/
      DATA NTGRGR/0/
      DATA NTGRLI/0/
      DATA NTGRNO/0/
      DATA NTGRPL/0/
C      DATA LIGRDA_PTR/GR_MAXGRP*0/

C Initialized when used:
C      DATA LIGREL_PTR/GREL_MAXGRP*0/

      DATA LIGRFA_PTR/GRFA_MAXGRP*0/
      DATA LIGRGA_PTR/GRGA_MAXGRP*0/
      DATA LIGRGR_PTR/GRGR_MAXGRP*0/
      DATA LIGRLI_PTR/GRLI_MAXGRP*0/
      DATA LIGRNO_PTR/GRNO_MAXGRP*0/
C      DATA LIGRPL_PTR/GR_MAXGRP*0/
      END


