      SUBROUTINE GET_REAL_IN_ARRAY_CORE(
     &  REALS_ARRAY,ALLOCATED_ARRAY,
     &  ARRAY_SIZE,ARRAY_INDEX,REAL_INDEX,VALUE,ERROR,*)

C#### Subroutine: GET_REAL_IN_ARRAY_CORE
C###  Description:
C###    The core routine to get an real value from an array of arrays.

      IMPLICIT NONE

!     Parameter List
      INTEGER ARRAY_INDEX,ARRAY_SIZE,REAL_INDEX
      REAL*8 VALUE
      CHARACTER ERROR*(*)
      POINTER REALS_ARRAY(ARRAY_SIZE),
     &  ALLOCATED_ARRAY(ARRAY_SIZE)
     

      CALL ENTERS('GET_REAL_IN_ARRAY_CORE',*9999)

      CALL GET_REAL(REALS_ARRAY(ARRAY_INDEX),
     &  ALLOCATED_ARRAY(ARRAY_INDEX),
     &  REAL_INDEX,VALUE,ERROR,*9999)

      CALL EXITS('GET_REAL_IN_ARRAY_CORE')
      RETURN
 9999 CALL ERRORS('GET_REAL_IN_ARRAY_CORE',ERROR)
      CALL EXITS('GET_REAL_IN_ARRAY_CORE')
      RETURN 1
      END


