      SUBROUTINE GET_STRING_IN_ARRAY(STRINGS_ARRAY,
     &  ALLOCATED_ARRAY,ARRAY_SIZE,STRING_LEN,ARRAY_INDEX,
     &  STRING_INDEX,VALUE,ERROR,*)

C#### Subroutine: GET_STRING_IN_ARRAY
C###  Description:
C###    Gets a string from an array of arrays.

      IMPLICIT NONE      

!     Parameter List
      INTEGER ARRAY_INDEX,ARRAY_SIZE,STRING_INDEX,STRING_LEN
      CHARACTER VALUE*(*),ERROR*(*)
      POINTER ALLOCATED_ARRAY,STRINGS_ARRAY

      CALL ENTERS('GET_STRING_IN_ARRAY',*9999)
      
      CALL GET_STRING_IN_ARRAY_CORE(
     &  %VAL(STRINGS_ARRAY),
     &  %VAL(ALLOCATED_ARRAY),ARRAY_SIZE,STRING_LEN,
     &  ARRAY_INDEX,STRING_INDEX,VALUE,ERROR,*9999)

      CALL EXITS('GET_STRING_IN_ARRAY')
      RETURN
 9999 CALL ERRORS('GET_STRING_IN_ARRAY',ERROR)
      CALL EXITS('GET_STRING_IN_ARRAY')
      RETURN 1
      END


