      SUBROUTINE GET_STRING(STRINGS_PTR,ALLOCATED_STRINGS,
     &  STRING_LEN,INDEX,VALUE,ERROR,*)

C#### Subroutine: GET_STRING
C###  Description:
C###    Gets a string from an array.

      IMPLICIT NONE

!     Parameter List
      POINTER STRINGS_PTR
      INTEGER ALLOCATED_STRINGS,INDEX,STRING_LEN
      CHARACTER VALUE*(*),ERROR*(*)

      CALL ENTERS('GET_STRING',*9999)

      CALL GET_STRING_CORE(%VAL(STRINGS_PTR),ALLOCATED_STRINGS,
     &  INDEX,VALUE,ERROR,%VAL(STRING_LEN),*9999)

      CALL EXITS('GET_STRING')
      RETURN
 9999 CALL ERRORS('GET_STRING',ERROR)
      CALL EXITS('GET_STRING')
      RETURN 1
      END


