      SUBROUTINE GET_LABEL_IN_ARRAY_CORE(LABELS_ARRAY,
     &  ALLOCATED_ARRAY,ARRAY_SIZE,ARRAY_INDEX,INDEX,
     &  LABELS_LEN,LABEL,ERROR,*)

C#### Subroutine: GET_LABEL_IN_ARRAY_CORE
C###  Description:
C###    The core routine for getting a label from an array of arrays.

      IMPLICIT NONE

!     Parameter List
      INTEGER ARRAY_INDEX,ARRAY_SIZE,INDEX,LABELS_LEN
      INTEGER ALLOCATED_ARRAY(ARRAY_SIZE)
      POINTER LABELS_ARRAY(ARRAY_SIZE)
      CHARACTER LABEL*(*),ERROR*(*)

      CALL ENTERS('GET_LABEL_IN_ARRAY_CORE',*9999)

      CALL GET_LABEL(LABELS_ARRAY(ARRAY_INDEX),
     &  ALLOCATED_ARRAY(ARRAY_INDEX),INDEX,LABELS_LEN,
     &  LABEL,ERROR,*9999)
      
      CALL EXITS('GET_LABEL_IN_ARRAY_CORE')
      RETURN
 9999 CALL ERRORS('GET_LABEL_IN_ARRAY_CORE',ERROR)
      CALL EXITS('GET_LABEL_IN_ARRAY_CORE')
      RETURN 1
      END
