      SUBROUTINE GET_LABEL_IN_ARRAY(LABELS_ARRAY,
     &  ALLOCATED_ARRAY,ARRAY_SIZE,ARRAY_INDEX,INDEX,LABELS_LEN,
     &  LABEL,ERROR,*)

C#### Subroutine: GET_LABEL_IN_ARRAY
C###  Description:
C###    Gets a label from an array of arrays given an index.

      IMPLICIT NONE

!     Parameter List
      INTEGER ARRAY_INDEX,ARRAY_SIZE,INDEX,LABELS_LEN
      POINTER LABELS_ARRAY
      POINTER ALLOCATED_ARRAY
      CHARACTER LABEL*(*),ERROR*(*)

      CALL ENTERS('GET_LABEL_IN_ARRAY',*9999)

      CALL GET_LABEL_IN_ARRAY_CORE(%VAL(LABELS_ARRAY),
     &  %VAL(ALLOCATED_ARRAY),ARRAY_SIZE,ARRAY_INDEX,
     &  INDEX,LABELS_LEN,LABEL,ERROR,*9999)

      CALL EXITS('GET_LABEL_IN_ARRAY')
      RETURN
 9999 CALL ERRORS('GET_LABEL_IN_ARRAY',ERROR)
      CALL EXITS('GET_LABEL_IN_ARRAY')
      RETURN 1
      END


