      SUBROUTINE GET_STRING_IN_ARRAY_CORE(
     &  STRINGS_ARRAY,ALLOCATED_ARRAY,
     &  ARRAY_SIZE,STRING_LEN,ARRAY_INDEX,STRING_INDEX,VALUE,ERROR,*)

C#### Subroutine: GET_STRING_IN_ARRAY_CORE
C###  Description:
C###    The core routine to get a string in an array of arrays.

      IMPLICIT NONE

!     Parameter List
      INTEGER ARRAY_INDEX,ARRAY_SIZE,STRING_INDEX,STRING_LEN
      CHARACTER VALUE*(*),ERROR*(*)
      POINTER STRINGS_ARRAY(ARRAY_SIZE),
     &  ALLOCATED_ARRAY(ARRAY_SIZE)
     

      CALL ENTERS('GET_STRING_IN_ARRAY_CORE',*9999)

      CALL GET_STRING(STRINGS_ARRAY(ARRAY_INDEX),
     &  ALLOCATED_ARRAY(ARRAY_INDEX),STRING_LEN,
     &  STRING_INDEX,VALUE,ERROR,*9999)

      CALL EXITS('GET_STRING_IN_ARRAY_CORE')
      RETURN
 9999 CALL ERRORS('GET_STRING_IN_ARRAY_CORE',ERROR)
      CALL EXITS('GET_STRING_IN_ARRAY_CORE')
      RETURN 1
      END


