      SUBROUTINE GET_INTEGER_IN_ARRAY(INTEGERS_ARRAY,
     &  ALLOCATED_ARRAY,ARRAY_SIZE,ARRAY_INDEX,
     &  INTEGER_INDEX,VALUE,ERROR,*)

C#### Subroutine: GET_INTEGER_IN_ARRAY
C###  Description:
C###    Gets an integer from an array of arrays.

      IMPLICIT NONE      

!     Parameter List
      INTEGER ARRAY_INDEX,ARRAY_SIZE,INTEGER_INDEX,VALUE
      CHARACTER ERROR*(*)
      POINTER ALLOCATED_ARRAY,INTEGERS_ARRAY

      CALL ENTERS('GET_INTEGER_IN_ARRAY',*9999)
      
      CALL GET_INTEGER_IN_ARRAY_CORE(
     &  %VAL(INTEGERS_ARRAY),
     &  %VAL(ALLOCATED_ARRAY),
     &  ARRAY_SIZE,ARRAY_INDEX,INTEGER_INDEX,VALUE,ERROR,*9999)

      CALL EXITS('GET_INTEGER_IN_ARRAY')
      RETURN
 9999 CALL ERRORS('GET_INTEGER_IN_ARRAY',ERROR)
      CALL EXITS('GET_INTEGER_IN_ARRAY')
      RETURN 1
      END


