      SUBROUTINE GET_LABEL(LABELS_PTR,ALLOCATED_LABELS,
     &  INDEX,LABELS_LEN,LABEL,ERROR,*)

C#### Subroutine: GET_LABEL
C###  Description:
C###    Gets a label from an array given an index.

      IMPLICIT NONE

!     Parameter List
      INTEGER ALLOCATED_LABELS,INDEX,LABELS_LEN
      POINTER LABELS_PTR
      CHARACTER LABEL*(*),ERROR*(*)

      CALL ENTERS('GET_LABEL',*9999)

      CALL GET_LABEL_CORE(%VAL(LABELS_PTR),ALLOCATED_LABELS,
     &  INDEX,LABEL,ERROR,%VAL(LABELS_LEN),*9999)

      CALL EXITS('GET_LABEL')
      RETURN
 9999 CALL ERRORS('GET_LABEL',ERROR)
      CALL EXITS('GET_LABEL')
      RETURN 1
      END


