      SUBROUTINE GET_INDEX_IN_ARRAY_CORE(LABELS_ARRAY,
     &  TOTAL_ARRAY,ALLOCATED_ARRAY,ARRAY_SIZE,ARRAY_INDEX,
     &  LABELS_LEN,LABEL,INDEX,ERROR,*)

C#### Subroutine: GET_INDEX_IN_ARRAY_CORE
C###  Description:
C###    The core routine for getting an index for a given label 
C###    from an array of arrays.

      IMPLICIT NONE

!     Parameter List
      INTEGER ARRAY_INDEX,ARRAY_SIZE,INDEX
      INTEGER LABELS_LEN
      INTEGER TOTAL_ARRAY(ARRAY_SIZE)
      INTEGER ALLOCATED_ARRAY(ARRAY_SIZE)
      POINTER LABELS_ARRAY(ARRAY_SIZE)
      CHARACTER LABEL*(*),ERROR*(*)

      CALL ENTERS('GET_INDEX_IN_ARRAY_CORE',*9999)
      
      IF(ARRAY_SIZE.LT.ARRAY_INDEX)THEN
        INDEX=0
      ELSE
        CALL GET_INDEX(LABELS_ARRAY(ARRAY_INDEX),
     &    TOTAL_ARRAY(ARRAY_INDEX),ALLOCATED_ARRAY(ARRAY_INDEX),
     &    LABELS_LEN,LABEL,INDEX,ERROR,*9999)
      ENDIF
      
      CALL EXITS('GET_INDEX_IN_ARRAY_CORE')
      RETURN
 9999 CALL ERRORS('GET_INDEX_IN_ARRAY_CORE',ERROR)
      CALL EXITS('GET_INDEX_IN_ARRAY_CORE')
      RETURN 1
      END
