      SUBROUTINE GET_INTEGER(INTEGERS_PTR,ALLOCATED_INTEGERS,
     &  INDEX,VALUE,ERROR,*)

C#### Subroutine: GET_INTEGER
C###  Description:
C###    Gets a integer from an array.

      IMPLICIT NONE

!     Parameter List
      POINTER INTEGERS_PTR
      INTEGER ALLOCATED_INTEGERS,INDEX,VALUE
      CHARACTER ERROR*(*)

      CALL ENTERS('GET_INTEGER',*9999)

      CALL GET_INTEGER_CORE(%VAL(INTEGERS_PTR),ALLOCATED_INTEGERS,
     &  INDEX,VALUE,ERROR,*9999)

      CALL EXITS('GET_INTEGER')
      RETURN
 9999 CALL ERRORS('GET_INTEGER',ERROR)
      CALL EXITS('GET_INTEGER')
      RETURN 1
      END


