      SUBROUTINE GET_INTEGER_CORE(INTEGERS_PTR,ALLOCATED_INTEGERS,
     &  INDEX,VALUE,ERROR,*)

C#### Subroutine: GET_INTEGER_CORE
C###  Description:
C###    The core routine for getting an interger from an array.

      IMPLICIT NONE

!     Parameter List
      INTEGER ALLOCATED_INTEGERS,INDEX,VALUE
      INTEGER INTEGERS_PTR(ALLOCATED_INTEGERS)
      CHARACTER ERROR*(*)

      CALL ENTERS('GET_INTEGER_CORE',*9999)

      VALUE=INTEGERS_PTR(INDEX)

      CALL EXITS('GET_INTEGER_CORE')
      RETURN
 9999 CALL ERRORS('GET_INTEGER_CORE',ERROR)
      CALL EXITS('GET_INTEGER_CORE')
      RETURN 1
      END


