      SUBROUTINE GET_INDEX(LABELS_PTR,TOTAL_LABELS,
     &  ALLOCATED_LABELS,LABELS_LEN,LABEL,INDEX,ERROR,*)

C#### Subroutine: GET_INDEX
C###  Description:
C###    Returns the index of a label

      IMPLICIT NONE

!     Parameter List
      POINTER LABELS_PTR
      INTEGER LABELS_LEN
      INTEGER ALLOCATED_LABELS,INDEX,TOTAL_LABELS
      CHARACTER LABEL*(*),ERROR*(*)

      CALL ENTERS('GET_INDEX',*9999)

      CALL GET_INDEX_CORE(%VAL(LABELS_PTR),
     &  TOTAL_LABELS,ALLOCATED_LABELS,LABEL,INDEX,ERROR,
     &  %VAL(LABELS_LEN),*9999)

      CALL EXITS('GET_INDEX')
      RETURN
 9999 CALL ERRORS('GET_INDEX',ERROR)
      CALL EXITS('GET_INDEX')
      RETURN 1
      END


