      SUBROUTINE GET_INDEX_IN_ARRAY(LABELS_ARRAY,TOTAL_ARRAY,
     &  ALLOCATED_ARRAY,ARRAY_SIZE,ARRAY_INDEX,LABELS_LEN,LABEL,
     &  INDEX,ERROR,*)

C#### Subroutine: GET_INDEX_IN_ARRAY
C###  Description:
C###    Gets the index of a label from an array of arrays.

      IMPLICIT NONE

!     Parameter List
      INTEGER ARRAY_INDEX,ARRAY_SIZE,INDEX,LABELS_LEN
      POINTER LABELS_ARRAY
      POINTER TOTAL_ARRAY
      POINTER ALLOCATED_ARRAY
      CHARACTER LABEL*(*),ERROR*(*)

      CALL ENTERS('GET_INDEX_IN_ARRAY',*9999)

      CALL GET_INDEX_IN_ARRAY_CORE(%VAL(LABELS_ARRAY),
     &  %VAL(TOTAL_ARRAY),%VAL(ALLOCATED_ARRAY),
     &  ARRAY_SIZE,ARRAY_INDEX,LABELS_LEN,LABEL,INDEX,ERROR,*9999)

      CALL EXITS('GET_INDEX_IN_ARRAY')
      RETURN
 9999 CALL ERRORS('GET_INDEX_IN_ARRAY',ERROR)
      CALL EXITS('GET_INDEX_IN_ARRAY')
      RETURN 1
      END


