      SUBROUTINE GET_INTEGER_IN_ARRAY_CORE(
     &  INTEGERS_ARRAY,ALLOCATED_ARRAY,
     &  ARRAY_SIZE,ARRAY_INDEX,INTEGER_INDEX,VALUE,ERROR,*)

C#### Subroutine: GET_INTEGER_IN_ARRAY_CORE
C###  Description:
C###    The core routine to get an integer from an array of arrays.

      IMPLICIT NONE

!     Parameter List
      INTEGER ARRAY_INDEX,ARRAY_SIZE,INTEGER_INDEX,VALUE
      CHARACTER ERROR*(*)
      POINTER INTEGERS_ARRAY(ARRAY_SIZE),
     &  ALLOCATED_ARRAY(ARRAY_SIZE)
     

      CALL ENTERS('GET_INTEGER_IN_ARRAY_CORE',*9999)

      CALL GET_INTEGER(INTEGERS_ARRAY(ARRAY_INDEX),
     &  ALLOCATED_ARRAY(ARRAY_INDEX),
     &  INTEGER_INDEX,VALUE,ERROR,*9999)

      CALL EXITS('GET_INTEGER_IN_ARRAY_CORE')
      RETURN
 9999 CALL ERRORS('GET_INTEGER_IN_ARRAY_CORE',ERROR)
      CALL EXITS('GET_INTEGER_IN_ARRAY_CORE')
      RETURN 1
      END


