      SUBROUTINE GET_REAL_IN_ARRAY(REALS_ARRAY,
     &  ALLOCATED_ARRAY,ARRAY_SIZE,ARRAY_INDEX,
     &  REAL_INDEX,VALUE,ERROR,*)

C#### Subroutine: GET_REAL_IN_ARRAY
C###  Description:
C###    Gets a real value from an array of arrays.

      IMPLICIT NONE      

!     Parameter List
      INTEGER ARRAY_INDEX,ARRAY_SIZE,REAL_INDEX
      REAL*8 VALUE
      CHARACTER ERROR*(*)
      POINTER ALLOCATED_ARRAY,REALS_ARRAY

      CALL ENTERS('GET_REAL_IN_ARRAY',*9999)
      
      CALL GET_REAL_IN_ARRAY_CORE(
     &  %VAL(REALS_ARRAY),
     &  %VAL(ALLOCATED_ARRAY),
     &  ARRAY_SIZE,ARRAY_INDEX,REAL_INDEX,VALUE,ERROR,*9999)

      CALL EXITS('GET_REAL_IN_ARRAY')
      RETURN
 9999 CALL ERRORS('GET_REAL_IN_ARRAY',ERROR)
      CALL EXITS('GET_REAL_IN_ARRAY')
      RETURN 1
      END


