      SUBROUTINE SET_LABEL_IN_ARRAY_CORE(
     &  LABELS_ARRAY,TOTAL_ARRAY,ALLOCATED_ARRAY,
     &  ARRAY_SIZE,ARRAY_INDEX,LABELS_LEN,LABEL,ERROR,*)

C#### Subroutine: SET_LABEL_IN_ARRAY_CORE
C###  Description:
C###    The core routine to sets a label in an array of arrays.

      IMPLICIT NONE

!     Parameter List
      INTEGER ARRAY_INDEX,ARRAY_SIZE,LABELS_LEN
      CHARACTER LABEL*(*),ERROR*(*)
      POINTER LABELS_ARRAY(ARRAY_INDEX),
     &  TOTAL_ARRAY(ARRAY_INDEX),
     &  ALLOCATED_ARRAY(ARRAY_INDEX)
     
!     Local Variables
      INTEGER i

      CALL ENTERS('SET_LABEL_IN_ARRAY_CORE',*9999)

      IF(ARRAY_INDEX.GT.ARRAY_SIZE)THEN
        DO i=ARRAY_SIZE+1,ARRAY_INDEX
          LABELS_ARRAY(i)=0
          TOTAL_ARRAY(i)=0
          ALLOCATED_ARRAY(i)=0
        ENDDO
        ARRAY_SIZE=ARRAY_INDEX
      ENDIF
      
      CALL SET_LABEL(LABELS_ARRAY(ARRAY_INDEX),
     &  TOTAL_ARRAY(ARRAY_INDEX),
     &  ALLOCATED_ARRAY(ARRAY_INDEX),
     &  LABELS_LEN,LABEL,ERROR,*9999)

      CALL EXITS('SET_LABEL_IN_ARRAY_CORE')
      RETURN
 9999 CALL ERRORS('SET_LABEL_IN_ARRAY_CORE',ERROR)
      CALL EXITS('SET_LABEL_IN_ARRAY_CORE')
      RETURN 1
      END


