      SUBROUTINE SET_REAL(REALS_PTR,ALLOCATED_VALUES,INDEX,VALUE,
     &  ERROR,*)

C#### Subroutine: SET_REAL
C###  Description:
C###    Sets a real value in an array.

      IMPLICIT NONE
      INCLUDE 'mach00.inc'

!     Parameter List
      POINTER REALS_PTR
      INTEGER ALLOCATED_VALUES,INDEX,NEW_ALLOCATION,MEM_INCR
      REAL*8 VALUE
      PARAMETER (MEM_INCR=10)
      CHARACTER ERROR*(*)

      CALL ENTERS('SET_REAL',*9999)

      
      IF(INDEX.GT.ALLOCATED_VALUES)THEN
        NEW_ALLOCATION=((INT(INDEX/MEM_INCR))+1)*MEM_INCR
        CALL REALLOCATE_MEMORY(NEW_ALLOCATION,DPTYPE,REALS_PTR,
     &    ERROR,*9999)
        ALLOCATED_VALUES=NEW_ALLOCATION
      ENDIF
      
      CALL SET_REAL_CORE(%VAL(REALS_PTR),ALLOCATED_VALUES,
     &  INDEX,VALUE,ERROR,*9999)

      CALL EXITS('SET_REAL')
      RETURN
 9999 CALL ERRORS('SET_REAL',ERROR)
      CALL EXITS('SET_REAL')
      RETURN 1
      END


