      SUBROUTINE SET_LABEL_IN_ARRAY(LABELS_ARRAY,
     &  TOTAL_ARRAY,ALLOCATED_ARRAY,
     &  ARRAY_SIZE,ARRAY_INDEX,LABELS_LEN,LABEL,ERROR,*)

C#### Subroutine: SET_LABEL_IN_ARRAY
C###  Description:
C###   Sets a label in an array of arrays.

      IMPLICIT NONE
      INCLUDE 'mach00.inc'

!     Parameter List
      INTEGER ARRAY_INDEX,ARRAY_SIZE,LABELS_LEN
      CHARACTER LABEL*(*),ERROR*(*)
      POINTER ALLOCATED_ARRAY,LABELS_ARRAY,TOTAL_ARRAY

      CALL ENTERS('SET_LABEL_IN_ARRAY',*9999)
      
      IF(ARRAY_INDEX.GT.ARRAY_SIZE)THEN
        CALL REALLOCATE_MEMORY(ARRAY_INDEX,
     '    POINTERTYPE,LABELS_ARRAY,ERROR,*9999)
        CALL REALLOCATE_MEMORY(ARRAY_INDEX,
     '    POINTERTYPE,TOTAL_ARRAY,ERROR,*9999)
        CALL REALLOCATE_MEMORY(ARRAY_INDEX,
     '    POINTERTYPE,ALLOCATED_ARRAY,ERROR,*9999)
      ENDIF
      
      CALL SET_LABEL_IN_ARRAY_CORE(
     &  %VAL(LABELS_ARRAY),
     &  %VAL(TOTAL_ARRAY),
     &  %VAL(ALLOCATED_ARRAY),
     &  ARRAY_SIZE,ARRAY_INDEX,LABELS_LEN,LABEL,ERROR,*9999)

      CALL EXITS('SET_LABEL_IN_ARRAY')
      RETURN
 9999 CALL ERRORS('SET_LABEL_IN_ARRAY',ERROR)
      CALL EXITS('SET_LABEL_IN_ARRAY')
      RETURN 1
      END


