      SUBROUTINE SET_INTEGER_CORE(INTEGERS_PTR,ALLOCATED_VALUES,
     &  INDEX,VALUE,ERROR,*)

C#### Subroutine: SET_INTEGER_CORE
C###  Description:
C###    The core routine for setting an interger in an array.

      IMPLICIT NONE

!     Parameter List
      INTEGER ALLOCATED_VALUES,INDEX,VALUE
      INTEGER INTEGERS_PTR(ALLOCATED_VALUES)
      CHARACTER ERROR*(*)

      CALL ENTERS('SET_INTEGER_CORE',*9999)

      INTEGERS_PTR(INDEX)=VALUE

      CALL EXITS('SET_INTEGER_CORE')
      RETURN
 9999 CALL ERRORS('SET_INTEGER_CORE',ERROR)
      CALL EXITS('SET_INTEGER_CORE')
      RETURN 1
      END


