      SUBROUTINE SET_INTEGER_IN_ARRAY(INTEGERS_ARRAY,
     &  ALLOCATED_ARRAY,
     &  ARRAY_SIZE,ARRAY_INDEX,INTEGER_INDEX,VALUE,ERROR,*)

C#### Subroutine: SET_INTEGER_IN_ARRAY
C###  Description:
C###    Sets an integer in an array of arrays.

      IMPLICIT NONE
      INCLUDE 'mach00.inc'
      

!     Parameter List
      INTEGER ARRAY_INDEX,ARRAY_SIZE,INTEGER_INDEX,VALUE
      CHARACTER ERROR*(*)
      POINTER ALLOCATED_ARRAY,INTEGERS_ARRAY

      CALL ENTERS('SET_INTEGER_IN_ARRAY',*9999)
      
      IF(ARRAY_INDEX.GT.ARRAY_SIZE)THEN
        CALL REALLOCATE_MEMORY(ARRAY_INDEX,
     '    POINTERTYPE,INTEGERS_ARRAY,ERROR,*9999)
        CALL REALLOCATE_MEMORY(ARRAY_INDEX,
     '    POINTERTYPE,ALLOCATED_ARRAY,ERROR,*9999)
      ENDIF
      
      CALL SET_INTEGER_IN_ARRAY_CORE(
     &  %VAL(INTEGERS_ARRAY),
     &  %VAL(ALLOCATED_ARRAY),
     &  ARRAY_SIZE,ARRAY_INDEX,INTEGER_INDEX,VALUE,ERROR,*9999)

      CALL EXITS('SET_INTEGER_IN_ARRAY')
      RETURN
 9999 CALL ERRORS('SET_INTEGER_IN_ARRAY',ERROR)
      CALL EXITS('SET_INTEGER_IN_ARRAY')
      RETURN 1
      END


