      SUBROUTINE SET_REAL_IN_ARRAY(REALS_ARRAY,
     &  ALLOCATED_ARRAY,
     &  ARRAY_SIZE,ARRAY_INDEX,REAL_INDEX,VALUE,ERROR,*)

C#### Subroutine: SET_REAL_IN_ARRAY
C###  Description:
C###    Sets a real value in an array of arrays.

      IMPLICIT NONE
      INCLUDE 'mach00.inc'
      

!     Parameter List
      INTEGER ARRAY_INDEX,ARRAY_SIZE,REAL_INDEX
      REAL*8 VALUE
      CHARACTER ERROR*(*)
      POINTER ALLOCATED_ARRAY,REALS_ARRAY

      CALL ENTERS('SET_REAL_IN_ARRAY',*9999)
      
      IF(ARRAY_INDEX.GT.ARRAY_SIZE)THEN
        CALL REALLOCATE_MEMORY(ARRAY_INDEX,
     '    DPTYPE,REALS_ARRAY,ERROR,*9999)
        CALL REALLOCATE_MEMORY(ARRAY_INDEX,
     '    DPTYPE,ALLOCATED_ARRAY,ERROR,*9999)
      ENDIF
      
      CALL SET_REAL_IN_ARRAY_CORE(
     &  %VAL(REALS_ARRAY),%VAL(ALLOCATED_ARRAY),
     &  ARRAY_SIZE,ARRAY_INDEX,REAL_INDEX,VALUE,ERROR,*9999)

      CALL EXITS('SET_REAL_IN_ARRAY')
      RETURN
 9999 CALL ERRORS('SET_REAL_IN_ARRAY',ERROR)
      CALL EXITS('SET_REAL_IN_ARRAY')
      RETURN 1
      END


