      SUBROUTINE SET_INTEGER_IN_ARRAY_CORE(
     &  INTEGERS_ARRAY,ALLOCATED_ARRAY,
     &  ARRAY_SIZE,ARRAY_INDEX,INTEGER_INDEX,VALUE,ERROR,*)

C#### Subroutine: SET_INTEGER_IN_ARRAY_CORE
C###  Description:
C###    The core routine to set an integer in an array of arrays.

      IMPLICIT NONE

!     Parameter List
      INTEGER ARRAY_INDEX,ARRAY_SIZE,INTEGER_INDEX,VALUE
      CHARACTER ERROR*(*)
      POINTER INTEGERS_ARRAY(ARRAY_INDEX),
     &  ALLOCATED_ARRAY(ARRAY_INDEX)
     
!     Local Variables
      INTEGER i

      CALL ENTERS('SET_INTEGER_IN_ARRAY_CORE',*9999)

      IF(ARRAY_INDEX.GT.ARRAY_SIZE)THEN
        DO i=ARRAY_SIZE+1,ARRAY_INDEX
          INTEGERS_ARRAY(i)=0
          ALLOCATED_ARRAY(i)=0
        ENDDO
        ARRAY_SIZE=ARRAY_INDEX
      ENDIF
      
      CALL SET_INTEGER(INTEGERS_ARRAY(ARRAY_INDEX),
     &  ALLOCATED_ARRAY(ARRAY_INDEX),
     &  INTEGER_INDEX,VALUE,ERROR,*9999)

      CALL EXITS('SET_INTEGER_IN_ARRAY_CORE')
      RETURN
 9999 CALL ERRORS('SET_INTEGER_IN_ARRAY_CORE',ERROR)
      CALL EXITS('SET_INTEGER_IN_ARRAY_CORE')
      RETURN 1
      END


