      SUBROUTINE SET_STRING_IN_ARRAY(STRINGS_ARRAY,
     &  ALLOCATED_ARRAY,
     &  ARRAY_SIZE,STRING_LEN,ARRAY_INDEX,STRING_INDEX,VALUE,ERROR,*)

C#### Subroutine: SET_STRING_IN_ARRAY
C###  Description:
C###    Sets a string value in an array of arrays.

      IMPLICIT NONE
      INCLUDE 'mach00.inc'
      

!     Parameter List
      INTEGER ARRAY_INDEX,ARRAY_SIZE,STRING_INDEX,STRING_LEN
      CHARACTER VALUE*(*),ERROR*(*)
      POINTER ALLOCATED_ARRAY,STRINGS_ARRAY

      CALL ENTERS('SET_STRING_IN_ARRAY',*9999)
      
      IF(ARRAY_INDEX.GT.ARRAY_SIZE)THEN
        CALL REALLOCATE_MEMORY(ARRAY_INDEX,
     '    POINTERTYPE,STRINGS_ARRAY,ERROR,*9999)
        CALL REALLOCATE_MEMORY(ARRAY_INDEX,
     '    POINTERTYPE,ALLOCATED_ARRAY,ERROR,*9999)
      ENDIF
      
      CALL SET_STRING_IN_ARRAY_CORE(
     &  %VAL(STRINGS_ARRAY),
     &  %VAL(ALLOCATED_ARRAY),
     &  ARRAY_SIZE,STRING_LEN,ARRAY_INDEX,
     &  STRING_INDEX,VALUE,ERROR,*9999)

      CALL EXITS('SET_STRING_IN_ARRAY')
      RETURN
 9999 CALL ERRORS('SET_STRING_IN_ARRAY',ERROR)
      CALL EXITS('SET_STRING_IN_ARRAY')
      RETURN 1
      END


