      SUBROUTINE SET_LABEL(LABELS_PTR,TOTAL_LABELS,
     &  ALLOCATED_LABELS,LABELS_LEN,LABEL,ERROR,*)

C#### Subroutine: SET_LABEL
C###  Description:
C###    Sets a label in an array.

      IMPLICIT NONE
      INCLUDE 'mach00.inc'

!     Parameter List
      POINTER LABELS_PTR
      INTEGER ALLOCATED_LABELS,LABELS_INCR,LABELS_LEN,TOTAL_LABELS
      PARAMETER (LABELS_INCR=10)
      CHARACTER LABEL*(*),ERROR*(*)

      CALL ENTERS('SET_LABEL',*9999)

      
      IF(TOTAL_LABELS+1.GT.ALLOCATED_LABELS)THEN
        CALL REALLOCATE_MEMORY(
     &    (ALLOCATED_LABELS+LABELS_INCR)*LABELS_LEN,
     &    CHARTYPE,LABELS_PTR,ERROR,*9999)
        ALLOCATED_LABELS=ALLOCATED_LABELS+LABELS_INCR
      ENDIF
      
      CALL SET_LABEL_CORE(%VAL(LABELS_PTR),TOTAL_LABELS,
     &  ALLOCATED_LABELS,LABEL,ERROR,%VAL(LABELS_LEN),*9999)

      CALL EXITS('SET_LABEL')
      RETURN
 9999 CALL ERRORS('SET_LABEL',ERROR)
      CALL EXITS('SET_LABEL')
      RETURN 1
      END


