      SUBROUTINE SET_REAL_IN_ARRAY_CORE(
     &  REALS_ARRAY,ALLOCATED_ARRAY,
     &  ARRAY_SIZE,ARRAY_INDEX,REAL_INDEX,VALUE,ERROR,*)

C#### Subroutine: SET_REAL_IN_ARRAY_CORE
C###  Description:
C###    Sets a real value in an array of array.

      IMPLICIT NONE

!     Parameter List
      INTEGER ARRAY_INDEX,ARRAY_SIZE,REAL_INDEX
      REAL*8 VALUE
      CHARACTER ERROR*(*)
      POINTER REALS_ARRAY(ARRAY_INDEX),
     &  ALLOCATED_ARRAY(ARRAY_INDEX)
     
!     Local Variables
      INTEGER i

      CALL ENTERS('SET_REAL_IN_ARRAY_CORE',*9999)

      IF(ARRAY_INDEX.GT.ARRAY_SIZE)THEN
        DO i=ARRAY_SIZE+1,ARRAY_INDEX
          REALS_ARRAY(i)=0
          ALLOCATED_ARRAY(i)=0
        ENDDO
        ARRAY_SIZE=ARRAY_INDEX
      ENDIF
      
      CALL SET_REAL(REALS_ARRAY(ARRAY_INDEX),
     &  ALLOCATED_ARRAY(ARRAY_INDEX),
     &  REAL_INDEX,VALUE,ERROR,*9999)

      CALL EXITS('SET_REAL_IN_ARRAY_CORE')
      RETURN
 9999 CALL ERRORS('SET_REAL_IN_ARRAY_CORE',ERROR)
      CALL EXITS('SET_REAL_IN_ARRAY_CORE')
      RETURN 1
      END


