      SUBROUTINE SET_STRING_CORE(STRINGS_PTR,ALLOCATED_STRINGS,
     &  INDEX,VALUE,ERROR,*)

C#### Subroutine: SET_STRING_CORE
C###  Description:
C###    The core routine for setting an string in an array.

      IMPLICIT NONE

!     Parameter List
      INTEGER ALLOCATED_STRINGS,INDEX
      CHARACTER STRINGS_PTR(ALLOCATED_STRINGS)*(*)
      CHARACTER VALUE*(*),ERROR*(*)

      CALL ENTERS('SET_STRING_CORE',*9999)

      STRINGS_PTR(INDEX)=VALUE

      CALL EXITS('SET_STRING_CORE')
      RETURN
 9999 CALL ERRORS('SET_STRING_CORE',ERROR)
      CALL EXITS('SET_STRING_CORE')
      RETURN 1
      END


