      SUBROUTINE SET_STRING_IN_ARRAY_CORE(
     &  STRINGS_ARRAY,ALLOCATED_ARRAY,
     &  ARRAY_SIZE,STRING_LEN,ARRAY_INDEX,STRING_INDEX,VALUE,ERROR,*)

C#### Subroutine: SET_STRING_IN_ARRAY_CORE
C###  Description:
C###    The core routing to set a string value in an array of arrays.

      IMPLICIT NONE

!     Parameter List
      INTEGER ARRAY_INDEX,ARRAY_SIZE,STRING_INDEX,STRING_LEN
      CHARACTER VALUE*(*),ERROR*(*)
      POINTER STRINGS_ARRAY(ARRAY_INDEX),
     &  ALLOCATED_ARRAY(ARRAY_INDEX)
     
!     Local Variables
      INTEGER i

      CALL ENTERS('SET_STRING_IN_ARRAY_CORE',*9999)

      IF(ARRAY_INDEX.GT.ARRAY_SIZE)THEN
        DO i=ARRAY_SIZE+1,ARRAY_INDEX
          STRINGS_ARRAY(i)=0
          ALLOCATED_ARRAY(i)=0
        ENDDO
        ARRAY_SIZE=ARRAY_INDEX
      ENDIF
      
      CALL SET_STRING(STRINGS_ARRAY(ARRAY_INDEX),
     &  ALLOCATED_ARRAY(ARRAY_INDEX),STRING_LEN,
     &  STRING_INDEX,VALUE,ERROR,*9999)

      CALL EXITS('SET_STRING_IN_ARRAY_CORE')
      RETURN
 9999 CALL ERRORS('SET_STRING_IN_ARRAY_CORE',ERROR)
      CALL EXITS('SET_STRING_IN_ARRAY_CORE')
      RETURN 1
      END


