      SUBROUTINE SET_LABEL_CORE(LABELS_PTR,TOTAL_LABELS,
     &  ALLOCATED_LABELS,LABEL,ERROR,*)

C#### Subroutine: SET_LABEL_CORES
C###  Description:
C###    The core routine to sets a label in an array.

      IMPLICIT NONE

!     Parameter List
      INTEGER ALLOCATED_LABELS,TOTAL_LABELS
      CHARACTER LABEL*(*),LABELS_PTR(ALLOCATED_LABELS)*(*),ERROR*(*)

      CALL ENTERS('SET_LABEL_CORE',*9999)
      
      TOTAL_LABELS=TOTAL_LABELS+1
      LABELS_PTR(TOTAL_LABELS)=LABEL

      CALL EXITS('SET_LABEL_CORE')
      RETURN
 9999 CALL ERRORS('SET_LABEL_CORE',ERROR)
      CALL EXITS('SET_LABEL_CORE')
      RETURN 1
      END


