      SUBROUTINE SET_INTEGER(INTEGERS_PTR,ALLOCATED_VALUES,INDEX,VALUE,
     &  ERROR,*)

C#### Subroutine: SET_INTEGER
C###  Description:
C###    Sets a integer in an array.

      IMPLICIT NONE
      INCLUDE 'mach00.inc'

!     Parameter List
      POINTER INTEGERS_PTR
      INTEGER ALLOCATED_VALUES,INDEX,NEW_ALLOCATION,MEM_INCR,VALUE
      PARAMETER (MEM_INCR=10)
      CHARACTER ERROR*(*)

      CALL ENTERS('SET_INTEGER',*9999)

      
      IF(INDEX.GT.ALLOCATED_VALUES)THEN
        NEW_ALLOCATION=((INT(INDEX/MEM_INCR))+1)*MEM_INCR
        CALL REALLOCATE_MEMORY(NEW_ALLOCATION,INTTYPE,INTEGERS_PTR,
     &    ERROR,*9999)
        ALLOCATED_VALUES=NEW_ALLOCATION
      ENDIF
      
      CALL SET_INTEGER_CORE(%VAL(INTEGERS_PTR),ALLOCATED_VALUES,
     &  INDEX,VALUE,ERROR,*9999)

      CALL EXITS('SET_INTEGER')
      RETURN
 9999 CALL ERRORS('SET_INTEGER',ERROR)
      CALL EXITS('SET_INTEGER')
      RETURN 1
      END


