      SUBROUTINE SET_STRING(STRINGS_PTR,ALLOCATED_STRINGS,STRING_LEN,
     &  INDEX,VALUE,ERROR,*)

C#### Subroutine: SET_STRING
C###  Description:
C###    Sets a string in an array.

      IMPLICIT NONE
      INCLUDE 'mach00.inc'

!     Parameter List
      POINTER STRINGS_PTR
      INTEGER ALLOCATED_STRINGS,INDEX,NEW_ALLOCATION,MEM_INCR,
     &  STRING_LEN
      PARAMETER (MEM_INCR=10)
      CHARACTER VALUE*(*),ERROR*(*)

      CALL ENTERS('SET_STRING',*9999)

      
      IF(INDEX.GT.ALLOCATED_STRINGS)THEN
        NEW_ALLOCATION=((INT(INDEX/MEM_INCR))+1)*MEM_INCR
        CALL REALLOCATE_MEMORY(NEW_ALLOCATION*STRING_LEN,CHARTYPE,
     &    STRINGS_PTR,ERROR,*9999)
        ALLOCATED_STRINGS=NEW_ALLOCATION
      ENDIF
      
      CALL SET_STRING_CORE(%VAL(STRINGS_PTR),ALLOCATED_STRINGS,
     &  INDEX,VALUE,ERROR,%VAL(STRING_LEN),*9999)

      CALL EXITS('SET_STRING')
      RETURN
 9999 CALL ERRORS('SET_STRING',ERROR)
      CALL EXITS('SET_STRING')
      RETURN 1
      END


