      SUBROUTINE ITERATE(ISEG,CSEG,ECHO,END,STRING,INTWORK,REALWORK,
     '  ERROR,*)

C#### Subroutine: ITERATE
C###  Description:
C###    ITERATE is a buffer call to the iteration handler ITERATE_DYNAM.

      IMPLICIT NONE
      INCLUDE 'ktyp00.cmn'
      INCLUDE 'mxch.inc'
      INCLUDE 'ofst00.cmn'
      INCLUDE 'solv00.cmn'
!     Parameter List
      INTEGER ISEG(*),INTWORK(NIWM)
      REAL*8 REALWORK(NRWM)
      CHARACTER CSEG(*)*(*),ERROR*(*),STRING*(MXCH)
      LOGICAL ECHO,END
!     Local Variables

      CALL ENTERS('ITERATE',*9999)

      IF(KTYP20.LT.3) THEN
        CALL ITERATE_DYNAM(ISEG,REALWORK(OS_RESID),REALWORK(OS_RESIDM),
     '    CSEG,ECHO,END,STRING,INTWORK,REALWORK,ERROR,*9999)
      ELSEIF(KTYP20.GE.3) THEN
        IF(USE_SOLVE_ACTIV) THEN
          CALL ITERATE_DYNAM3(ISEG,CSEG,ECHO,END,STRING,INTWORK,
     '      REALWORK,ERROR,*9999)
        ELSE
          CALL ITERATE_DYNAM2(ISEG,CSEG,ECHO,END,STRING,INTWORK,
     '      REALWORK,ERROR,*9999)
        ENDIF
      ENDIF

      CALL EXITS('ITERATE')
      RETURN
 9999 CALL ERRORS('ITERATE',ERROR)
      CALL EXITS('ITERATE')
      RETURN 1
      END


