      SUBROUTINE DESTROY_CSTRING(C_STRING_PTR)

C#### Subroutine: DESTROY_CSTRING
C###  Description:
C###    DESTROY_CSTRING deallocates memory to alloacted by
C###    CREATE_CSTRING.

      IMPLICIT NONE
      CHARACTER*(*) ROUTINENAME
      PARAMETER(ROUTINENAME='DESTROY_CSTRING')
      INCLUDE 'mach00.inc'
!     Parameter List
      INTEGER*4 C_STRING_PTR
!     Local Variables
      CHARACTER ERROR*100

      CALL ENTERS(ROUTINENAME,*1)
 1    CONTINUE

      CALL FREE_MEMORY(C_STRING_PTR,ERROR,*9999)

      CALL EXITS(ROUTINENAME)
      RETURN
 9999 CALL ERRORIN(ROUTINENAME)
      CALL EXITS(ROUTINENAME)
      RETURN
      END


