      SUBROUTINE ADD_EQUATION_NOTE(EQUATION_LABEL,NOTE,ERROR,*)

C#### Subroutine: ADD_EQUATION_NOTE
C###  Description:
C###    Adds a line of description or notes for an equation.

      IMPLICIT NONE
      INCLUDE 'equation00.cmn'

!     Parameter List
      CHARACTER EQUATION_LABEL*(*),NOTE*(*),ERROR*(*)
!     Local Variables
      INTEGER EQUATION_INDEX

      CALL ENTERS('ADD_EQUATION_NOTE',*9999)

      CALL GET_EQUATION_INDEX(EQUATION_LABEL,EQUATION_INDEX,ERROR,*9999)
      
      CALL SET_LABEL_IN_ARRAY(
     &  EQUATION_NOTE_ARRAY,
     &  EQUATION_NOTE_TOTAL_ARRAY,
     &  EQUATION_NOTE_ALLOC_ARRAY,
     &  EQUATION_NOTE_ARRAY_SIZE,
     &  EQUATION_INDEX,EQUATION_NOTE_LEN,NOTE,
     &  ERROR,*9999)

      CALL EXITS('ADD_EQUATION_NOTE')
      RETURN
 9999 CALL ERRORS('ADD_EQUATION_NOTE',ERROR)
      CALL EXITS('ADD_EQUATION_NOTE')
      RETURN 1
      END


