      SUBROUTINE ADD_EQUATION_OUTPUT(EQUATION_LABEL,OUTPUT_LABEL,
     &  ERROR,*)

C#### Subroutine: ADD_EQUATION_OUTPUT
C###  Description:
C###    Adds a new equation output variable.

      IMPLICIT NONE
      INCLUDE 'equation00.cmn'

!     Parameter List
      CHARACTER EQUATION_LABEL*(*),OUTPUT_LABEL*(*),ERROR*(*)
!     Local Variables
      INTEGER EQUATION_INDEX

      CALL ENTERS('ADD_EQUATION_OUTPUT',*9999)

      CALL GET_EQUATION_INDEX(EQUATION_LABEL,EQUATION_INDEX,ERROR,*9999)
      
      CALL SET_LABEL_IN_ARRAY(
     &  EQN_OUT_LABELS_ARRAY,
     &  EQN_OUT_TOTAL_ARRAY,
     &  EQN_OUT_ALLOC_ARRAY,
     &  EQN_OUT_ARRAY_SIZE,
     &  EQUATION_INDEX,EQN_OUT_LABELS_LEN,OUTPUT_LABEL,
     &  ERROR,*9999)

      CALL EXITS('ADD_EQUATION_OUTPUT')
      RETURN
 9999 CALL ERRORS('ADD_EQUATION_OUTPUT',ERROR)
      CALL EXITS('ADD_EQUATION_OUTPUT')
      RETURN 1
      END


