      SUBROUTINE ADD_EQUATION_INPUT(EQUATION_LABEL,INPUT_LABEL,ERROR,*)

C#### Subroutine: ADD_EQUATION_INPUT
C###  Description:
C###    Adds a new equation input variable.

      IMPLICIT NONE
      INCLUDE 'equation00.cmn'

!     Parameter List
      CHARACTER EQUATION_LABEL*(*),INPUT_LABEL*(*),ERROR*(*)
!     Local Variables
      INTEGER EQUATION_INDEX

      CALL ENTERS('ADD_EQUATION_INPUT',*9999)

      CALL GET_EQUATION_INDEX(EQUATION_LABEL,EQUATION_INDEX,ERROR,*9999)
      
      CALL SET_LABEL_IN_ARRAY(
     &  EQN_IN_LABELS_ARRAY,
     &  EQN_IN_TOTAL_ARRAY,
     &  EQN_IN_ALLOC_ARRAY,
     &  EQN_IN_ARRAY_SIZE,
     &  EQUATION_INDEX,EQN_IN_LABELS_LEN,INPUT_LABEL,
     &  ERROR,*9999)

      CALL EXITS('ADD_EQUATION_INPUT')
      RETURN
 9999 CALL ERRORS('ADD_EQUATION_INPUT',ERROR)
      CALL EXITS('ADD_EQUATION_INPUT')
      RETURN 1
      END


