      BLOCK DATA EQUATION00

      IMPLICIT NONE
      INCLUDE 'equation00.cmn'

! Use equation objects
      DATA USE_EQUATION_OBJECT/.FALSE./

! Equation Labels
      DATA EQUATION_LABELS_PTR/0/
      DATA ALLOCATED_EQUATION_LABELS/0/
      DATA TOTAL_EQUATION_LABELS/0/

! Equation class
      DATA EQUATION_CLASS_PTR/0/
      DATA ALLOCATED_EQUATION_CLASS/0/

! Equation nx
      DATA EQUATION_NX_PTR/0/
      DATA ALLOCATED_EQUATION_NX/0/

! Equation verbosity
      DATA EQUATION_VERBOSE_PTR/0/
      DATA ALLOCATED_EQUATION_VERBOSE/0/

! Equation Notes
      DATA EQUATION_NOTE_ARRAY/0/
      DATA EQUATION_NOTE_TOTAL_ARRAY/0/
      DATA EQUATION_NOTE_ALLOC_ARRAY/0/
      DATA EQUATION_NOTE_ARRAY_SIZE/0/

! Equation Parameters
      DATA EQN_IN_LABELS_ARRAY/0/
      DATA EQN_IN_TOTAL_ARRAY/0/
      DATA EQN_IN_ALLOC_ARRAY/0/
      DATA EQN_IN_ARRAY_SIZE/0/

! Equation Parameters NM index
      DATA EQN_IN_NM_ARRAY/0/
      DATA EQN_IN_NM_ALLOC_ARRAY/0/
      DATA EQN_IN_NM_ARRAY_SIZE/0/

! Equation Parameters Initial Values
      DATA EQN_IN_INIT_VALUE_ARRAY/0/
      DATA EQN_IN_INIT_VALUE_ALLOC_ARRAY/0/
      DATA EQN_IN_INIT_VALUE_ARRAY_SIZE/0/

! Equation Parameters values
      DATA EQN_IN_VALUE_ARRAY/0/
      DATA EQN_IN_VALUE_ALLOC_ARRAY/0/
      DATA EQN_IN_VALUE_ARRAY_SIZE/0/

! Equation Parameters map type
      DATA EQN_IN_MAP_TYPE_ARRAY/0/
      DATA EQN_IN_MAP_TYPE_ALLOC_ARRAY/0/
      DATA EQN_IN_MAP_TYPE_ARRAY_SIZE/0/

! Equation Parameters map parent label
      DATA EQN_IN_MAP_PARENT_ARRAY/0/
      DATA EQN_IN_MAP_PARENT_ALLOC_ARRAY/0/
      DATA EQN_IN_MAP_PARENT_ARRAY_SIZE/0/

! Equation Parameters map INPUT label
      DATA EQN_IN_MAP_CHILD_ARRAY/0/
      DATA EQN_IN_MAP_CHILD_ALLOC_ARRAY/0/
      DATA EQN_IN_MAP_CHILD_ARRAY_SIZE/0/

! Equation Parameters
      DATA EQN_OUT_LABELS_ARRAY/0/
      DATA EQN_OUT_TOTAL_ARRAY/0/
      DATA EQN_OUT_ALLOC_ARRAY/0/
      DATA EQN_OUT_ARRAY_SIZE/0/

! Equation Parameters NH index
      DATA EQN_OUT_NH_ARRAY/0/
      DATA EQN_OUT_NH_ALLOC_ARRAY/0/
      DATA EQN_OUT_NH_ARRAY_SIZE/0/

! Equation Parameters NIY index
      DATA EQN_OUT_NIY_ARRAY/0/
      DATA EQN_OUT_NIY_ALLOC_ARRAY/0/
      DATA EQN_OUT_NIY_ARRAY_SIZE/0/

      END



