      SUBROUTINE GET_EQUATION_INPUT_NM(EQUATION_LABEL,INPUT_LABEL,
     &  NM,ERROR,*)

C#### Subroutine: GET_EQUATION_INPUT_NM
C###  Description:
C###    Gets the nm index for a equation input variable.

      IMPLICIT NONE
      INCLUDE 'equation00.cmn'

!     Parameter List
      INTEGER EQUATION_INDEX,INPUT_INDEX,NM
      CHARACTER EQUATION_LABEL*(*),INPUT_LABEL*(*),ERROR*(*)

      CALL ENTERS('GET_EQUATION_INPUT_NM',*9999)

      CALL GET_EQUATION_INDEX(EQUATION_LABEL,EQUATION_INDEX,ERROR,*9999)
      CALL GET_EQUATION_INPUT_INDEX(EQUATION_LABEL,INPUT_LABEL,
     &  INPUT_INDEX,ERROR,*9999)

      CALL GET_INTEGER_IN_ARRAY(EQN_IN_NM_ARRAY,
     &  EQN_IN_NM_ALLOC_ARRAY,
     &  EQN_IN_NM_ARRAY_SIZE,
     &  EQUATION_INDEX,INPUT_INDEX,NM,ERROR,*9999)

      CALL EXITS('GET_EQUATION_INPUT_NM')
      RETURN
 9999 CALL ERRORS('GET_EQUATION_INPUT_NM',ERROR)
      CALL EXITS('GET_EQUATION_INPUT_NM')
      RETURN 1
      END


