      SUBROUTINE GET_EQUATION_INPUT_TOTAL(EQUATION_LABEL,
     &  TOTAL_EQUATION_INPUT,ERROR,*)

C#### Subroutine: GET_EQUATION_INPUT_TOTAL
C###  Description:
C###    Gets the total number of equation input variables.

      IMPLICIT NONE
      INCLUDE 'equation00.cmn'

!     Parameter List
      INTEGER TOTAL_EQUATION_INPUT,EQUATION_INDEX
      CHARACTER EQUATION_LABEL*(EQUATION_LABELS_LEN),ERROR*(*)

      CALL ENTERS('GET_EQUATION_INPUT_TOTAL',*9999)
      
      CALL GET_EQUATION_INDEX(EQUATION_LABEL,EQUATION_INDEX,ERROR,*9999)
      
      CALL GET_TOTAL_IN_ARRAY(
     &  %VAL(EQN_IN_TOTAL_ARRAY),EQN_IN_ARRAY_SIZE,
     &  EQUATION_INDEX,TOTAL_EQUATION_INPUT,ERROR,*9999)

      CALL EXITS('GET_EQUATION_INPUT_TOTAL')
      RETURN
 9999 CALL ERRORS('GET_EQUATION_INPUT_TOTAL',ERROR)
      CALL EXITS('GET_EQUATION_INPUT_TOTAL')
      RETURN 1
      END


