      SUBROUTINE GET_EQUATION_INPUT_INDEX(EQUATION_LABEL,INPUT_LABEL,
     &  INPUT_INDEX,ERROR,*)

C#### Subroutine: GET_EQUATION_INPUT_INDEX
C###  Description:
C###    Returns the index of an equation input variable.

      IMPLICIT NONE
      INCLUDE 'equation00.cmn'

!     Parameter List
      INTEGER EQUATION_INDEX,INPUT_INDEX
      CHARACTER EQUATION_LABEL*(*),INPUT_LABEL*(*),ERROR*(*)
      

      CALL ENTERS('GET_EQUATION_INPUT_INDEX',*9999)
      
      CALL GET_EQUATION_INDEX(EQUATION_LABEL,EQUATION_INDEX,ERROR,*9999)

      CALL GET_INDEX_IN_ARRAY(EQN_IN_LABELS_ARRAY,
     &  EQN_IN_TOTAL_ARRAY,
     &  EQN_IN_ALLOC_ARRAY,
     &  EQN_IN_ARRAY_SIZE,EQUATION_INDEX,
     &  EQN_IN_LABELS_LEN,
     &  INPUT_LABEL,INPUT_INDEX,ERROR,*9999)

      CALL EXITS('GET_EQUATION_INPUT_INDEX')
      RETURN
 9999 CALL ERRORS('GET_EQUATION_INPUT_INDEX',ERROR)
      CALL EXITS('GET_EQUATION_INPUT_INDEX')
      RETURN 1
      END


