      SUBROUTINE GET_EQUATION_OUTPUT_INDEX(EQUATION_LABEL,OUTPUT_LABEL,
     &  OUTPUT_INDEX,ERROR,*)

C#### Subroutine: GET_EQUATION_OUTPUT_INDEX
C###  Description:
C###    Returns the index of an equation output variable.

      IMPLICIT NONE
      INCLUDE 'equation00.cmn'

!     Parameter List
      INTEGER EQUATION_INDEX,OUTPUT_INDEX
      CHARACTER EQUATION_LABEL*(*),OUTPUT_LABEL*(*),ERROR*(*)
      

      CALL ENTERS('GET_EQUATION_OUTPUT_INDEX',*9999)
      
      CALL GET_EQUATION_INDEX(EQUATION_LABEL,EQUATION_INDEX,ERROR,*9999)

      CALL GET_INDEX_IN_ARRAY(EQN_OUT_LABELS_ARRAY,
     &  EQN_OUT_TOTAL_ARRAY,
     &  EQN_OUT_ALLOC_ARRAY,
     &  EQN_OUT_ARRAY_SIZE,EQUATION_INDEX,
     &  EQN_OUT_LABELS_LEN,
     &  OUTPUT_LABEL,OUTPUT_INDEX,ERROR,*9999)

      CALL EXITS('GET_EQUATION_OUTPUT_INDEX')
      RETURN
 9999 CALL ERRORS('GET_EQUATION_OUTPUT_INDEX',ERROR)
      CALL EXITS('GET_EQUATION_OUTPUT_INDEX')
      RETURN 1
      END


