      SUBROUTINE GET_EQUATION_NOTE_TOTAL(EQUATION_LABEL,
     &  TOTAL_EQUATION_NOTE,ERROR,*)

C#### Subroutine: GET_EQUATION_NOTE_TOTAL
C###  Description:
C###    Gets the total number of lines for an equation description.

      IMPLICIT NONE
      INCLUDE 'equation00.cmn'

!     Parameter List
      INTEGER TOTAL_EQUATION_NOTE,EQUATION_INDEX
      CHARACTER EQUATION_LABEL*(EQUATION_LABELS_LEN),ERROR*(*)

      CALL ENTERS('GET_EQUATION_NOTE_TOTAL',*9999)
      
      CALL GET_EQUATION_INDEX(EQUATION_LABEL,EQUATION_INDEX,ERROR,*9999)
      
      CALL GET_TOTAL_IN_ARRAY(
     &  %VAL(EQUATION_NOTE_TOTAL_ARRAY),EQUATION_NOTE_ARRAY_SIZE,
     &  EQUATION_INDEX,TOTAL_EQUATION_NOTE,ERROR,*9999)

      CALL EXITS('GET_EQUATION_NOTE_TOTAL')
      RETURN
 9999 CALL ERRORS('GET_EQUATION_NOTE_TOTAL',ERROR)
      CALL EXITS('GET_EQUATION_NOTE_TOTAL')
      RETURN 1
      END


