      SUBROUTINE GET_EQUATION_OUTPUT_TOTAL(EQUATION_LABEL,
     &  TOTAL_EQUATION_OUTPUT,ERROR,*)

C#### Subroutine: GET_EQUATION_OUTPUT_TOTAL
C###  Description:
C###    Gets the total number of equation output variables.

      IMPLICIT NONE
      INCLUDE 'equation00.cmn'

!     Parameter List
      INTEGER TOTAL_EQUATION_OUTPUT,EQUATION_INDEX
      CHARACTER EQUATION_LABEL*(EQUATION_LABELS_LEN),ERROR*(*)

      CALL ENTERS('GET_EQUATION_OUTPUT_TOTAL',*9999)
      
      CALL GET_EQUATION_INDEX(EQUATION_LABEL,EQUATION_INDEX,ERROR,*9999)
      
      CALL GET_TOTAL_IN_ARRAY(
     &  %VAL(EQN_OUT_TOTAL_ARRAY),
     &  EQN_OUT_ARRAY_SIZE,EQUATION_INDEX,
     &  TOTAL_EQUATION_OUTPUT,ERROR,*9999)

      CALL EXITS('GET_EQUATION_OUTPUT_TOTAL')
      RETURN
 9999 CALL ERRORS('GET_EQUATION_OUTPUT_TOTAL',ERROR)
      CALL EXITS('GET_EQUATION_OUTPUT_TOTAL')
      RETURN 1
      END


