      SUBROUTINE GET_EQUATION_NX(EQUATION_LABEL,EQUATION_NX,
     &  ERROR,*)

C#### Subroutine: GET_EQUATION_NX
C###  Description:
C###    Gets the nx number of an equation.

      IMPLICIT NONE
      INCLUDE 'equation00.cmn'

!     Parameter List
      INTEGER EQUATION_INDEX,EQUATION_NX
      CHARACTER EQUATION_LABEL*(*),ERROR*(*)

      CALL ENTERS('GET_EQUATION_NX',*9999)

      CALL GET_EQUATION_INDEX(EQUATION_LABEL,EQUATION_INDEX,ERROR,*9999)

      CALL GET_INTEGER(EQUATION_NX_PTR,ALLOCATED_EQUATION_NX,
     &  EQUATION_INDEX,EQUATION_NX,ERROR,*9999)

      CALL EXITS('GET_EQUATION_NX')
      RETURN
 9999 CALL ERRORS('GET_EQUATION_NX',ERROR)
      CALL EXITS('GET_EQUATION_NX')
      RETURN 1
      END


