      SUBROUTINE GET_EQUATION_INPUT_MAP(EQUATION_LABEL,
     &  EQN_IN_LABEL,DEST_TYPE,DEST_LABEL,
     &  DEST_INPUT_LABEL,ERROR,*)

C#### Subroutine: GET_EQUATION_INPUT_MAP
C###  Description:
C###    Gets the mapping for an equation input variable.

      IMPLICIT NONE
      INCLUDE 'equation00.cmn'
      INCLUDE 'maths00.cmn'

!     Parameter List
      CHARACTER DEST_LABEL*(*),DEST_INPUT_LABEL*(*),DEST_TYPE*(*),
     &  EQUATION_LABEL*(*),EQN_IN_LABEL*(*),ERROR*(*)
!     Local Variables
      INTEGER EQUATION_INDEX,EQN_IN_INDEX

      CALL ENTERS('GET_EQUATION_INPUT_MAP',*9999)

      CALL GET_EQUATION_INDEX(EQUATION_LABEL,EQUATION_INDEX,ERROR,*9999)
      CALL ASSERT(EQUATION_INDEX.GT.0,'Equation label not found',
     &  ERROR,*9999)
      CALL GET_EQUATION_INPUT_INDEX(EQUATION_LABEL,EQN_IN_LABEL,
     &  EQN_IN_INDEX,ERROR,*9999)
      CALL ASSERT(EQN_IN_INDEX.GT.0,
     &  'Equation Parameter label not found',ERROR,*9999)
     
      CALL GET_STRING_IN_ARRAY(
     &  EQN_IN_MAP_TYPE_ARRAY,
     &  EQN_IN_MAP_TYPE_ALLOC_ARRAY,
     &  EQN_IN_MAP_TYPE_ARRAY_SIZE,
     &  EQN_IN_MAP_TYPE_LEN,
     &  EQUATION_INDEX,EQN_IN_INDEX,DEST_TYPE,
     &  ERROR,*9999)
      
      IF(DEST_TYPE.NE.'VALUE')THEN

        CALL GET_STRING_IN_ARRAY(
     &    EQN_IN_MAP_PARENT_ARRAY,
     &    EQN_IN_MAP_PARENT_ALLOC_ARRAY,
     &    EQN_IN_MAP_PARENT_ARRAY_SIZE,
     &    EQN_IN_MAP_PARENT_LEN,
     &    EQUATION_INDEX,EQN_IN_INDEX,DEST_LABEL,
     &    ERROR,*9999)

        CALL GET_STRING_IN_ARRAY(
     &    EQN_IN_MAP_CHILD_ARRAY,
     &    EQN_IN_MAP_CHILD_ALLOC_ARRAY,
     &    EQN_IN_MAP_CHILD_ARRAY_SIZE,
     &    EQN_IN_MAP_CHILD_LEN,
     &    EQUATION_INDEX,EQN_IN_INDEX,DEST_INPUT_LABEL,
     &    ERROR,*9999)
     
      ELSE
        DEST_LABEL = ' '
        DEST_INPUT_LABEL = ' '
      ENDIF

      CALL EXITS('GET_EQUATION_INPUT_MAP')
      RETURN
 9999 CALL ERRORS('GET_EQUATION_INPUT_MAP',ERROR)
      CALL EXITS('GET_EQUATION_INPUT_MAP')
      RETURN 1
      END

