      SUBROUTINE GET_EQUATION_OUTPUT_NIY(EQUATION_LABEL,OUTPUT_LABEL,
     &  NIY,ERROR,*)

C#### Subroutine: GET_EQUATION_OUTPUT_NIY
C###  Description:
C###    Gets the niy index for an equation output variable.

      IMPLICIT NONE
      INCLUDE 'equation00.cmn'

!     Parameter List
      INTEGER EQUATION_INDEX,OUTPUT_INDEX,NIY
      CHARACTER EQUATION_LABEL*(*),OUTPUT_LABEL*(*),ERROR*(*)

      CALL ENTERS('GET_EQUATION_OUTPUT_NIY',*9999)

      CALL GET_EQUATION_INDEX(EQUATION_LABEL,EQUATION_INDEX,ERROR,*9999)
      CALL GET_EQUATION_OUTPUT_INDEX(EQUATION_LABEL,OUTPUT_LABEL,
     &  OUTPUT_INDEX,ERROR,*9999)

      CALL GET_INTEGER_IN_ARRAY(EQN_OUT_NIY_ARRAY,
     &  EQN_OUT_NIY_ALLOC_ARRAY,
     &  EQN_OUT_NIY_ARRAY_SIZE,
     &  EQUATION_INDEX,OUTPUT_INDEX,NIY,ERROR,*9999)

      CALL EXITS('GET_EQUATION_OUTPUT_NIY')
      RETURN
 9999 CALL ERRORS('GET_EQUATION_OUTPUT_NIY',ERROR)
      CALL EXITS('GET_EQUATION_OUTPUT_NIY')
      RETURN 1
      END


