      SUBROUTINE GET_EQUATION_OUTPUT_LABEL(EQUATION_LABEL,
     &  OUTPUT_INDEX,OUTPUT_LABEL,ERROR,*)

C#### Subroutine: GET_EQUATION_OUTPUT_LABEL
C###  Description:
C###    Gets the label for an equation given an index.

      IMPLICIT NONE
      INCLUDE 'equation00.cmn'

!     Parameter List
      INTEGER EQUATION_INDEX,OUTPUT_INDEX
      CHARACTER EQUATION_LABEL*(*),OUTPUT_LABEL*(*),ERROR*(*)

      CALL ENTERS('GET_EQUATION_OUTPUT_LABEL',*9999)

      CALL GET_EQUATION_INDEX(EQUATION_LABEL,EQUATION_INDEX,ERROR,*9999)

      CALL GET_LABEL_IN_ARRAY(EQN_OUT_LABELS_ARRAY,
     &  EQN_OUT_ALLOC_ARRAY,EQN_OUT_ARRAY_SIZE,
     &  EQUATION_INDEX,OUTPUT_INDEX,EQN_OUT_LABELS_LEN,
     &  OUTPUT_LABEL,ERROR,*9999)

      CALL EXITS('GET_EQUATION_OUTPUT_LABEL')
      RETURN
 9999 CALL ERRORS('GET_EQUATION_OUTPUT_LABEL',ERROR)
      CALL EXITS('GET_EQUATION_OUTPUT_LABEL')
      RETURN 1
      END


