      SUBROUTINE GET_EQUATION_LABEL(EQUATION_INDEX,EQUATION_LABEL,
     &  ERROR,*)

C#### Subroutine: GET_EQUATION_LABEL
C###  Description: GET_EQUATION_LABEL
C###     Gets the label for an equation given an index.

      IMPLICIT NONE
      INCLUDE 'equation00.cmn'

!     Parameter List
      INTEGER EQUATION_INDEX
      CHARACTER EQUATION_LABEL*(*),ERROR*(*)

      CALL ENTERS('GET_EQUATION_LABEL',*9999)

      CALL GET_LABEL(EQUATION_LABELS_PTR,ALLOCATED_EQUATION_LABELS,
     &  EQUATION_INDEX,EQUATION_LABELS_LEN,EQUATION_LABEL,ERROR,*9999)

      CALL EXITS('GET_EQUATION_LABEL')
      RETURN
 9999 CALL ERRORS('GET_EQUATION_LABEL',ERROR)
      CALL EXITS('GET_EQUATION_LABEL')
      RETURN 1
      END


