      SUBROUTINE GET_EQUATION_INDEX(EQUATION_LABEL,INDEX,ERROR,*)

C#### Subroutine: GET_EQUATION_INDEX
C###  Description:
C###    Returns teh index of a equation

      IMPLICIT NONE
      INCLUDE 'equation00.cmn'

!     Parameter List
      INTEGER INDEX
      CHARACTER EQUATION_LABEL*(*),ERROR*(*)
      

      CALL ENTERS('GET_EQUATION_INDEX',*9999)

      CALL GET_INDEX(EQUATION_LABELS_PTR,
     &  TOTAL_EQUATION_LABELS,ALLOCATED_EQUATION_LABELS,
     &  EQUATION_LABELS_LEN,EQUATION_LABEL,INDEX,ERROR,*9999)

      CALL EXITS('GET_EQUATION_INDEX')
      RETURN
 9999 CALL ERRORS('GET_EQUATION_INDEX',ERROR)
      CALL EXITS('GET_EQUATION_INDEX')
      RETURN 1
      END


