      SUBROUTINE GET_EQUATION_INPUT_LABEL(EQUATION_LABEL,
     &  INPUT_INDEX,INPUT_LABEL,ERROR,*)

C#### Subroutine: GET_EQUATION_INPUT_LABEL
C###  Description:
C###    Gets an equation input variable label given an index.

      IMPLICIT NONE
      INCLUDE 'equation00.cmn'

!     Parameter List
      INTEGER EQUATION_INDEX,INPUT_INDEX
      CHARACTER EQUATION_LABEL*(*),INPUT_LABEL*(*),ERROR*(*)

      CALL ENTERS('GET_EQUATION_INPUT_LABEL',*9999)

      CALL GET_EQUATION_INDEX(EQUATION_LABEL,EQUATION_INDEX,ERROR,*9999)

      CALL GET_LABEL_IN_ARRAY(EQN_IN_LABELS_ARRAY,
     &  EQN_IN_ALLOC_ARRAY,EQN_IN_ARRAY_SIZE,
     &  EQUATION_INDEX,INPUT_INDEX,EQN_IN_LABELS_LEN,
     &  INPUT_LABEL,ERROR,*9999)

      CALL EXITS('GET_EQUATION_INPUT_LABEL')
      RETURN
 9999 CALL ERRORS('GET_EQUATION_INPUT_LABEL',ERROR)
      CALL EXITS('GET_EQUATION_INPUT_LABEL')
      RETURN 1
      END


