      SUBROUTINE GET_EQUATION_INPUT_VALUE(EQUATION_LABEL,INPUT_LABEL,
     &  VALUE,ERROR,*)

C#### Subroutine: GET_EQUATION_INPUT_VALUE
C###  Description:
C###    Gets the current value of a given equation input variable.

      IMPLICIT NONE
      INCLUDE 'equation00.cmn'

!     Parameter List
      INTEGER EQUATION_INDEX,INPUT_INDEX
      REAL*8 VALUE
      CHARACTER EQUATION_LABEL*(*),INPUT_LABEL*(*),ERROR*(*)

      CALL ENTERS('GET_EQUATION_INPUT_VALUE',*9999)

      CALL GET_EQUATION_INDEX(EQUATION_LABEL,EQUATION_INDEX,ERROR,*9999)
      CALL GET_EQUATION_INPUT_INDEX(EQUATION_LABEL,INPUT_LABEL,
     &  INPUT_INDEX,ERROR,*9999)

      CALL GET_REAL_IN_ARRAY(EQN_IN_VALUE_ARRAY,
     &  EQN_IN_VALUE_ALLOC_ARRAY,
     &  EQN_IN_VALUE_ARRAY_SIZE,
     &  EQUATION_INDEX,INPUT_INDEX,VALUE,ERROR,*9999)

      CALL EXITS('GET_EQUATION_INPUT_VALUE')
      RETURN
 9999 CALL ERRORS('GET_EQUATION_INPUT_VALUE',ERROR)
      CALL EXITS('GET_EQUATION_INPUT_VALUE')
      RETURN 1
      END


