      SUBROUTINE GET_EQUATION_OUTPUT_NH(EQUATION_LABEL,OUTPUT_LABEL,
     &  NH,ERROR,*)

C#### Subroutine: GET_EQUATION_OUTPUT_NH
C###  Description:
C###    Gets the nh index for an equation output variable.

      IMPLICIT NONE
      INCLUDE 'equation00.cmn'

!     Parameter List
      INTEGER EQUATION_INDEX,OUTPUT_INDEX,NH
      CHARACTER EQUATION_LABEL*(*),OUTPUT_LABEL*(*),ERROR*(*)

      CALL ENTERS('GET_EQUATION_OUTPUT_NH',*9999)

      CALL GET_EQUATION_INDEX(EQUATION_LABEL,EQUATION_INDEX,ERROR,*9999)
      CALL GET_EQUATION_OUTPUT_INDEX(EQUATION_LABEL,OUTPUT_LABEL,
     &  OUTPUT_INDEX,ERROR,*9999)

      CALL GET_INTEGER_IN_ARRAY(EQN_OUT_NH_ARRAY,
     &  EQN_OUT_NH_ALLOC_ARRAY,
     &  EQN_OUT_NH_ARRAY_SIZE,
     &  EQUATION_INDEX,OUTPUT_INDEX,NH,ERROR,*9999)

      CALL EXITS('GET_EQUATION_OUTPUT_NH')
      RETURN
 9999 CALL ERRORS('GET_EQUATION_OUTPUT_NH',ERROR)
      CALL EXITS('GET_EQUATION_OUTPUT_NH')
      RETURN 1
      END


