      SUBROUTINE PRINT_EQUATION_OUTPUT_VALUES(EQUATION_LABEL,ERROR,*)

C#### Subroutine: PRINT_EQUATION_OUTPUT_VALUES
C###  Description:
C###    Prints the current values of an equations output variables.

      IMPLICIT NONE
      INCLUDE 'cbdi02.cmn'
      INCLUDE 'colours00.cmn'
      INCLUDE 'equation00.cmn'

!     Parameter List
      CHARACTER EQUATION_LABEL*(EQUATION_LABELS_LEN),ERROR*(*)

!     Local Variables
      INTEGER INDEX,TOTAL
      INTEGER IB1,IE1
      CHARACTER OLABEL*(EQN_OUT_LABELS_LEN)

      CALL ENTERS('PRINT_EQUATION_OUTPUT_VALUES',*9999)
          
      CALL GET_EQUATION_INDEX(EQUATION_LABEL,INDEX,ERROR,*9999)

      CALL ASSERT(INDEX.NE.0,'Error: Equation label not found',
     &  ERROR,*9999)

      CALL GET_EQUATION_OUTPUT_TOTAL(EQUATION_LABEL,TOTAL,ERROR,*9999)
      
      DO INDEX=1,TOTAL
        CALL GET_EQUATION_OUTPUT_LABEL(EQUATION_LABEL,INDEX,OLABEL,
     &    ERROR,*9999)
        CALL STRING_TRIM(OLABEL,IB1,IE1)
        WRITE(OP_STRING,'(6X,'''//COLOUR_CHILD//OLABEL(IB1:IE1)
     &    //COLOUR_DEFAULT//''')')
        CALL WRITES(IOFI,OP_STRING,ERROR,*9999)
      ENDDO
      
       

      CALL EXITS('PRINT_EQUATION_OUTPUT_VALUES')
      RETURN
 9999 CALL ERRORS('PRINT_EQUATION_OUTPUT_VALUES',ERROR)
      CALL EXITS('PRINT_EQUATION_OUTPUT_VALUES')
      RETURN 1
      END


