      SUBROUTINE PRINT_EQUATION_VALUES(EQUATION_LABEL,ERROR,*)

C#### Subroutine: PRINT_EQUATION_VALUES
C###  Description:
C###    Prints the current values of an equatios input and output 
C###    variables.

      IMPLICIT NONE
      INCLUDE 'cbdi02.cmn'
      INCLUDE 'colours00.cmn'
      INCLUDE 'equation00.cmn'

!     Parameter List
      CHARACTER EQUATION_LABEL*(EQUATION_LABELS_LEN),ERROR*(*)

!     Local Variables
      INTEGER INDEX,TOTAL
      INTEGER IB1,IB2,IE1,IE2
      REAL*8 VALUE
      CHARACTER ILABEL*(EQN_IN_LABELS_LEN),
     &  OLABEL*(EQN_OUT_LABELS_LEN),
     &  VALUE_STRING*32

      CALL ENTERS('PRINT_EQUATION_VALUES',*9999)
          
      CALL GET_EQUATION_INDEX(EQUATION_LABEL,INDEX,ERROR,*9999)

      CALL STRING_TRIM(EQUATION_LABEL,IB1,IE1)
      WRITE(OP_STRING,'(3X,''Inputs:'')')
      CALL WRITES(IOFI,OP_STRING,ERROR,*9999)

      CALL GET_EQUATION_INPUT_TOTAL(EQUATION_LABEL,TOTAL,ERROR,*9999)
        
      DO INDEX=1,TOTAL
        CALL GET_EQUATION_INPUT_LABEL(EQUATION_LABEL,INDEX,ILABEL,
     &    ERROR,*9999)
        CALL GET_EQUATION_INPUT_VALUE(EQUATION_LABEL,ILABEL,
     &    VALUE,ERROR,*9999)
        WRITE(VALUE_STRING,'('' = '',D12.5)') VALUE
          
        CALL STRING_TRIM(ILABEL,IB1,IE1)
        CALL STRING_TRIM(VALUE_STRING,IB2,IE2)
        WRITE(OP_STRING,'(6X,'''//COLOUR_CHILD//ILABEL(IB1:IE1)
     &    //COLOUR_DEFAULT//' '//VALUE_STRING(IB2:IE2)//''')')
        CALL WRITES(IOFI,OP_STRING,ERROR,*9999)
      ENDDO
      
      WRITE(OP_STRING,'(3X,''Outputs:'')')
      CALL WRITES(IOFI,OP_STRING,ERROR,*9999)

      CALL GET_EQUATION_OUTPUT_TOTAL(EQUATION_LABEL,TOTAL,ERROR,*9999)
      
      DO INDEX=1,TOTAL
        CALL GET_EQUATION_OUTPUT_LABEL(EQUATION_LABEL,INDEX,OLABEL,
     &    ERROR,*9999)
        CALL STRING_TRIM(OLABEL,IB1,IE1)
        WRITE(OP_STRING,'(6X,'''//COLOUR_CHILD//OLABEL(IB1:IE1)
     &    //COLOUR_DEFAULT//''')')
        CALL WRITES(IOFI,OP_STRING,ERROR,*9999)
      ENDDO
      WRITE(OP_STRING,'()')
      CALL WRITES(IOFI,OP_STRING,ERROR,*9999)
      
       

      CALL EXITS('PRINT_EQUATION_VALUES')
      RETURN
 9999 CALL ERRORS('PRINT_EQUATION_VALUES',ERROR)
      CALL EXITS('PRINT_EQUATION_VALUES')
      RETURN 1
      END


