      SUBROUTINE SET_EQUATION_INPUT_INIT_VALUE(EQUATION_LABEL,
     &  INPUT_LABEL,INITIAL_VALUE,ERROR,*)

C#### Subroutine: SET_EQUATION_INPUT_INIT_VALUE
C###  Description:
C###    Sets the initial value for an equation input variable.

      IMPLICIT NONE
      INCLUDE 'equation00.cmn'

!     Parameter List
      REAL*8 INITIAL_VALUE
      CHARACTER EQUATION_LABEL*(*),INPUT_LABEL*(*),ERROR*(*)
!     Local Variables
      INTEGER EQUATION_INDEX,INPUT_INDEX

      CALL ENTERS('SET_EQUATION_INPUT_INIT_VALUE',*9999)

      CALL GET_EQUATION_INDEX(EQUATION_LABEL,EQUATION_INDEX,ERROR,*9999)
      CALL GET_EQUATION_INPUT_INDEX(EQUATION_LABEL,INPUT_LABEL,
     &  INPUT_INDEX,ERROR,*9999)
      
      CALL SET_REAL_IN_ARRAY(
     &  EQN_IN_INIT_VALUE_ARRAY,
     &  EQN_IN_INIT_VALUE_ALLOC_ARRAY,
     &  EQN_IN_INIT_VALUE_ARRAY_SIZE,
     &  EQUATION_INDEX,INPUT_INDEX,INITIAL_VALUE,
     &  ERROR,*9999)

      CALL EXITS('SET_EQUATION_INPUT_INIT_VALUE')
      RETURN
 9999 CALL ERRORS('SET_EQUATION_INPUT_INIT_VALUE',ERROR)
      CALL EXITS('SET_EQUATION_INPUT_INIT_VALUE')
      RETURN 1
      END


