      SUBROUTINE SET_EQUATION_CLASS(EQUATION_LABEL,EQUATION_CLASS,
     &  ERROR,*)

C#### Subroutine: SET_EQUATION_CLASS
C###  Description:
C###    Sets the class number of an equation.

      IMPLICIT NONE
      INCLUDE 'equation00.cmn'

!     Parameter List
      INTEGER EQUATION_INDEX,EQUATION_CLASS
      CHARACTER EQUATION_LABEL*(*),ERROR*(*)

      CALL ENTERS('SET_EQUATION_CLASS',*9999)

      CALL GET_EQUATION_INDEX(EQUATION_LABEL,EQUATION_INDEX,ERROR,*9999)

      CALL SET_INTEGER(EQUATION_CLASS_PTR,ALLOCATED_EQUATION_CLASS,
     &  EQUATION_INDEX,EQUATION_CLASS,ERROR,*9999)

      CALL EXITS('SET_EQUATION_CLASS')
      RETURN
 9999 CALL ERRORS('SET_EQUATION_CLASS',ERROR)
      CALL EXITS('SET_EQUATION_CLASS')
      RETURN 1
      END


