      SUBROUTINE SET_EQUATION_VERBOSE(EQUATION_LABEL,EQUATION_VERBOSE,
     &  ERROR,*)

C#### Subroutine: SET_EQUATION_VERBOSE
C###  Description:
C###    Sets the verbosity level of an equation.

      IMPLICIT NONE
      INCLUDE 'equation00.cmn'

!     Parameter List
      INTEGER EQUATION_INDEX,EQUATION_VERBOSE
      CHARACTER EQUATION_LABEL*(*),ERROR*(*)

      CALL ENTERS('SET_EQUATION_VERBOSE',*9999)

      CALL GET_EQUATION_INDEX(EQUATION_LABEL,EQUATION_INDEX,ERROR,*9999)

      CALL SET_INTEGER(EQUATION_VERBOSE_PTR,ALLOCATED_EQUATION_VERBOSE,
     &  EQUATION_INDEX,EQUATION_VERBOSE,ERROR,*9999)

      CALL EXITS('SET_EQUATION_VERBOSE')
      RETURN
 9999 CALL ERRORS('SET_EQUATION_VERBOSE',ERROR)
      CALL EXITS('SET_EQUATION_VERBOSE')
      RETURN 1
      END


