      SUBROUTINE SET_USER_DOUBLE(NAME,VALUE,ERR_CODE)

C#### Subroutine: SET_USER_DOUBLE
C###  Description:
C###    Sets an interpreter variable NAME to real*8 VALUE.
C     Created: KAT 2001-09-19

      IMPLICIT NONE
      CHARACTER*(*) ROUTINENAME
      PARAMETER(ROUTINENAME='SET_USER_DOUBLE')

      INCLUDE 'comm00.cmn'

      !Argument Variables
      CHARACTER*(*) NAME
      REAL*8 VALUE
      INTEGER ERR_CODE
      !Local Variables
      INTEGER*4 NAME_PTR
      INTEGER STATUS

      CALL ENTERS(ROUTINENAME,*999)

      NAME_PTR=0
      CALL CREATE_CSTRING(NAME_PTR,NAME)
      IF(NAME_PTR.EQ.0) GOTO 999

      CALL INTERPRETER_SET_DOUBLE(%VAL(INTERPRETER_PTR),
     &  %VAL(NAME_PTR),VALUE,STATUS)

      CALL DESTROY_CSTRING(NAME_PTR)

      IF(STATUS.EQ.0) GOTO 999

      ERR_CODE=0
      CALL EXITS(ROUTINENAME)
      RETURN

 999  CALL ERRORIN(ROUTINENAME)
      ERR_CODE=1
      CALL EXITS(ROUTINENAME)
      END ! SUBROUTINE SET_USER_DOUBLE


