      SUBROUTINE SET_USER_CHARACTER(NAME,VALUE,ERR_CODE)

C#### Subroutine: SET_USER_CHARACTER
C###  Description:
C###    Sets an interpreter variable NAME to character VALUE.
C     Created: KAT 2001-09-19

      IMPLICIT NONE
      CHARACTER*(*) ROUTINENAME
      PARAMETER(ROUTINENAME='SET_USER_CHARACTER')

      INCLUDE 'comm00.cmn'

      !Argument Variables
      CHARACTER*(*) NAME,VALUE
      INTEGER ERR_CODE
      !Local Variables
      INTEGER*4 NAME_PTR,VALUE_PTR
      INTEGER STATUS

      CALL ENTERS(ROUTINENAME,*999)

      NAME_PTR=0
      CALL CREATE_CSTRING(NAME_PTR,NAME)
      IF(NAME_PTR.EQ.0) GOTO 999

      VALUE_PTR=0
      CALL CREATE_CSTRING(VALUE_PTR,VALUE)
      IF(VALUE_PTR.EQ.0) THEN
        STATUS=0
      ELSE

        CALL INTERPRETER_SET_STRING(%VAL(INTERPRETER_PTR),
     &    %VAL(NAME_PTR),%VAL(VALUE_PTR),STATUS)
        
        CALL DESTROY_CSTRING(VALUE_PTR)

      ENDIF !VALUE_PTR

      CALL DESTROY_CSTRING(NAME_PTR)

      IF(STATUS.EQ.0) GOTO 999

      ERR_CODE=0
      CALL EXITS(ROUTINENAME)
      RETURN

 999  CALL ERRORIN(ROUTINENAME)
      ERR_CODE=1
      CALL EXITS(ROUTINENAME)
      END ! SUBROUTINE SET_USER_CHARACTER


